### ISSUE TITLE
GET requests for https://example.com?para1=test&FUZZ=test1

### ISSUE THREAD

**Issue by 4huo** [ffuf/ffuf#108]
how can I use -u flag with url "https://example.com?para1=test&FUZZ=test1".

**Comment by joohoi** [comment]
Hi, can you elaborate the question a bit? This looks like the correct syntax indeed.

`ffuf -u 'https://example.com?para1=test&FUZZ=test1' -w '/path/to/wordlist.txt'`

**Comment by joohoi** [comment]
If you wish to use multiple wordlists, or have a need to rename the `FUZZ` variable, you can do this by providing the keyword within the `-w` flag, separated by a colon, like: `-w '/path/to/wordlist.txt:CUSTOM' -u 'https://CUSTOM.example.org`

**Comment by 4huo** [comment]
Ah, it's my default. I didn't add '' for url. Thanks for checking~

**Comment by joohoi** [comment]
No problem, I think your issue there was the shell catching the `&` which is a special character for creating background jobs. The other option would then be escaping the char like:
```
ffuf -u https://example.com/?para1=test\&FUZZ=test1 -w /path/to/wordlist.txt
```

**Comment by 4huo** [comment]
Got it! Thanks again~
