### ISSUE TITLE
Status code 415

### ISSUE THREAD

**Issue by crinny** [ffuf/ffuf#109]
I am trying to run ffuf with the following command:
```
ffuf -w wordlist.txt -u https://mysite.com/api/v1/rest-auth/login/ -X POST -d "username=u336\&password=FUZZ\&add_captcha=false\&csrfmiddlewaretoken=" -v
```
And getting error 415 (Unsupported Media Type) on every request, though when I try sending a request from https://reqbin.com/ everything is OK.
![image](https://user-images.githubusercontent.com/42045258/69416220-2abaeb00-0d27-11ea-892b-8c35825eeb3f.png)

![image](https://user-images.githubusercontent.com/42045258/69416144-03641e00-0d27-11ea-9dff-4dc422225117.png)

**Comment by joohoi** [comment]
You are probably missing `Content-Type` header or something similar. Check the reqbin Headers tab and add everything you might need with `-H "Headername: Headervalue"` on ffuf cli

**Comment by crinny** [comment]
Thanks! That did work. Though I am still getting status code 400. Can i somehow save or look at full response from the server, not just status code or word count?

**Comment by joohoi** [comment]
Unfortunately that's not possible as of yet, but will probably be a feature in the future releases.  That said, you should be able to reconstruct the request in `curl` as ffuf aims to be cli compatible to reasonable length with it. The only header ffuf itself adds is the `User-Agent`, so besides that, you should be able to get same responses by just substituting `ffuf` with `curl` on the cli, and getting rid of `-u` before the URL as well as `-w` and its argument.
