### ISSUE TITLE
improve output

### ISSUE THREAD

**Issue by AnotherWayIn** [ffuf/ffuf#111]
hey mate,
Firstly, great tool! 
Any chance you could increase the spacing in the output so that the columns fall in line pls?
This will make it much easier to scroll through and noticed subtle differences in word count/sizes
thanks
![image](https://user-images.githubusercontent.com/10500665/69537157-72a57080-0fba-11ea-9936-8777e6d78a7b.png)

**Comment by joohoi** [comment]
Thanks! 

It's kind of painful to try to fit result lines with three (or more) variable-length entries in consistent spacing, as we don't know the potential lengths of subsequent outputs (as we print the results as we go). Also the exact values are important, so we cannot shorten them either. 

I don't know if it fits your use case, but the verbose mode `-v` prints the wordlist entries (as well as full URL) on their own  lines, automatically making them to fall in line with each other. The downside of course being each result taking up multiple lines worth of space in the terminal screen.

**Comment by AnotherWayIn** [comment]
ok thanks i will give that a go

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
