### ISSUE TITLE
File input with two modes

### ISSUE THREAD

**Issue by theblackturtle** [ffuf/ffuf#112]
For example:

**Wordlist:**
```
index.php
backup.php
bak.php
```
**Site list:**
```
https://domain1.com/FUZZ
https://domain2.com/FUZZ
https://domain3.com/FUZZ
```

**Mode 1**: Scan each site
```
https://domain1.com/index.php
https://domain1.com/backup.php
https://domain1.com/bak.php

https://domain2.com/index.php
https://domain2.com/backup.php
https://domain2.com/bak.php

...
```

**Mode 2**: Scan all sites with a word. With this method, it can reduce the banned rate very much and a server still fine with large traffic.
```
https://domain1.com/index.php
https://domain2.com/index.php
https://domain3.com/index.php

https://domain1.com/backup.php
https://domain2.com/backup.php
https://domain3.com/backup.php
```

**Comment by joohoi** [comment]
This is already implemented and works when using the multiple wordlists feature:

```
ffuf -v -c -u "HOST/FUZZ" -w "hosts.txt:HOST" -w "fuzz.txt:FUZZ"
```
The iteration order of wordlists are the same than they appear on the command line, so in this example the hosts.txt wordlist gets first iterated through for the first entry in the fuzz.txt wordlist, then the second and so on.

**Comment by joohoi** [comment]
The behavior explained in the previous comment is the behavior of the "Mode 2" in your proposal. To get the "Mode 1" behavior, just change the order of wordlists in the command line:

```
ffuf -v -c -u "HOST/FUZZ" -w "fuzz.txt:FUZZ" -w "hosts.txt:HOST" 
```

**Comment by joohoi** [comment]
I'm closing this issue as resolved, if you feel this is not the case, feel free to comment here and we can reopen it.
