### ISSUE TITLE
SIGABRT v0.12 on Ubuntu 19.10

### ISSUE THREAD

**Issue by p4fg** [ffuf/ffuf#117]
Attempting to fuzz differents hosts using commandline:

`./ffuf -u FUZZ/Some/path/here -w hosts.txt -mc 200 -fw 0-10,20-10000 -o output.json -t 20`

Working fine for 2-3 minutes with correct hits, then:

```
        /'___\  /'___\           /'___\
       /\ \__/ /\ \__/  __  __  /\ \__/
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/
         \ \_\   \ \_\  \ \____/  \ \_\
          \/_/    \/_/   \/___/    \/_/

       v0.12
________________________________________________

 :: Method           : GET
 :: URL              : FUZZ/Some/path/here
 :: Output file      : output.json
 :: File format      : json
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 20
 :: Matcher          : Response status: 200
 :: Filter           : Response words: 0-10,20-10000
________________________________________________

<STATUS MSG CUT>

SIGABRT: abort
PC=0x7f36e34183eb m=18 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f36e34183eb
stack: frame={sp:0x7f369fffb2c0, fp:0x0} stack=[0x7f369f7ff288,0x7f369fffee88)
00007f369fffb1c0:  00007f36e3587fef  000000000000000f
00007f369fffb1d0:  00000002fffffffe  00007f36e35bc440
00007f369fffb1e0:  0000000000000000  ffffffffffff0000
00007f369fffb1f0:  454c36312d465455  0000000000002f2f
00007f369fffb200:  ffff0000000000ff  ffff000000000000
00007f369fffb210:  0000000000000000  0000000000000000
00007f369fffb220:  ffff000000ff0000  ffff000000ff0000
00007f369fffb230:  00007f369fffb200  0000000000000000
00007f369fffb240:  0000000000000000  ffffffffffffffff
00007f369fffb250:  0000000000000000  0000000000000000
00007f369fffb260:  00007f369fffb500  00007f36e33f97b3
00007f369fffb270:  0000000000000000  0000000000000000
00007f369fffb280:  7b7b7b7b7b7b7b7b  7b7b7b7b7b7b7b4e
00007f369fffb290:  000000c00040d800  000000000000001c
00007f369fffb2a0:  0000000000000020  000000c00040d820
00007f369fffb2b0:  c95c8146d79d8b00  1b0c52eb5dc741cf
00007f369fffb2c0: <0000000000000000  c200000000000000

<lots of more output here>
```

Shouldnt it be possible to fuzz the host in a URL? (I.e. probing many hosts for a path)

**Comment by p4fg** [comment]
hosts.txt contains hosts including protocols like:

```
http://www.something.com
https://something.else.co.uk
etc..
```

**Comment by p4fg** [comment]
Attached debug info (from piping stdout and stderr to a file):
[debug.log](https://github.com/ffuf/ffuf/files/3916853/debug.log)

**Comment by p4fg** [comment]
$ go version
go version go1.13.4 linux/amd64

**Comment by joohoi** [comment]
Thanks for opening the issue. I think this is something external sending SIGABRT to ffuf process. It could be kernel enforcing resource limits (ulimit) or something else.

Can you check your system and kernel logs if they have any information about it?

This situation can be simulated by running ffuf, and sending external SIGABRT by:
```
kill -6 `ps aux |grep ffuf |grep -v grep |awk '{print $2}'`
```

**Comment by joohoi** [comment]
Regardless, I'll use this issue to track work on catching the abort signal within ffuf and exiting cleanly.

**Comment by joohoi** [comment]
Also, if you have time to debug this further, it would be super helpful to see if this is reproducable when lowering the thread count `-t 1` for example. That would allow seeing the actual culprit in ffuf core dump.

**Comment by p4fg** [comment]
Nothing in the kernel/system logs. 
Does not seem to trigger using `-t 1`

**Comment by joohoi** [comment]
Thanks for the response. I'm trying to figure out how to reproduce the issue (this is the first time it has been reported, and I haven't seen one before). 

Could you provide me with the specs of the box that you encountered the issue with? I'm trying to figure out if it might be happening because some resource has been exhausted.

**Comment by p4fg** [comment]
The problem indeed turned out to be kernel-related (in combination with something in ffuf):

* Running my testing with low amounts of threads (10-15) never gave any crash
* Running with threading 100 gave crashes almost every time; HOWEVER the times that it did not crash it got a lot of error-messges "Too many open files".

Raising the soft-limit to 65k made the problems go away.
However, something is fishy when the application crashes instead of just saying "too many open files".

Maybe the application should do some sanity-checking for high thread-counts (or keep track of open filehandles so that it does not reach more than say 80% of the softlimit?)

**Comment by joohoi** [comment]
Thanks for debugging the issue!

Unfortunately it's not an easy task to keep track of the open file handles - in this case they are created by Go standard library when resolving the domain names (this is the only `ffuf` use case which requires a lot of file handles).

More so, from the provided `debug.log` stack trace it looks like `ffuf` is using the libc `getaddrinfo()` to handle the name resolution. This [should not be the case](https://golang.org/pkg/net/#hdr-Name_Resolution) in Linux systems.

It also looks like different distros handle the file handle exhaustion differently. On Ubuntu 18.04, when exhausting the soft file handle limit, the individual connections just fail, increment the Errors - counter in ffuf, and if `--debug-log` is defined, prints the errors correctly to the debug log:
```
2019/12/04 16:03:13 Get https://example.org/something: dial tcp: lookup my.plaid.com: too many open files
```

**Comment by p4fg** [comment]
Maybe a Go/Ubuntu 19.10 issue then?

**Comment by joohoi** [comment]
Yeah. Could be. I'll have to install a Ubuntu 19.10 box to test this out. Thanks again for your help debugging this!
