### ISSUE TITLE
[Feature request] - Show the selected extensions that are being fuzzed in the header

### ISSUE THREAD

**Issue by BlueAlder** [ffuf/ffuf#120]
Hi, love the tool really cool and fast alternative to gobuster. Would be awesome if you could list the extensions that are being tested in the header along with the Method, URL and Matcher. I have had a few times where I was confused at the output of the tool when I realised that there was a typo or just just forgot to add extensions to my input. 

Since this is such a simple change I would do it myself and create a pull request but I'm not that comfortable with go yet. But I still will have a look at it! 

Thanks!

**Comment by joohoi** [comment]
Well, you are in luck. That's [already implemented](https://github.com/ffuf/ffuf/blob/master/pkg/output/stdout.go#L63-L69). I would recommend just upgrading your `ffuf` installation and you are good to go :)

**Comment by BlueAlder** [comment]
Oh awesome thanks :) Didn't realise. I installed through homebrew so might not have been updated yet.
