### ISSUE TITLE
Filter by regexp doesn't seem to work on responses

### ISSUE THREAD

**Issue by knivets** [ffuf/ffuf#121]
I use `-fr '<filter>'` flag but it still includes responses that have this string. I'm pretty sure that those responses contain this string. However there is no way to confirm this, so I think a flag that allows to debug the response would be a great feature. Finally, I also noticed that I can't filter the responses by header key (e.g. `-fr 'Set-Cookie'`). It seems like most of the match/filter functionality is focused on the body of the message. Perhaps I'm missing something, just let me know. Otherwise I could probably help with the PR on this.

**Comment by joohoi** [comment]
> However there is no way to confirm this, so I think a flag that allows to debug the response would be a great feature.

I have been thinking of adding support for storing the (matched) responses alongside with the requests for this and post processing purposes. This is probably going to happen sooner than later.

>  Finally, I also noticed that I can't filter the responses by header key (e.g. -fr 'Set-Cookie')

You should be. The regex matcher / filter surely does search the headers too. I wonder if this could be case sensitivity issue though. Can you do more tests with case insensitive matching / filtering, in your use case: `-fr '(?i)Set-Cookie' to confirm if this is the case?

**Comment by knivets** [comment]
> I have been thinking of adding support for storing the (matched) responses alongside with the requests for this and post processing purposes. This is probably going to happen sooner than later.

Awesome.

> Can you do more tests with case insensitive matching

I'll check the case sensitivity issue and get back to you.

**Comment by bsysop** [comment]
Idem at here with -mr

Tested

`-mr "(?i)(Item)"`
`-mr "(Item)"`
`-mr "Item"`

Also tested combined with `-mc 200` but always return elements that dont match

```
________________________________________________
 :: Method           : GET
 :: URL              : URL/item
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 20
 :: Matcher          : Response status: 200
 :: Matcher          : Regexp: (?i)(Item)
________________________________________________
```

Any ideia?

MacOS by the way..

**Comment by joohoi** [comment]
If the response contains a string "Example" anywhere, you should be able to match it with exact casing:
`-mr Example` or by case insensitive regex `-mr '(?ì)example'`.

**Comment by knivets** [comment]
Sorry, I totally forgot about this issue. I'll try to do some tests soon

**Comment by bsysop** [comment]
Got it @joohoi, but are returning not just the match and more "no-sense" results, let me show a example.

```
http://cookie.████████.com [Status: 200, Size: 43, Words: 1, Lines: 9]
https://███████.com [Status: 200, Size: 38, Words: 1, Lines: 1]
```

`curl -i http://cookie.████████.com`
```HTTP/1.1 200
Date: Sun, 29 Dec 2019 23:09:56 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 54
Connection: keep-alive
Server: Apache
Strict-Transport-Security: max-age=31536000
Timing-Allow-Origin: *

{"success":false,"message":"Not logged"}
```

Word in -mr arent here,

Maybe chars are found separately?
`ITEM = I, T, E, M found, but not "ITEM"`

**Comment by joohoi** [comment]
Are you running with `-mc 200` here as well? It's really hard to tell because of the high level of retracted information. If you have `-mc 200` (or the default, which is `-mc 200,204,301,302,307,401,403`) it will match both, the responses with the `-mr regex` and any response with status code that's defined in `-mc`.

**Comment by joohoi** [comment]
If you _only_ want to match responses with the regex, you can override the default value of `-mc` by for example `-mc 999` which would match all responses with status code 999, obviously not happening, as well as everything that matches your regex.

**Comment by bsysop** [comment]
This make **totally** sense!

Will try, if by some reason is a real issue, i will come back here!

Thank you very much!

**Comment by joohoi** [comment]
I think this got solved. Regarding the inconvenience of `-mc 999`, it isn't required anymore as of `ffuf v.1.0`. The default `-mc` value will be ignored, if any other matcher (the regex matcher in this case) is defined.

I'm closing this issue as of now, and reopening if needed.

**Comment by bsysop** [comment]
Awesome @joohoi, great job!

if anyone need some additional script, im open to do!

**Comment by NoobGajen** [comment]
I'm using `ffuf version: 2.1.0-dev` and still  -fr <Filter regexp> is not working for me

am i doing anything wrong here ??

```bash
ffuf -w /usr/share/payloads/fuzzdb/attack/unicode/specialchars.txt -u 'http://teacher.htb/moodle/login/index.php' -d 'anchor=&username=Giovanni&password=Th4C00lTheachaFUZZ' -t 1 -fr "Invalid login"
```

**Comment by pwnedDesal** [comment]
> I'm using `ffuf version: 2.1.0-dev` and still `-fr <Filter regexp>` is not working for me.
> 
> I wanna filter those responses which contain "Invalid login"
> 
> Am I doing anything wrong here ??
> 
> ```shell
> ffuf -w /usr/share/payloads/fuzzdb/attack/unicode/specialchars.txt -u 'http://teacher.htb/moodle/login/index.php' -d 'anchor=&username=Giovanni&password=Th4C00lTheachaFUZZ' -t 1 -fr "Invalid login"
> ```

proxy the request using burp then do the search in proxy history
