### ISSUE TITLE
Need help parsing the json output

### ISSUE THREAD

**Issue by dark-warlord14** [ffuf/ffuf#123]
I ran ffuf on 600 urls and stored the result in json format.
I dont know how to parse the output.
Suppose if I have to grep through all 200 response how do I do that?
If you know any tutorial on learning this a link will be appreciated.
Thank you

**Comment by joohoi** [comment]
Check out [gron](https://github.com/tomnomnom/gron) and [jq](https://stedolan.github.io/jq/).

**Comment by w4cky** [comment]
@dark-warlord14 

cat output_file | jq -c '.results[] | {url:.url,status: .status}'
