### ISSUE TITLE
ffuf includes comment lines in wordlists

### ISSUE THREAD

**Issue by pirxthepilot** [ffuf/ffuf#130]
If I have a wordlist that contains comments (preceded by `#`), ffuf also treats it as part of the wordlist. I wonder if it'd be better to ignore instead?

I'm using v0.12.

Thanks, great tool and happy new year!

**Comment by joohoi** [comment]
Some use cases still need the comments to be passed to input as any other character. That said, this feature is already in works in PR #115

**Comment by pirxthepilot** [comment]
Oh, I seem to have missed that PR. Great, thanks!

**Comment by Ice3man543** [comment]
Hey @joohoi @pirxthepilot, I added PR #138 which fixes this issue.

**Comment by joohoi** [comment]
This is fixed by the PR linked above, thanks again @Ice3man543 !
