### ISSUE TITLE
Save Output About

### ISSUE THREAD

**Issue by secfb** [ffuf/ffuf#131]
I used the following command for subdomain on a site.
```bash
ffuf -c -w ~/wordlist/subdomain.txt -u https://tesla.com -H "Host: FUZZ.tesla.com" -fc 301 -t 150
```
## Shortcomings
- We cannot save the results of the scan.
- I wish the results would look like a full url. ( For Example https://shop.tesla.com
https://meet.tesla.com )

**Comment by joohoi** [comment]
> We cannot save the results of the scan.

The requests and responses get written to disk when you use output directory CLI flag: `-od name_for_output_directory`

> I wish the results would look like a full url.

ffuf merely saves the HTTP request and the response to the file, and the name of the file is a md5 hash of the content. This is because many of the use cases revolve around fuzzing some other part of the request than the URL. To get all the information you need saved to files it's suggested to use `-od` in combination with `-o outputfile.json` (or any other output file type by using `-of`).

**Comment by secfb** [comment]
I know these. Only subdomains of the outputs are not listed.
For example
________________________________________________

apps                    [Status: 302, Size: 0, Words: 1, Lines: 1]
shop                    [Status: 200, Size: 76835, Words: 2353, Lines: 1678]
forums                  [Status: 200, Size: 43379, Words: 7142, Lines: 669]
www                     [Status: 200, Size: 103977, Words: 45726, Lines: 1452]
mobile                  [Status: 302, Size: 0, Words: 1, Lines: 1]
billing                 [Status: 302, Size: 0, Words: 1, Lines: 1]
auth                    [Status: 302, Size: 28, Words: 4, Lines: 1]
events                  [Status: 403, Size: 1233, Words: 73, Lines: 30]
partners                [Status: 403, Size: 13, Words: 2, Lines: 1]
marketing               [Status: 403, Size: 1233, Words: 73, Lines: 30]
feedback                [Status: 302, Size: 224, Words: 12, Lines: 8]
inside                  [Status: 200, Size: 3401, Words: 848, Lines: 91]
:: Progress: [999/999] :: 43 req/sec :: Duration: [0:00:23] :: Errors: 3 ::

How do I register only the subdoins from the above? Doesn't that feature?
cat result.txt
apps.tesla.com
shop.tesla.com
forums..tesla.com
www.tesla.com
mobile.tesla.com
.
.
.

**Comment by joohoi** [comment]
You have multiple options, but the one I personally prefer is using json output ( `-of json`) and writing the results using `-o results.json`, and parsing that with a tool of choice; [gron](https://github.com/tomnomnom/gron) and [jq](https://github.com/stedolan/jq) are great tools to achieve that.

**Comment by secfb** [comment]
Only words can be accessed using jq. (to these www,shop). Is still not saved as follows.follows.if I'm wrong would you correct
cat result.txt
apps.tesla.com
shop.tesla.com
forums..tesla.com
.
.
.
```bash
hans@sec# cat word.txt
shop
auth
events
hans@sec# ffuf -c -w /tmp/word.txt -u https://tesla.com -H "Host: FUZZ.tesla.com" -o result.txt

        /'___\  /'___\           /'___\
       /\ \__/ /\ \__/  __  __  /\ \__/
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/
         \ \_\   \ \_\  \ \____/  \ \_\
          \/_/    \/_/   \/___/    \/_/

       v0.12
________________________________________________

 :: Method           : GET
 :: URL              : https://tesla.com
 :: Header           : Host: FUZZ.tesla.com
 :: Output file      : result.txt
 :: File format      : json
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 40
 :: Matcher          : Response status: 200,204,301,302,307,401,403
________________________________________________

shop                    [Status: 200, Size: 76835, Words: 2353, Lines: 1678]
events                  [Status: 403, Size: 1233, Words: 73, Lines: 30]
auth                    [Status: 302, Size: 28, Words: 4, Lines: 1]
:: Progress: [3/3] :: 3 req/sec :: Duration: [0:00:01] :: Errors: 0 ::
```
---
```bash
hans@sec# cat result.txt|jq
{
  "commandline": "ffuf -c -w /tmp/word.txt -u https://tesla.com -H Host: FUZZ.tesla.com -o result.txt",
  "time": "2020-01-02T15:39:05+03:00",
  "results": [
    {
      "input": {
        "FUZZ": "shop"
      },
      "position": 1,
      "status": 200,
      "length": 76835,
      "words": 2353,
      "lines": 1678,
      "redirectlocation": "",
      "url": "https://tesla.com"
    },
    {
      "input": {
        "FUZZ": "events"
      },
      "position": 3,
      "status": 403,
      "length": 1233,
      "words": 73,
      "lines": 30,
      "redirectlocation": "",
      "url": "https://tesla.com"
    },
    {
      "input": {
        "FUZZ": "auth"
      },
      "position": 2,
      "status": 302,
      "length": 28,
      "words": 4,
      "lines": 1,
      "redirectlocation": "/login",
      "url": "https://tesla.com"
    }
  ]
}
```

**Comment by joohoi** [comment]
Ah, now I see your point. Because of the swiss army knife nature of ffuf, it's not a feasible addition (as the FUZZ or any other keyword can appear anywhere in the request). However as you are constructing the `ffuf` command line already, it would be trivial to loop through the words and add them manually in shell script post processing.

**Comment by secfb** [comment]
ffuz really makes the brute force process very fast. That's why I wanted to use it for subdomain detection. Apparently, it doesn't have the ability to save it as a subdomain. I will have to use other tools (gobuster).

Thank you very much for your attention and quick response.

**Comment by joohoi** [comment]
Thanks! String concatenation is pretty trivial task in shell. If you like to keep using ffuf for this, I would definitely suggest looking into it as it'll be immensively useful in other automation tasks further down the line. Best of luck with your endeavors!

**Comment by secfb** [comment]
I no longer use ffuf to detect subdomain. It's already not being added to a list using gron and jq. I don't think it's ridiculous that there's no saving on a list(subdomain).

**Comment by joohoi** [comment]
Sorry if I was unclear about the reasoning. I absolutely don't think that the request is ridiculous. As a generic tool (instead of a tool specifically for virtualhost discovery) I need to account for all of the use cases, and am trying to keep it as simple as possible while enabling as many use cases as possible within the constraints. 

The `Host` header fuzzing is only one of the use cases, and by that rationale adding it would mean it'd make sense to add all the headers to output files. Some fuzz jobs also deal with POST data for example, so It'd make sense to include that too. To solve these use cases, `-ud` flag is already added, and it saves the complete request and response for all of the matches to a file, and this was what I initially thought your original issue was about.

**Comment by joohoi** [comment]
The current minimalist output still gives the possibility to combine and postprocess all the information using shell scripts. An example script for your use case would be:
```
for subdomain in $(jq -r ".results[].input[]" results.json);do echo $subdomain.tesla.com;done
```

**Comment by secfb** [comment]
I presented this as a suggestion that this should be in tool(ffuf). The following sample script is running. Thanks.
Thank you for the answer. 
I wish you good work.

**Comment by aniruddhmistry** [comment]
Hi 
I want to save all HTTP response of the body part in CSV, JSON. is there any way?

**Comment by n3rada** [comment]
Hi maintainers, I would really appreciate it if you could display the contents of the response as `curl -i`. The main use case is when an identification cookie is sent as a response to identify the user and you want to brute force user identification with for example: `seq 20004400 20004500 | ffuf -w -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "contact_id=FUZZ" -u https://portal-client/restricted/preview/ -mc 302`

**Comment by CipherStriker** [comment]
There are several ways to save the output. But the most informational is when using ">>" or piping it through "tee" command. The only problem with that is ffuf banner it not saved in the output file, which has all the necessary information about the scan. If this feature can be added in the future releases then it would be very practical.

**Comment by M3hank** [comment]
> There are several ways to save the output. But the most informational is when using ">>" or piping it through "tee" command. The only problem with that is ffuf banner it not saved in the output file, which has all the necessary information about the scan. If this feature can be added in the future releases then it would be very practical.

Something like this works
```
 ffuf -u https://www.example.com/FUZZ -w wordlist -v  | tee -a ffuf.txt
```

**Comment by CipherStriker** [comment]
Yes, we can do that, but the output file still does not hold the banner
information.
