### ISSUE TITLE
Make recursion depth 1 as default

### ISSUE THREAD

**Issue by dark-warlord14** [ffuf/ffuf#132]

**Comment by joohoi** [comment]
Can you give a bit more context about this request? Rationale etc. I don't think recursion should be enabled by default personally, but I'm up for discussion.

**Comment by dark-warlord14** [comment]
I mean when we enable recursion flag
it hits all endpoints
for e.g
if manager redirect manager/
it adds a job for fuzzing manager/ endpoint
and while fuzzing manager/admin redirects to manager/admin/
new job is added to fuzz manager/admin/ endpoint and the loop continues
by default it should only fuzz upto manager/ and not manager/admin

it that make sense to you or we would have to fuzz a site together. that will be more fun

**Comment by iNoSec2** [comment]
i hope it will not add this, we go away from dirb/dirbuster for this kinds of bad feature. Add it optional yeah but not by default please. and if you want enable it by default make an alias ffuf = "ffuf --recursive 1" for example in your bashrc file

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
