### ISSUE TITLE
Feature request: aggressive recursion strategy

### ISSUE THREAD

**Issue by dark-warlord14** [ffuf/ffuf#133]
with recursion flag on if we hit 200 status for path like /manager/contact.php
then add job for fuzzing manager/.
currently jobs are added only when redirection happens to manager/ 
let me know what you think about this

**Comment by joohoi** [comment]
Interesting idea, I like it! It probably shouldn't be default, so I'm thinking of adding a CLI flag along the lines of  `-recursion-strategy "aggressive"` that would enable this.

**Comment by dark-warlord14** [comment]
not default
but whenever recursion is on the depth should be only 1 or it will take forever to get the job done

**Comment by dark-warlord14** [comment]
I will give an example for this
suppose if we get a hit for `contact/admin.php1 endpoint as `200 OK`
we should add a job for fuzzing `contact/`
I suck at explaining but let me know what you think

**Comment by joohoi** [comment]
This is implemented with `-recursion-strategy greedy`
