### ISSUE TITLE
Feature request: Parse raw request to ffuf options

### ISSUE THREAD

**Issue by joohoi** [ffuf/ffuf#136]
CLI flags `-request` and `-request-proto` should be added to parse a raw request into ffuf options.

The `-request-proto` is used to define the protocol to use as the raw HTTP request itself does not include that information. The possible values being `http` and `https`, defaulting to `https`. This option should only be used in conjunction with `-request`.

Options to parse in from the raw request file:
- Method
- Host
- Headers
- Body (POST/PUT/etc. data)

The parsing should be handled prior to applying other command line parameters to the configuration structure to allow the user to override some of the values in the parsed request.

As an example, a raw request file:
```
GET /FUZZ HTTP/1.1
Host: example.org
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
DNT: 1
```

Would be parsed into `ffuf` configuration structure equivalent of:
```
ffuf -u https://example.org/FUZZ -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Accept-Language: en-US,en;q=0.5" -H "DNT: 1"
```

With the addition, and the raw request example file above, this would result into a `ffuf` command:
```
ffuf -request rawrequest.txt -w wordlist.txt
```

Changing the protocol to `http` instead of the default `https` would be done by:
```
ffuf -request rawrequest.txt -request-proto http -w wordlist.txt
```

Overriding the host to connect, the URL component and the protocol (but not the `Host` header!) could be handled by:
```
ffuf -request rawrequest.txt -u https://ffuf.io.fi/FUZZ -w wordlist.txt
````

And overriding only the `Host` header could be handled by:
```
ffuf -request rawrequest.txt -H "Host: somethingelse.tld" -w wordlist.txt
```

**Comment by joohoi** [comment]
This issue has a [$100 bounty](https://twitter.com/codingo_/status/1217011896194199552) attached to it.

**Comment by phspade** [comment]
This is super cool!

**Comment by Ice3man543** [comment]
Hey, I tried to solve this in pr #137. Let me know if that's what we want.

**Comment by SakiiR** [comment]
hehe nice ! it works :)

**Comment by joohoi** [comment]
Yup! Fixed by the PR linked above, thanks again @Ice3man543

**Comment by ldionmarcil** [comment]
Correct me if I'm wrong, but Host overriding does not appear to work? Specifically, when using a request file with the following command:

`$ ffuf -request req.txt -u https://FUZZ/ -w hostnames.txt`

where `req.txt`:

```http
GET / HTTP/1.1
Host: target.com

```

and `hostnames.txt` is a list of fqdns, the requests are genenrated as such:

```GET / HTTP/1.1
Host: FUZZ

```

Ffuf connects to the hostname found in `hostnames.txt` and not the one in the `Host` of `req.txt`. Am I misusing the feature or is this not supported? 

Thanks!

**Comment by alonek1** [comment]
i have same problem here

**Comment by SakiiR** [comment]
Give the $100 back !

🤣
