### ISSUE TITLE
Filtering by regex breaks when using -od output directory

### ISSUE THREAD

**Issue by nseratt** [ffuf/ffuf#147]
Running two commands:

1. without -od : 
ffuf -c -D -e php -w /home/tools/dirsearch/db/dicc.txt -v -o "/home/user/reports/ffuf/website.com/report-2020-01-24-16-05-20.json" -fr "(?i)(Your request cannot be completed)" -u https://www.website.com/FUZZ

Works as intended. I am only getting results when a match is found that does not contain the regex pattern.

2. with -od output directory flag:

ffuf -c -D -e php -w /home/tools/dirsearch/db/dicc.txt -v -o "/home/user/reports/ffuf/website.com/report-2020-01-24-16-05-20.json" -fr "(?i)(Your request cannot be completed)" -od "/home/user/reports/ffuf/website.com/data/" -u https://www.website.com/FUZZ

Now every result gives a 200, even though they match the string I have configured in the -fr regex in the body. 

Simply removing the -od flag and parameter makes it work correctly, so I think there is some connection with using -od that makes -fr not function anymore.

**Comment by joohoi** [comment]
Thanks for reporting the issue! I looked in to this, and it's a legit bug, resulting from trying to read from body twice. 

It's handled as a stream in go, so typically you can read it only once - the result that `ffuf` was trying to read for regex matching was empty because of this!
