### ISSUE TITLE
Feature request: Adding additional paths to recursion queue

### ISSUE THREAD

**Issue by Damian89** [ffuf/ffuf#148]
Hi,
first of all: thanks for ffuf.

When working with recursion, ffuf currently decides by itself which path to add to the queue. This is great. But sometimes the user knows hidden paths (found in js files, ...) which ffuf won't find (because they are 404 or whatever).

It would be awesome to have a parameter which allows adding own paths in the beginning:

```
ffuf -u https://target/FUZZ -w wl.txt -c -ac -recursion -recursion-depth 2 -recursion-paths admin,secret,more
```

This would add right in the beginning:
```
[INFO] Adding a new job to the queue: https://target/admin/FUZZ
[INFO] Adding a new job to the queue: https://target/secret/FUZZ
[INFO] Adding a new job to the queue: https://target/more/FUZZ
```
ffuf does the job on `https://target/FUZZ` and adds additional paths found and if thats done, ffuf starts the bruteforcing in `admin`, then `secret`, then `more`, then the other paths found by itself.

What do you think? This would automate the whole thing even more - currently the user has to restart ffuf with `-u https://target/admin/FUZZ` and so on. Thats ok, but more automation would be even better ;)

Best,

Damian

**Comment by joohoi** [comment]
I prefer trying not to complicate the ffuf code any more than necessary, and I believe this can be resolved by the user with the current options available.

Two different ways to handle this come to mind:
 - If you know some endpoints already existing, you could add the keyword to your wordlist, that way it would be picked up for recursion.
 - You could use multiple wordlists if you have wildly varying endpoints you are trying to fuzz:
   - endpoints.txt would contain: https://target, https://target/admin, https://target/more
   - `ffuf -w endpoints.txt:ENDPOINT -w wordlist.txt -u ENDPOINT/FUZZ`

What do you think?

**Comment by Damian89** [comment]
Hey, yes, actually this is a good very idea - didn't realize this is possible. From an automation perspective my solution would be easier to handle (since I dont scan one asset, I scan thousands of assets on multiple servers) - but it looks like I have to add this wordlist generation to my own logik.
Best,
Damian
