### ISSUE TITLE
Negative match reponse size filter

### ISSUE THREAD

**Issue by gopinath6** [ffuf/ffuf#152]
i was trying different option to list negative response  size. but i could get the command,Not sure if already implemented
for eg 
ffuf.exe -r -mc 200  -u http://text.com/FUZZ

000000005074            [Status: 200, Size: 12930, Words: 1114, Lines: 271] :: Errors: 0 ::
000000004926            [Status: 200, Size: 12930, Words: 1114, Lines: 271] :: Errors: 0 ::
0000000059              [Status: 200, Size: 12930, Words: 1114, Lines: 271]
000000005311            [Status: 200, Size: 12930, Words: 1114, Lines: 271] :: Errors: 0 ::
0000000061              [Status: 200, Size: 12930, Words: 1114, Lines: 271] :: Errors: 0 ::
0000000062              [Status: 200, Size: 12930, Words: 1114, Lines: 271] :: Errors: 0 ::
0000000065              [Status: 200, Size: 12930, Words: 1114, Lines: 271] :: Errors: 0 ::
0000000063              [Status: 200, Size: 12930, Words: 1114, Lines: 271] :: Errors: 0 ::
0000000067              [Status: 200, Size: 12930, Words: 1114, Lines: 271] :: Errors: 0 ::
0000000064              [Status: 200, Size: 12930, Words: 1114, Lines: 271] :: Errors: 0 ::
0000000066              [Status: 200, Size: 12930, Words: 1114, Lines: 271] :: Errors: 0 ::
0000000068              [Status: 200, Size: 12930, Words: 1114, Lines: 271]
0000000070              [Status: 200, Size: 12930, Words: 1114, Lines: 271]

I do not want result with status =200 with response size=12930.
I need result with status =200 and response size !=12930
Is that possible?
Similarly for lines and words

**Comment by bsysop** [comment]
Yes
```
ffuf -r -mc 200 -fs 12930 -u http://text.com/FUZZ
```

**Comment by bsysop** [comment]
Also you can concatenate multiples values
```
-mc 200,201
-fs 24030,4929
```

**Comment by joohoi** [comment]
and ranges! `-fs 12900-13000,4242`

**Comment by gopinath6** [comment]
Thanks!
