### ISSUE TITLE
Data submission bug

### ISSUE THREAD

**Issue by knivets** [ffuf/ffuf#159]
`-d` won't set `-H 'Content-Type: application/x-www-form-urlencoded'` automatically. Just wasted half an hour trying to understand why `POST` requests are not working 😅

**Comment by joohoi** [comment]
I'm sorry for the trouble, and can understand the frustration. However this is considered working as intended. `ffuf` doesn't set the content type header for different payloads automatically. As there's plenty of different ones depending on the payload, this is left for the users discretion.

I personally find it much easier to work with `-request` and `-request-proto` where you would save the raw request to a file, edit the fuzz keywords in place, and pass it in by: `ffuf -request saved-req.txt -request-proto https ...`.

**Comment by sangvo1991** [comment]
I think if this is intended, it should be mentioned in README.md. Because I take a lot of hours to find out why my POST requests dont work. 

Thank you.

**Comment by bsysop** [comment]
Make sense @sangvo1991, good observation!
