### ISSUE TITLE
Keyword for wordlist not detected in -u option when parsing a request file

### ISSUE THREAD

**Issue by phspade** [ffuf/ffuf#160]
![ffuf-issue](https://user-images.githubusercontent.com/18681023/74081288-4d3be500-4a88-11ea-8645-9514f8937fbe.png)

**Comment by phspade** [comment]
Hi @joohoi 

The tables have turned now haha, now I already confirm that this is fixed, however, if I will do a basic scan like my command:

`ffuf -c -w /path/to/wordlist.txt -u https://example.com -H "Host: FUZZ" -mc all -fc 500-599`

It cannot read the -u flag

**Comment by joohoi** [comment]
How sloppy of me! It's now fixed.
