### ISSUE TITLE
How check url's from a file.

### ISSUE THREAD

**Issue by vishu10x00** [ffuf/ffuf#163]
i have text file.

http://www.cpms.osd.mil/LPDD/LeaderSummit/lds_index.aspx
http://www.cpms.osd.mil:80/lpdd/lpd_about.aspx 
http://www.cpms.osd.mil/lpdd/lpd_about.aspx?mode=print
http://www.cpms.osd.mil:80/lpdd/lpdd_index.aspx 
http://www.cpms.osd.mil:80/lpdd/lpdd_index.aspx?mode=print 
http://www.cpms.osd.mil:80/lpdd/MandS_index.aspx 
http://www.cpms.osd.mil:80/lpdd/MandS_index.aspx?mode=print

now i just want to send the request, to the server no fuzzing.

**Comment by joohoi** [comment]
You should run ffuf with `ffuf -w file.txt -u FUZZ` to achieve this.
