### ISSUE TITLE
dirb mode not working??

### ISSUE THREAD

**Issue by Phoenix1112** [ffuf/ffuf#170]
hello.. thank you for this project. There is something I do not understand. Why can't I brute force the directories it finds like dirb program again.dirb program scans again for directories it finds. When I wanted to do this with ffuf, I could not do it. 

Here is the command I use.

ffuf -c -w fuzz.txt -recursion -recursion-depth 10 -fc 400,403,404 -u https://target.com/FUZZ

does not force the directories it finds again. What am I doing wrong. ??

**Comment by joohoi** [comment]
You are probably hitting a bug that has been fixed in the `master` already: #167 
I would try building the master version and re-running the same command.

**Comment by joohoi** [comment]
I'm closing this issue for now, as it has most likely been already fixed, but feel free to comment if that's not the case and I'll reopen.
