### ISSUE TITLE
Make defining User-agent header case insensitive

### ISSUE THREAD

**Issue by joohoi** [ffuf/ffuf#171]
The `User-agent` header is the only one ffuf sets up automatically. There's currently a bug that makes defining a custom user agent header name case sensitive;

This does not work:
```
ffuf -H "User-agent: custom string" ...
```

While this does:
```
ffuf -H "User-Agent: custom string" ...
```

**Comment by joohoi** [comment]
As noted in #169 @bjhulst wishes to tackle this issue.

**Comment by bjhulst** [comment]
Roger.

**Comment by joohoi** [comment]
This was fixed in #173 

Thanks again @bjhulst !

**Comment by okondo-afo** [comment]
FFUF returns incorrect data with its useragent header, all ffuf data is wrong , it kept returning 403 forbidden when its not

**Comment by spidy-idc** [comment]
> Project37 reacted with eyes emoji

Some websites block ffuf and gobuster user agents, We have to randomize user agents for fuzzing

**Comment by netwons** [comment]
how randomize user agents?
