### ISSUE TITLE
[request] add arbitrary, multiple extensions to requests

### ISSUE THREAD

**Issue by eur0pa** [ffuf/ffuf#19]
Flag: `-e`, Default: (none)
Commandline: `-e .aspx,.php,nodot`
Generator logic (FUZZ = current entry from wordlist): `/FUZZ /FUZZ.aspx /FUZZ.php /FUZZnodot`

**Comment by joohoi** [comment]
Do you think it'd be feasible to list the extensions in a wordlist? This would allow more abstract way of doing this, that would at the same time enable different fuzzing modes with multiple FUZZ keywords. Something that Burp calls Pitchfork and Cluster bomb modes in the Intruder module.

**Comment by eur0pa** [comment]
You normally don't need that many, it's usually 10 or less; commandline is practical enough especially when scripting the tool in automation chains, which would save a step of dumping extensions to file before invoking `ffuf`

**Comment by C0RB3N** [comment]
Hey guys, I actually added this feature for a friend 🙂 It essentially replaces %EXT% like dirsearch does, so I'm sure it wouldn't be hard to just force extensions as well.

**Comment by joohoi** [comment]
> Hey guys, I actually added this feature for a friend slightly_smiling_face It essentially replaces %EXT% like dirsearch does, so I'm sure it wouldn't be hard to just force extensions as well.

👋 I wonder if you would be up to submitting a PR?

**Comment by C0RB3N** [comment]
Yep! I'll touch up the code a bit, it might be later this week as I'm going to the March Madness SemiFinals soon

**Comment by joohoi** [comment]
Sounds good! Looking forward to it. I'd probably prefer some other keyword than %EXT%, though, FFUFEXT for example, even though I don't like that too much either ;) 

I'm up for discussion about keyword refactoring altogether.

**Comment by C0RB3N** [comment]
I meant it replaces %EXT% from any given line in a wordlist :) (Dirsearch's wordlist contains %EXT% where it want's an extension bruteforced, was merely given the opportunity for users like [naffy](https://twitter.com/nnwakelam) use their desired wordlists. It also just force extensions if the line in the wordlist doesn't contain that keyword.

**Comment by joohoi** [comment]
Yup, I was just meaning that as the main keyword is currently `FUZZ` to be replaced by wordlist entry, I would like some other keyword than `%EXT%` to be replaced by the extension provided in a list in command line, but am up for discussion about the keywords altogether.

All in all, I'd like the keyword to be easy to memorize, and something that wouldn't collide with actual requests or shell internals.

**Comment by C0RB3N** [comment]
For sure, I don't care what you do as it's your tool, was just letting you know what I had done :) for now I'll just leave it as is and will add the option to just force extensions

**Comment by joohoi** [comment]
Ok, sounds good! I really appreciate you sending your work upstream as it's clearly something that's needed as a feature.

**Comment by joohoi** [comment]
Now that I understand the patch better, I see that it basically brings the compatibility to DirSearch wordlists with entries like:
```
some_path
some_path.%EXT%
...
```
I'm currently thinking of adding the feature requested by @eur0pa ; adding a new keyword for extensions, and CLI flag to provide the needed extensions. 

That said, I think I'll end up adding a compatibility mode for DirSearch wordlists, using (or building on) the patch kindly provided by @C0RB3N

**Comment by joohoi** [comment]
These features are now in master branch! I'll release a new version in a few days!
