### ISSUE TITLE
Header Information 

### ISSUE THREAD

**Issue by warhanter** [ffuf/ffuf#197]
could you add the used **wordlist** in the header information when **ffuf** is running..

**Comment by helpermika** [comment]
Do you mean adding it here?

________________________________________________

 :: Method           : POST
 :: URL              : http://localhost:8080/
 :: Header           : Content-Type: application/json
 :: Data             : {"Username": "Mika", "Password": "FUZZ"}
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 40
 :: Matcher          : Response status: 200,204,301,302,307,401,403
________________________________________________

**Comment by warhanter** [comment]
Exactly -:)

**Comment by helpermika** [comment]
I take this issue
