### ISSUE TITLE
some Command usage issue's please check  out

### ISSUE THREAD

**Issue by TROUBLE-1** [ffuf/ffuf#201]
![user_redirecting_attackers_site](https://user-images.githubusercontent.com/54508518/77842730-6cffa780-71b3-11ea-8a48-1c3480c5c0a4.JPG)

**Comment by bjhulst** [comment]
Maybe you should run it like ./ffuf after you ran "go build".

**Comment by joohoi** [comment]
Yeah, you should either build the tool and run the generated binary or download and run a prebuilt one from [releases](https://github.com/ffuf/ffuf/releases) page.

Where did you find this way of trying to run ffuf, as it's not even supposed to work that way?

**Comment by TROUBLE-1** [comment]
Its worked, sorry for making it as an issue

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
