### ISSUE TITLE
bash: ffuf: command not found

### ISSUE THREAD

**Issue by rajkamal7404** [ffuf/ffuf#202]
ffuf -w wordlist.txt -u https://example.org/FUZZ -mc all -fs 42 -c -v
when i am enter this command 
then error 
<pre>bash: ffuf: command not found
</pre>

**Comment by joohoi** [comment]
How did you install `ffuf` ? If you installed it manually, you need to use the `/full/directory/path/to/ffuf -w wordlist ...` if it's not on your `$PATH`. If you used `go get ...` for installation, the binary can be found from `$HOME/go/bin/ffuf`. 

This is *NIX 101, and there's plenty of learning resources available. Use provided keywords above for web searches to find more information about the subject :) Happy hacking!
