### ISSUE TITLE
Support multiple words in the same wordlist

### ISSUE THREAD

**Issue by dee-see** [ffuf/ffuf#203]
I don't know how to phrase this clearly so I'll write an example:

hosts.csv
```csv
domain.com,192.168.1.12
sub.domain.com,192.168.1.14
```

wordlist.txt
```txt
admin
supersecret.txt
```

```shell
$ ffuf -u 'https://HOSTS[0]/FUZZ' -H 'Host: HOSTS[1]' -w hosts.csv:HOSTS -w wordlist.txt:FUZZ
```

Basically, I have a list of domains and IP and I want to fuzz those. If I split the domains and IPs in 2 files it will try every domain for every IP and that's not what I want to do. Is this already possible? If not is this something you'd consider for a feature request? 

Thanks for the great tool

**Comment by joohoi** [comment]
I think this would be best handled with a shell script that loops through the values in hosts.csv, and initiates ffuf for each of them with the wordlist.

The functionality here is partly available: the multi-wordlist behavior can be chosen between "pitchfork" and "clusterbomb" modes. The pitchfork would walk the wordlists in lockstep. However in this case it would mean walking the `wordlist.txt` in similar fashion with the domains.

**Comment by dee-see** [comment]
A bash loop around this is probably the best way to go indeed, thanks for the reply!
