### ISSUE TITLE
ffuf should write output while a job is in progress

### ISSUE THREAD

**Issue by justinsteven** [ffuf/ffuf#205]
When doing a long-running `ffuf` it would be useful to have the output file (e.g. JSON) be written periodically, based on results seen so far, so that a user can get a head-start on exploring the results (Preventing https://xkcd.com/303/ :wink:)

**Comment by justinsteven** [comment]
Most of my need for this feature will be handled by the upcoming interactive feature. It looks like you'll be able to break into a long-running scan and emit the intermediate results to a JSON file.

I think it might still be useful enough to leave this on the backlog though - some people might want intermediate results written to a file without needing to break into their scan and manually trigger it. Since writing this issue I've come to learn of NDJSON which is probably a more appropriate output format for intermediate results (you could even stream results line-by-line to the file)

If you'd rather clean up the backlog and close this issue, that's ok with me too :+1:

**Comment by joohoi** [comment]
I'm thinking of adding a new output format: [JSON Lines](https://jsonlines.org/).

This would probably gather to this need?
