### ISSUE TITLE
[request] filter results by blacklist instead of whitelist

### ISSUE THREAD

**Issue by eur0pa** [ffuf/ffuf#21]
**Current logic**

If `resp.Status` matches one of the statuses defined, the entry is valid (match-only)

**Desired logic**

If `resp.Status` *does not* match any of the blacklisted statuses, the entry is valid (match-all)

**Sane defaults**: `404,410,502,503`

**Comment by joohoi** [comment]
Oh, obviously. This is much better way of handling this! Thanks!

**Comment by joohoi** [comment]
This is now implemented in the PR #26 , but you will have to use CLI flag `-mc all` to enable the functionality.
