### ISSUE TITLE
Match regex returns encoded text as a match

### ISSUE THREAD

**Issue by rotemreiss** [ffuf/ffuf#219]
Hi,

I am experiencing a problem with ffuf, and I wonder if it is something that I'm doing wrong.

**What I want to achieve**
Send a URL with a string and if the string is reflected in the response - show it as a match.

**What I tried**
`ffuf -w ./urls.txt -u "FUZZsomeuniquestring<b>" -mr "FUZZsomeuniquestring<b>"`

**Expected result**
Match only if the response actually contains the exact same string (with `<b>`)

**Actual result**
Getting a match even if the response's body contains something like:
`someuniquestring%3Cb%3E`

Am I missing something? Is that the desired behavior as you see it? Any way to get a match only if it is being reflected as is?

Thanks.

**Comment by joohoi** [comment]
I tried to reproduce the issue, and wasn't able to do so. Could you post additional info. What I'm looking for is the complete request + response (you can save them with `-od temp_output_directory` ) as well as the ffuf command line you are using. 

Feel free to anonymize the data. That would provide me the sufficient information to debug this further.

**Comment by rotemreiss** [comment]
Thanks @joohoi, the `-od` helped me to find the problem. It was indeed reflected as-is in the `Location` header of the response.

As far as I remember ffuf doesn't have the ability to check only the body or headers for a match, right?

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
