### ISSUE TITLE
ffuf: command not found

### ISSUE THREAD

**Issue by ram48484** [ffuf/ffuf#220]
I have downloaded and installed ffuf. I also have the go installed. I have downloaded the linux/amd_64 version.

When I am trying to run something like below. 

`ffuf -w /path/to/wordlist -u https://target/FUZZ`

I am getting the below error. 

> -bash: ffuf: command not found

Please help me to resolve the issue

**Comment by joohoi** [comment]
This looks like an issue with `$PATH`. I recommend moving the `ffuf` executable to a directory on your `$PATH` or extending the `$PATH` by: `export $PATH=$PATH:/the/directory/where/your/ffuf/binary/is/installed`.

Alternatively you can run executable with a full (or relative) path to it by: `/path/to/ffuf -w wordlist.txt -u ...` or `./ffuf -w wordlist.txt -u ...`.

**Comment by Th3R0oT** [comment]
For me PATH is setup but still getting the same error.

**Comment by bsysop** [comment]
> For me PATH is setup but still getting the same error.
> 
> export GOPATH=$HOME/go
> export PATH=$PATH:$GOPATH/bin
> 
> export PATH=/usr/local/bin:$PATH
> export $PATH=$PATH:/Users/Arpit/Desktop/ffuf
> export GOPATH=/Users/Arpit/Desktop/Desktop/DevSecOps/BB/go
> export GOPATH=/Users/Arpit/Desktop/ffuf

https://github.com/ffuf/ffuf/issues/277

**Comment by ShebinJoseJacob** [comment]
It seems to be still some path related issues. You may try this 
```
export GOROOT=/usr/local/go

export GOPATH=$HOME/go

export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

echo 'export GOROOT=/usr/local/go' >> ~/.bash_profile

echo 'export GOPATH=$HOME/go'>> ~/.bash_profile	
		
echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >> ~/.bash_profile
	
source ~/.bash_profile
```

(You can use `~/.profile` instead of `~/.bash_profile`)

**Comment by abhipujari23** [comment]
A simple solution which I was able to do is to copy the ffuf bin file to the Binary file for usr

`sudo cp ffuf /usr/bin `

This worked for me and now I can access Fuff
