### ISSUE TITLE
Unknown field when installing.

### ISSUE THREAD

**Issue by MikeSS281986** [ffuf/ffuf#222]
When using command go get github.com/ffuf/ffuf it returns with go/src/github.com/ffuf/ffuf/pkg/runner/simple.go:53:19: unknown field ‘MaxConnsPerHost’ in struct literal of type http.Transport. Thus cannot install ffuf. Any thoughts would be appreciated.

**Comment by joohoi** [comment]
Cheers!
You are trying to build `ffuf` with too old version of Go. It requires `1.11` or greater.
