### ISSUE TITLE
Facing error while using ffuf

### ISSUE THREAD

**Issue by hi10ndr4** [ffuf/ffuf#224]
Encountered error(s): 2 errors occured.
* -u flag or -request flag is required
* Keyword FUZZ defined, but not found in headers, method, URL or POST data.
Please can you explain why I'm facing this error. I have done everything right.
./ffuf -w path of wordlist -u https://target.com/FUZZ
Please suggest what I have to do. Follow each and every steps right.

**Comment by joohoi** [comment]
Common occureance is that people copy paste commands from a website where the dash - might be some other character instead, making ffuf not recognize the -u flag. I wonder if this might be t he issue?

**Comment by joohoi** [comment]
Closing as duplicate for: #227
