### ISSUE TITLE
Getting a single issue everytime i am running ffuf

### ISSUE THREAD

**Issue by Droidzzzio** [ffuf/ffuf#227]
Just firing the normal basic command 
ffuf -u https://example.com/FUZZ -w wordlist.txt 

and getting an error

keyword defined, but not found in headers, method, URL or POST data

Using windows 10 
Problem occured after the updation to latest version of ffuf. 
Please resolve this issue ASAP

**Comment by joohoi** [comment]
I'm unable to reproduce the issue, ffuf seems to work fine on windows 10 and with the latest release:
```
C:\Users\redacted\Downloads\ffuf_1.0.2_windows_amd64>type wordlist.txt
index.html
somethingelse
secret
C:\Users\redacted\Downloads\ffuf_1.0.2_windows_amd64>ffuf -u https://ffuf.io.fi/FUZZ -w wordlist.txt

        /'___\  /'___\           /'___\
       /\ \__/ /\ \__/  __  __  /\ \__/
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/
         \ \_\   \ \_\  \ \____/  \ \_\
          \/_/    \/_/   \/___/    \/_/

       v1.0.2
________________________________________________

 :: Method           : GET
 :: URL              : https://ffuf.io.fi/FUZZ
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 40
 :: Matcher          : Response status: 200,204,301,302,307,401,403
________________________________________________

secret                  [Status: 401, Size: 195, Words: 6, Lines: 8]:: Errors: 0 ::
index.html              [Status: 200, Size: 16, Words: 1, Lines: 4] :: Errors: 0 ::
:: Progress: [3/3] :: Job [1/1] :: 0 req/sec :: Duration: [0:00:00] :: Errors: 0 ::
```

Common occurance is that people copy paste commands from a website where the dash `-` might be some other character instead, making ffuf not recognize the `-u` flag. I wonder if this might be t he issue?

**Comment by Droidzzzio** [comment]
The issue is coming when i am firing ffuf command from the directory where the wordlist exist , . If the wordlist is in the other directory and giving upon the path , the error is ocurring .

**Comment by Droidzzzio** [comment]
C:\Users\malav>ffuf -u https://example.com/FUZZ -w C:\Users\malav\Downloads\SecLists\Fuzzing\LFI\LFI-Jhaddix.txt
Encountered error(s): 1 errors occured.
        * Keyword \Users\malav\Downloads\SecLists\Fuzzing\LFI\LFI-Jhaddix.txt defined, but not found in headers, method, URL or POST data.

**Comment by joohoi** [comment]
This is caused by colon `:` being used as a wordlist:keyword separator. This has been now fixed in a PR.

**Comment by Droidzzzio** [comment]
The tool is now working fine as expected....thanks a lot for resolving the issue.

**Comment by OdinF13** [comment]
> problem:
* Keyword FUZZ defined, but not found in headers, method, URL or POST data.

> solution:
```bash
root@localhost:~/# ffuf -u "https://example.com/FUZZ" -w /path/to/wordlist
```

**Comment by nmunagar** [comment]
I have same error with linux 
Encountered error(s): 1 errors occured.
        * Keyword FUZZ defined, but not found in headers, method, URL or POST data.

**Comment by nmunagar** [comment]
input : ffuf -u https://www.ict.gnu.ac.in/FFUF -w LFI-Jhaddix.txt -c -r -v  
output : Encountered error(s): 1 errors occured.
* Keyword FUZZ defined, but not found in headers, method, URL or POST data.

any idea how to fix...

**Comment by Sam-Sepioll** [comment]
Same issue, doesn't work.

**Comment by joohoi** [comment]
In the example above by @nmunagar he used keyword FFUF, which is incorrect in this context. 

The actual bug here was related to Windows filepaths only, as they have `:` in them.

**Comment by JetFree** [comment]
The same issue, Kali linux, ffuf 1.5.0..

**Comment by bolka64** [comment]
for me, on Kali, ffuf was showing weird repeated “Error” and 0 req/sec, which looked broken but wasn’t.
Turned out it was just the terminal being too narrow — widening it fixed it instantly.
