### ISSUE TITLE
Case In-Sensitive Search (Feature Request)

### ISSUE THREAD

**Issue by unKn0wnUser453** [ffuf/ffuf#229]
Add a windows search option that filters the input list for case in-sensitivity.
aspnet_client           [Status: 301, Size: 155, Words: 9, Lines: 2]
uploadedfiles           [Status: 301, Size: 155, Words: 9, Lines: 2]
uploadedFiles           [Status: 301, Size: 155, Words: 9, Lines: 2]
UploadedFiles           [Status: 301, Size: 155, Words: 9, Lines: 2]
Aspnet_client           [Status: 301, Size: 155, Words: 9, Lines: 2]
aspnet_Client           [Status: 301, Size: 155, Words: 9, Lines: 2]
ASPNET_CLIENT           [Status: 301, Size: 155, Words: 9, Lines: 2]
Aspnet_Client           [Status: 301, Size: 155, Words: 9, Lines: 2]

**Comment by MMrhassel** [comment]
(y)

**Comment by joohoi** [comment]
I think this would be best handled outside of ffuf, in the wordlist generation. To get unique case-insensitive payloads, you can use `uniq` tool thats included in your typical GNU tools.

For example (the `-i` for uniq means case insensitive, and `-w -` for ffuf means "read from stdin"):

```
uniq -i /path/to/wordlist.txt | ffuf -w - -u https://example.org/FUZZ ...
```
