### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by notnoobdude** [ffuf/ffuf#230]
Whenever I try to install it via `go get -u github.com/ffuf/ffuf` it reflects this error:

go get github.com/ffuf/ffuf: copying /tmp/go-build047329942/b001/exe/a.out: open /home/danex/go/bin/ffuf: permission denied

**Comment by joohoi** [comment]
Judging by the error message it looks like you have some permission issues in your local filesystem. This is not a ffuf specific issue, and I'd recommend searching around with the (relevant parts of) error message.
