### ISSUE TITLE
Remove Duplicate Results

### ISSUE THREAD

**Issue by attacker007** [ffuf/ffuf#234]
Dear @Daviey 

I am getting a lot of false positive results. Almost all content-discovery list is giving me 200 OK response with same response Size..

Is there any way to remove these kinda Responses which are giving same Response Sizes?

Thanks.

**Comment by joohoi** [comment]
Hi, please see the different filters that ffuf provides. The size filter (`-fs`) is probably what you are looking for for this use case.

**Comment by Daviey** [comment]
@attacker007 No need to direct questions to me, I've just done a few simple changes, @joohoi is the real hero of ffuf!

**Comment by attacker007** [comment]
Hi Daviey Sorry for disturbing you buddy.. yes .. Indeed @joohoi is the hero... 
I just wanted this tool to be intelligent in a way that it automatically filter "Response Size" When tool gets same Response Size For more than 10 Content-Discovery list words. 

As you told me to use -fs .. its Ok for one target but when we've to test list of url.txt ..Then it will not be easy.

I hope you will review it again !!

**Comment by attacker007** [comment]
Hi @joohoi 

I came across another issue related to this...

Can i use multiple  Response Sizes  with tag "-fs" or only can feed one Response Size? 

Like I am getting Same Response for files like *.php (all *.php file response size is 3400)

And Also Getting Same Response Size for *.Jsp (All *.jsp file response size is 4300)

Sincerely,

**Comment by bsysop** [comment]
Hi @attacker007 

You can use many as you need.

```-fs 100,200,500```

or by ranges

```-fs 100-300```

Also combine it.
