### ISSUE TITLE
-Maxtime-job is not defined on the latest version

### ISSUE THREAD

**Issue by abdilahrf** [ffuf/ffuf#235]
I cannot found the -maxtime-jobs option on the latests version releases.
but it was already on the readme.md.

**Comment by joohoi** [comment]
Hi, that's right. `--maxtime-jobs` is currently only in the unreleased `master` branch, but will be included in the future release. To see the readme (and CHANGELOG) for the release version, please see: [the v1.0.2 release tag](https://github.com/ffuf/ffuf/tree/v1.0.2).
