### ISSUE TITLE
Error in runner while vhostscan

### ISSUE THREAD

**Issue by bugbaba** [ffuf/ffuf#24]
Hi,

while running ffuf to fuzz for virtual-hosts for one of the URL it is giving error 

```
Error in runner: Get https://www.domain.com/: EOF
```

Command running with:
```
./ffuf -k -c -t 10 -mc 200 -w ./wordlist.txt -H 'Host: FUZZ.domain.com' -u https://www.domain.com/ 
```

Things I have tried:
1. Using smaller wordlist
2. Lowering thread counts
3. Trying other fuzzing like parameter for same host

It is just failing for virtual-hosts fuzzing for this URL only.

Thanks

**Comment by joohoi** [comment]
Sounds like there's a reverse proxy, WAF implementation or alike that just kills the connection dead cold when encountering an unexpected `Host` header. Have you tried making a `curl` request to the host using one of the failing names in the wordlist?

**Comment by bugbaba** [comment]
looked at it again, for non valid host the server is replying with empty response. That might be the reason of error as ffuf was trying to get response code and size of an empty response.

**Comment by joohoi** [comment]
I think that answers the original question. Is there something that you feel that should be done differently in such case (on ffuf side)? 

In the master branch, the errors are not printed per default anymore (I'm going to add a CLI flag for verbose output to do that in the future too), but are increasing the error counter in status bar.

**Comment by bugbaba** [comment]
Checking if the response is not null before calculating the status code and response size would be a good precaution method.

**Comment by joohoi** [comment]
I think the error is from the HTTP client implementation rather than the subroutine checking up the response. Do you think there should be another, better way of reporting such errors? This will just increase the Errors: - counter in the master branch, and does not display anything.

I feel that it's effectively an error if HTTP request doesn't get a HTTP response.

**Comment by bugbaba** [comment]
looks good :+1:

**Comment by joohoi** [comment]
Awesome! I'll close the issue for now, if there's something else, please feel free to comment and I'll reopen it.

**Comment by balook** [comment]
use https://FUZZ or http:FUZZ rather than FUZZ.example.com
