### ISSUE TITLE
Feature Request - Inline wordlist

### ISSUE THREAD

**Issue by Rhynorater** [ffuf/ffuf#241]
One of the things that I think would be immensely helpful for ffuf would be some sort of inline wordlist. Something like this perhaps:

```
ffuf -u http://target.com/FUZZ1/FUZZ2 -iw test,test1,stuff:FUZZ1 -w ~/normalwordlist.txt
```
In this scenario, `iw` serves as an `inline wordlist` with comma-separated values.

**Comment by manuelbua** [comment]
You can do that with Bash's process substitution, a bit verbose on the command line, but it works well:
```
ffuf -u "http://the.host/ZZZ/XXX" -w <(echo -e '123\n456\n789'):ZZZ -w <(echo -e 'abc\ndef'):XXX
```

**Comment by joohoi** [comment]
Is this something that couldn't be handled with piping? 

`echo -e "test\ntest1\nstuff" |ffuf -w -:FUZZ1 -w ~/normalwordlist.txt ....`

**Comment by manuelbua** [comment]
Yes a single wordlist can be specified via stdin, not sure the OP intended *multiple* or just a single one: in that case stdin is enough i think.

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
