### ISSUE TITLE
[Feature request] Add a flag to have error logs 

### ISSUE THREAD

**Issue by 0xatul** [ffuf/ffuf#242]
It would be nice to have flag like `--error-log /path/to/errors.txt` to see what gave path/payload gave an error than just having the of numbers of errors at the bottom.

**Comment by bsysop** [comment]
Hi @0xatul, have you take a look in `-debug-log`?
```
OUTPUT OPTIONS:
  -debug-log       Write all of the internal logging to the specified file.
```

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
