### ISSUE TITLE
../go/src/github.com/ffuf/ffuf/pkg/runner/simple.go:53:19: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport

### ISSUE THREAD

**Issue by subhash0x** [ffuf/ffuf#243]
../go/src/github.com/ffuf/ffuf/pkg/runner/simple.go:53:19: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport

**Comment by joohoi** [comment]
You are trying to build ffuf with too old version of Go, ffuf needs to be built with Go >= 1.11
