### ISSUE TITLE
../../../tools/ffuf/main.go:125:15: undefined: Usage error

### ISSUE THREAD

**Issue by littl-one** [ffuf/ffuf#244]
I just installed ffuf, this is what I get :
```
# command-line-arguments
../../../tools/ffuf/main.go:125:15: undefined: Usage
../../../tools/ffuf/main.go:145:3: undefined: Usage
../../../tools/ffuf/main.go:151:3: undefined: Usage
../../../tools/ffuf/main.go:156:3: undefined: Usage
```
I tried installing go version 1.11, and 1.14 both won't produces these issue, I also tried reinstalling it many times, still reproducible. Any fix for this? Thanks

**Comment by joohoi** [comment]
How did you install ffuf and how are you running it? This sounds like it wasn't actually compiled or installed properly.

**Comment by littl-one** [comment]
yep, I managed to get it working now. thanks!
