### ISSUE TITLE
[Feature request] - Ignore lines starting with # and empty ones.

### ISSUE THREAD

**Issue by soufian2017** [ffuf/ffuf#246]
Many wordlists contain the licence/description at the start of the file.
ffuf doesnt ignore those lines by default and in many times in screw up the terminal with content not needed.
This feature would ignore those lines by default.

**Comment by bsysop** [comment]
Hi, take a look in #245

**Comment by soufian2017** [comment]
Missed it by one :stuck_out_tongue_closed_eyes: 
Always RTFM :100:
