### ISSUE TITLE
False positive results when fuzzing for dirs

### ISSUE THREAD

**Issue by its0x08** [ffuf/ffuf#247]
Is it supposed to give empty results?
Lately it has been happening several times.
![ffuf bug](https://i.imgur.com/vfdU3VN.png)

**Comment by joohoi** [comment]
Yeah, it's working as intended, your wordlist has some whitespace characters and the matches are for those.

**Comment by its0x08** [comment]
You are very right about that!!
I investigated and found out that the list has some lines that start with 1 or more spaces.
Thank you for the fast response !
![list entries](https://i.imgur.com/n5VQNmT.png)
