### ISSUE TITLE
The -mr option

### ISSUE THREAD

**Issue by marcelo321** [ffuf/ffuf#248]
Hello! one simple and stupid question. Does the `-mr match regex` works the same as matching something with `grep` command? i have to escape characters like `./[]$` but everything else works the same?

Thanks in advance.

**Comment by bsysop** [comment]
Hi Marcelo, Its a normal Regex in fact!

**Comment by marcelo321** [comment]
Hey @bsysop thanks for the quick answer! what if i want to match different words like when you do with grep. For example `grep 'word1\|word2'` i just tried it and doesn't work, is it possible to grep for differents words?

**Comment by marcelo321** [comment]
Hey soory, just figured it out... you don't have to escape | so `-mr 'word1|word2'`.

**Comment by bsysop** [comment]
Exactly bro, also advanced regex if you need.

**Comment by marcelo321** [comment]
ffuf is truly awesome, got it thanks!!
