### ISSUE TITLE
Feature Reqest:Add a flag to get md5sum of response. 

### ISSUE THREAD

**Issue by 0xatul** [ffuf/ffuf#249]

**Comment by bsysop** [comment]
Hi 0xatul,

It is done yet, when you use `-od` to save files, the file name is in fact the md5sum.

```
$ cat abb73fd82e118b9e220435047486b8e6 | md5sum
abb73fd82e118b9e220435047486b8e6  -
```

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
