### ISSUE TITLE
All errors with Low Threads and Timeout

### ISSUE THREAD

**Issue by marcelo321** [ffuf/ffuf#250]
hello!

I am trying to use ffuf with large wordlist and i lowered the threads and timeouts to the following:
`-timeout 5 -t 10` 

It went perfectly for the first 3 minutes and then i started to get the same errors as requests sent. i looked at the max file descriptors in my vps and it was:
```
# cat /proc/sys/fs/file-max
806576
```

Everything runs ok with almost no errors and at some point it ends up like this:
`:: Progress: [624391/624391] :: Job [1/1] :: 749 req/sec :: Duration: [0:13:53] :: Errors: 611804 ::`

Any idea how to fix this??

**Comment by marcelo321** [comment]
i then used the -debug option and got 600k lines telling me the same error:
`dial tcp: lookup dgjinyu.en.redacted.com: too many open files`.

but as i pasted before, the max open files i can have right now is `806576` which seems a really high number.

**Comment by bsysop** [comment]
E ai mano?

Sadly some (if not most of) VPS don't allow change in fact quantity of files open, since it affects the master machine and it can affect others users.

I recommend you VDS (Virtual Dedicated Server) instead of VPS, i dont found an workaround for that problem too in some VPS.

Btw what is your provider?

**Comment by marcelo321** [comment]
i was able to change the max of files open to 500k and now ffuf runs smoothly (using linode), the problem i just found is, it doesn't release the ram after using it. after using it for some hours it got to use all of my 8gb rams, but after stopping ffuf completely it was still using all of the ram.

**Comment by bsysop** [comment]
Interesting, i got a lot problems in VPS with many tools, finally i just let VPS for small tasks.

Happy hacking bro!. 🤟🏻
