### ISSUE TITLE
Auto detection of Noise and servers spitting the same stuff at u 

### ISSUE THREAD

**Issue by devcoinfet** [ffuf/ffuf#256]
say we are doing enum I see this so much a host would spit nonsense back at us 

cart                    [Status: 200, Size: 49144, Words: 2617, Lines: 11]
partner                 [Status: 200, Size: 49144, Words: 2617, Lines: 11]
tv                      [Status: 200, Size: 49144, Words: 2617, Lines: 11]
demo                    [Status: 200, Size: 49144, Words: 2617, Lines: 11]
employment              [Status: 200, Size: 49144, Words: 2617, Lines: 11]
trans                   [Status: 200, Size: 49144, Words: 2617, Lines: 11]
board                   [Status: 200, Size: 49144, Words: 2617, Lines: 11]
local                   [Status: 200, Size: 49144, Words: 2617, Lines: 11]
45                      [Status: 200, Size: 49144, Words: 2617, Lines: 11]

if it was python i know what i would do but go i do not do that
if its a 200 status code and the size is the same as well as the words and the size and status code alone could be used as a moc  noise reducer could u consider adding this?

**Comment by devcoinfet** [comment]
or say host is responding with the same content for  all 200's seems like a fake response or firewall or something or if its does what did  i miss lol

**Comment by bsysop** [comment]
Manually detect what are "fake positives" or "noisy", stop ffuf and run again with more calibration:

```
ffuf -acc local
```

It will fetch local, then add this to filtering config.

**Comment by joohoi** [comment]
Yeah, if you are ok with the preconfigured requests (some random strings etc.), you can use `-ac` as well.

I'm closing this issue as I feel that it's resolved, in case you disagree, let me know and I'll open it again to continue the discussion.
