### ISSUE TITLE
Adds a more line in the request while using -request 

### ISSUE THREAD

**Issue by hellrider9** [ffuf/ffuf#260]
The tool adds one more line to the request while using -request to load a file containing the HTTP request.This sometimes fails the purpose. That extra line makes the response from the server to be changed opposed to the response expected.
This is the scrrenshot of request to be sent.
![Screenshot from 2020-07-03 20-27-47](https://user-images.githubusercontent.com/56410386/86480685-1da9b400-bd6c-11ea-9b64-b69f94a4a873.png)
This is the screenshot of the request sent as captured by Burpsuite
![Screenshot from 2020-07-03 20-32-43](https://user-images.githubusercontent.com/56410386/86480981-bb9d7e80-bd6c-11ea-9067-52a17ddd17bd.png)
There is one extra line 15 in the request.

![Screenshot from 2020-07-03 20-35-57](https://user-images.githubusercontent.com/56410386/86481052-db34a700-bd6c-11ea-8f18-4d4c5bb11428.png)

**Comment by joohoi** [comment]
I think this is actually your text editor. Many of the editors have a "feature" that adds a newline to the end of every file when saving. You can confirm this by `hexdump -C filename.txt`.

You can disable this feature in vim (which is my weapon of choice) by:
```
$ vim -b filename.txt
:set noeol
```

**Comment by hellrider9** [comment]
Oh Yes. Sorry for opening wrong issue.
