### ISSUE TITLE
Disabled TLS certificate check

### ISSUE THREAD

**Issue by bjhulst** [ffuf/ffuf#272]
Is this set to true on purpose? This does not verify any TLS certificates currently.

https://github.com/ffuf/ffuf/blob/master/pkg/runner/simple.go#L55

InsecureSkipVerify: true,

**Comment by bsysop** [comment]
You can fuzz real SSL domains or also IP's, VirtualHosts, etc.

Have you any scenario where this could give fake results?

**Comment by bjhulst** [comment]
See it more like a question, maybe a rhetorical one. :smile: The http call will work faster without the check and the response arrives with or without a valid cert...

**Comment by bsysop** [comment]
Got it, the main ideia is FUZZ everywhere you want, with/without TLS, etc

**Comment by bjhulst** [comment]
Any comments from @joohoi before I close this... ?

**Comment by joohoi** [comment]
Yeah, it was originally functional and the check was true per default, but I decided to remove that later on as it would naturally break on all kinds of valid scenarios like fuzzing Host header and such. The TLS verification and trust are not in the core scope of the tool after all :)

**Comment by bjhulst** [comment]
closing it.
