### ISSUE TITLE
`-sa` flag didn't worked and ffuf kept sending probes even after hundred of errors

### ISSUE THREAD

**Issue by bugbaba** [ffuf/ffuf#273]
Hi :)

I am faceing this issue **first time**, while running ffuf against a website even after multiple errors being generated and `-sa` flag being specified which implies `-se` and `-sf` ffuf kept sending probes.

ffuf command I used:
```
./ffuf -ac -c -r -sa -w wordlists.txt -mc all -u -fc 400 https://example.com/FUZZ
```

![Screenshot_2020-07-29_05-58-42](https://user-images.githubusercontent.com/29960776/88742909-0b4f4a00-d161-11ea-9354-77f79a9fc0e6.png)

As you can see in the above screenshot around error count was `377` and I had to forcefully close the ffuf.

--
Regard,
@bugbaba

**Comment by joohoi** [comment]
Some of the requests must have been successful in the background. `-sa` implies `-se`, which stops the execution in a case where all the requests return an error. The counter however is reset on every successful request.

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
