### ISSUE TITLE
Make URL column clickable in output HTML file

### ISSUE THREAD

**Issue by hamza02x** [ffuf/ffuf#274]

**Comment by sickwiz** [comment]
Hey, I would like to work with this issue but I am new to golang. Can someone help  me in getting started

**Comment by fabiobauer** [comment]
#323

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
