### ISSUE TITLE
Extension (-e) does not add dot (.ext) in between the filename and the extension

### ISSUE THREAD

**Issue by necross2** [ffuf/ffuf#275]
when specifying an extension (-e) using a wordlist, the request combines the file name from the wordlist together with the extension supplied.
For example, if I have a file name in my wordlist named `info` and I use the `-e php` attribute, the request will go to `example.com/infophp` instead of `example.com/info.php`

**Comment by bsysop** [comment]
Hi buddy,

FFUF is a very very democratic software, different to others "File searchers" like dirsearch, FFUF allow you do FFUZ as you want.. so..

**Extensions normally are:**
```
- .jsp
- .aspx
- .php
etc
```

**but what happens when you want find rare extensions?**

```
_php
__php
._php
```

So ffuf allow you to configure what kind of crazy extensions (and usage) you want.

Good hacking!.

**Comment by necross2** [comment]
What does that have to do anything?
A valid file extension must start with a dot.
If you want to find extension that begin with an underscore, you can for example specify ‘-e _php’ but you still need a dot...

**Comment by bsysop** [comment]
I just forgot to say..

*Usage:*
```
ffuf ... -e ".php,.asp,___php"
```

**Comment by bsysop** [comment]
> What does that have to do anything?
> A valid file extension must start with a dot.
> If you want to find extension that begin with an underscore, you can for example specify ‘-e _php’ but you still need a dot...

I understand your point, and yes, one file extensions must start with a dot, BUT in real world, people are free to use one..two or no dots at all.

**Comment by necross2** [comment]
> > What does that have to do anything?
> > A valid file extension must start with a dot.
> > If you want to find extension that begin with an underscore, you can for example specify ‘-e _php’ but you still need a dot...
> 
> I understand your point, and yes, one file extensions must start with a dot, BUT in real world, people are free to use one..two or no dots at all.

If you want to find files that have no extensions, don’t use -e. Otherwise, a valid file extension must begin with a dot.

**Comment by bsysop** [comment]
Could you elaborate more please?

**Comment by necross2** [comment]
Most wordlists would contain simple file names with no extension.
You can use those to enumerate files or directories. (Providing -w /path/to/wordlists.

If you wanted to use said wordlist to enumerate files with a php extension for example, as is stands now, you would have to specify ‘-e .php’.

If you wanted  wanted multiple extension, you would need to add the dot before each of them (which is redundant)

To your example above, if you wanted to find an extension with multiple underscores, you would need to specify ‘-e .__php’ for example.

Either way, you need a dot when working with extensions. It’s how web servers work...

**Comment by bsysop** [comment]
Got it,

So we are at the start point.

Yes, in FFUF have to specify the character that you consider could exist in that website, underscore, dot, etc

Some backup files are just "filename_bak" without dots.

**Comment by necross2** [comment]
> Got it,
> 
> So we are at the start point.
> 
> Yes, in FFUF have to specify the character that you consider could exist in that website, underscore, dot, etc
> 
> Some backup files are just "filename_bak" without dots.

Right... but those are not extensions... for those you would use ‘-w path/to/wordlist then the target would be https://example.com/FUZZ_bak

**Comment by bsysop** [comment]
Yes, so "extension" is probably not the best word here, probably suffix would fit better.

In your suggested case you can fuzz using just _bak but with `-e` you can use any as you want
```
-e ".bak, _bak, __bak, _bk"
```

In just one run, better than running FFUF 4 times

**Comment by necross2** [comment]
> Yes, so "extension" is probably not the best word here, probably suffix would fit better.
> 
> In your suggested case you can fuzz using just _bak but with `-e` you can use any as you want
> 
> ```
> -e ".bak, _bak, __bak, _bk"
> ```
> 
> In just one run, better than running FFUF 4 times

Fine by me, but at the very least, update the readme or manual so it’s clear one would have to provide dot (.) together with extension.

Following the example on the main page results in the description I initially provided.

**Comment by bsysop** [comment]
You right! It will be done!

**Comment by necross2** [comment]
> You right! It will be done!

👍

**Comment by bsysop** [comment]
https://github.com/ffuf/ffuf/pull/276 

🤟🏻

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
