### ISSUE TITLE
zsh: command not found: ffuf

### ISSUE THREAD

**Issue by Th3R0oT** [ffuf/ffuf#277]
Hi, I'm getting command not found error. I tried every way to configure the path as below:
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export PATH=/usr/local/bin:$PATH
export $PATH=$PATH:/Users/Arpit/Desktop/ffuf
export GOPATH=/Users/Arpit/Desktop/Desktop/DevSecOps/BB/go
export GOPATH=/Users/Arpit/Desktop/ffuf

**Comment by bsysop** [comment]
Hi @Th3R0oT, here you have a mess with Golang, not with Ffuf, if you look your exports, you can see you set FFUF in $GOPATH, which is wrong.

https://github.com/golang/go/wiki/SettingGOPATH

**Comment by Th3R0oT** [comment]
Still not working. I've changed the oath as per your given instruction as below:

export GOPATH=$HOME/go

**Comment by bsysop** [comment]
Hi @Th3R0oT, you having a issue with GO, i recommend you do a clean install of GO and check some manuals how to do it and make your environment ready for any GO tools.

**Comment by joohoi** [comment]
The installation dir for binaries that were built and installed by `go get ...` should be found in `$HOME/go/bin` .
