### ISSUE TITLE
Add full url/path in output

### ISSUE THREAD

**Issue by marcelo321** [ffuf/ffuf#279]
When running ffuf like: ffuf -w wordlist -u host/FUZZ

We get the output like this:

![imagen](https://user-images.githubusercontent.com/29487296/90321860-21f8ed80-df24-11ea-98bd-e72694d72022.png)

It would be really cool if the full url was shown, like:

```
https://google.com/path
https://google.com/path2
```

so people like me that use a special ssh connection like termius can click the link instead of 
copy-pasting the path and adding it to the host we have to put manually to check the endpoint.

Maybe adding a new flag like -fullurl or something? there is the -v flag but that ones gives a lot more informaiton/output that is not really wanted sometimes.

Thanks in advance

**Comment by marcelo321** [comment]
nvm, it is possible to do it adding the -v flag and just palying a bit with grep and sed

**Comment by bsysop** [comment]
=]

Also can save in json and parse that very very easy, ping me if need help!
