### ISSUE TITLE
upgrade => v1.1.0

### ISSUE THREAD

**Issue by skahure003** [ffuf/ffuf#280]
After running go get command to install ffuf, the output is 
> go: github.com/ffuf/ffuf upgrade => v1.1.0

and the package is not installed, how do i rectify that.

**Comment by joohoi** [comment]
Go also stores the source code in a local clone of the git repository. In case `go get ...` finds a local copy, it will build it without checking upstream.

If you are upgrading, you want to add `-u` flag to your `go get` command:
```
go get -u github.com/ffuf/ffuf
```

**Comment by joohoi** [comment]
I feel that this issue was resolved, so I'm closing it. In case you disagree, feel free to comment and we can reopen it.
