### ISSUE TITLE
Custom auto calibration string seems to not be working

### ISSUE THREAD

**Issue by Kiblyn11** [ffuf/ffuf#281]
**Issue**: Using -acc does not change calibration

For example, I use auto calibration, it filters some boring results but there are still some.
So I would like to add boring items from my wordlist (which returns exactly same response) to the auto calibration with -acc but I still see them and the alike responses

I may have misunderstood the purpose of -acc flag.

Example
```
# Auto calibration filter some stuff
ffuf -u "https://google.com" -H "Host: FUZZ" -w ./wordlists/vhosts.txt -ac

# There is still uninteresting stuff, I would like to add some words of the wordlist to the autocalibration
ffuf -u "https://google.com" -H "Host: FUZZ" -w ./wordlists/vhosts.txt -ac -acc firewall -acc en -acc www

# Still same result
```

**Comment by Kiblyn11** [comment]
Hi @bsysop,

Thanks, that's clear explanation, I get it now.
Would be good to have it on README page.

**Comment by bsysop** [comment]
Good idea @Kiblyn11, you right README are a simple list of arguments.

Probably soon we will have a very extensive list.

Good hacking!
