### ISSUE TITLE
-o": unsupported protocol scheme 

### ISSUE THREAD

**Issue by welltest** [ffuf/ffuf#284]
Getting an error:

Error in autocalibration, exiting: Get "example.com/-o": unsupported protocol scheme ""
cat: example.tmp: No such file or directory

Using:
ffuf -mc all -c -H "X-Forwarded-For: 127.0.0.1" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" -u example.com/FUZZ -w /root/wordlist/dicc.txt -D -e js,php,bak,txt,asp,aspx,jsp,html,zip,jar,sql,json,old,gz,shtml,log,swp,yaml,yml,config,save,rsa,ppk -acc -o example.tmp

I tried -ac but no use

**Comment by bsysop** [comment]
Hi @welltest,

You need to set HTTP SCHEMA in `-u example.com/FUZZ`, so something like `-u http://example.com/FUZZ`

Happy hacking
