### ISSUE TITLE
Compared with dirsearch ，There are quite a few false positives

### ISSUE THREAD

**Issue by icezhaoL** [ffuf/ffuf#292]
1、When all the results are 200, it returns all the results back.These result pages and URL pages are the same.
eg: http://www.example.com/                        length:80  word:30                             
      http://www.example.com/FUZZ            all result  length:80  word:30      
      Such false positives should not be returned
2、When -r and -fc exist together。 The fc parameter should filter 301/302, not the redirected page status.
eg: http://www.example.com/FUZZ     all result return 302 status code ,Redirect the 200 false positives page

**Comment by bsysop** [comment]
Hi @icezhaoL, how are you using FFUF? with `-ac` and `-acc`?

**Comment by icezhaoL** [comment]
ffuf -w dicc.txt -u https://api*.com/FUZZ  -o /1.json -c  -r
no use -ac and -acc 
i don't know how to use this options ac and acc?

**Comment by bsysop** [comment]
Ok, i see.

`-ac` is mainly which will fix your problem, it will first run looking the pattern of the server and then ignore it.

If you use `-ac` it will ignore `length:80 word:30`

`ffuf arguments_here -ac`

`-acc` is to ignore all pages similar to one you pass.

`-acc my_custom_page.html`

Then he will take code/length/words and ignore it.

**Comment by icezhaoL** [comment]
Thank you for your patience.

**Comment by bsysop** [comment]
Don't worry, anything you need just open a new issue =]

**Comment by joohoi** [comment]
Thanks for clearing this up @bsysop . I consider the issue solved, and will close it.
