### ISSUE TITLE
Ffuf throws error if comma "," used in a value for -H flag, v1.2.0-git

### ISSUE THREAD

**Issue by MMquant** [ffuf/ffuf#297]
Consider following -H flag and `Fuzz Faster U Fool - v1.2.0-git`
`-H "User-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en) AppleWebKit/522.11.1 (KHTML, like Gecko)"`

If you run ffuf with such setting it immediately throws an error
```
Encountered error(s): 1 errors occured.
	* Header defined by -H needs to have a value. ":" should be used as a separator
```
I was trying to escape the `,` with `\,` but it didn't do the job :)
Simply removing `,` character from the -H value solves the problem and ffuf starts successfully.

**Comment by MMquant** [comment]
I thing this commit `https://github.com/ffuf/ffuf/commit/a71f1c0105e291f117d8a52318f58554f19e9b03` is the issue. It parses commas in all flags, not only in `-w` flag.

**Comment by joohoi** [comment]
Nice catch, thanks for opening the issue. It's now fixed in #298

**Comment by joohoi** [comment]
And special thanks for going through the trouble to pinpointing the issue, you made it really easy to fix this <3

**Comment by MMquant** [comment]
Well I haven't go through any trouble I just noticed
<img width="932" alt="image" src="https://user-images.githubusercontent.com/20891620/93310546-38d17f00-f805-11ea-89a2-3981e26a90de.png">
and checked the commit :)
