### ISSUE TITLE
In what order are the wordlists iterated?

### ISSUE THREAD

**Issue by p4fg** [ffuf/ffuf#300]
In what order is the wordlists permutated?

Say I have one list with hosts and one list with paths.
I want to take the first path, and test it over all hosts first, and then take the next path. 
(To avoid overloading hosts with multiple requests at once and getting blocked).

I guess (hope) that the order of the wordlists will help me out:

ffuf -u https://FUZZHOST/FUZZPATH -w ./hosts.txt:FUZZHOST -w ./paths.txt:FUZZPATH

vs

ffuf -u https://FUZZHOST/FUZZPATH -w ./paths.txt:FUZZPATH -w ./hosts.txt:FUZZHOST

Which one of these will do what I need?

**Comment by p4fg** [comment]
Based on my testing this (with one thread) it seems that ffuf will first iterate over the entire first specified wordlist together with the first line of the second. It seems resonable. Is this by design (so that we can count on it working that way in the future)?

**Comment by joohoi** [comment]
Hi, this is indeed by design, and I strive to keep it this way. Ffuf uses Go's standard library module called `flag` to parse the command line, so I cannot guarantee its design however, but my intention is to keep it this way, and to have a reliable way of handling this.

**Comment by p4fg** [comment]
Awesome!
