### ISSUE TITLE
proposal: consider requiring Go 1.12 at least to simplify internal logic

### ISSUE THREAD

**Issue by jimen0** [ffuf/ffuf#301]
Hi,

I propose to bump the minimum Go required version to, at least, Go 1.12 in order to be able to simplify some parts of the internal logic of `ffuf`.

### Context

`ffuf` [currently requires](https://github.com/ffuf/ffuf/blob/f3bcb50e3ad0960d810bbec0abe159bf0471704b/go.mod#L3) Go 1.11 at least. Go 1.12 was [released](https://blog.golang.org/go1.12) on 25 February 2019. As you can see on its [release notes](https://golang.org/doc/go1.12) two useful new functions were added to the standard libary. These are [`strings.ReplaceAll`](https://pkg.go.dev/strings#ReplaceAll) and [`bytes.ReplaceAll`](https://pkg.go.dev/bytes#ReplaceAll).

As you can see on their [implementation](https://golang.org/src/strings/strings.go?s=24475:24517#L958), this wouldn't have any performance benefit/consequence, it would just be a readability improvement.

### What would it simplify?

After doing a quick grep on ffuf's codebase, here's what could be simplified (commit [`f3bcb50e3ad0960d810bbec0abe159bf0471704b`](https://github.com/ffuf/ffuf/tree/f3bcb50e3ad0960d810bbec0abe159bf0471704b)):

```console
./pkg/runner/simple.go:75:		req.Method = strings.Replace(req.Method, keyword, string(inputitem), -1)
./pkg/runner/simple.go:78:			var CanonicalHeader string = textproto.CanonicalMIMEHeaderKey(strings.Replace(h, keyword, string(inputitem), -1))
./pkg/runner/simple.go:79:			headers[CanonicalHeader] = strings.Replace(v, keyword, string(inputitem), -1)
./pkg/runner/simple.go:82:		req.Url = strings.Replace(req.Url, keyword, string(inputitem), -1)
./pkg/runner/simple.go:83:		req.Data = []byte(strings.Replace(string(req.Data), keyword, string(inputitem), -1))
./pkg/filter/regex.go:44:		pattern = strings.Replace(pattern, keyword, regexp.QuoteMeta(string(inputitem)), -1)
```

### Implementation

I'd be happy to provide a patch doing it for Hacktoberfest if you agree on bumping the minimum Go required version 🎉 

Please, feel free to close this issue if you disagree (:

Best,
Miguel

**Comment by joohoi** [comment]
Thanks for the well written proposal and explanation! I would be happy to bump the version and have you submit the PR when Hacktoberfest hits ;) 

I'll mark this issue with label has-pr, in order to let people know that it's being taken care of.

**Comment by joohoi** [comment]
The required version was bumped to 1.13 already with #302 , so you should be free to implement the fixes.

**Comment by jimen0** [comment]
Thanks for the heads up!
