### ISSUE TITLE
If we could pass input flag of fuzz number ranges instead of wordlist 

### ISSUE THREAD

**Issue by ironfisto** [ffuf/ffuf#306]
Sometimes we need to fuzz number ranges. But some specific digits and with ranges. There are fuzzing lists by sec list  and they all start with zero. It would we good if can specify ranges like 1000 to 2000 direct flag in ffuf

**Comment by joohoi** [comment]
I think this is more related to wordlist generation than ffuf itself. However what I usually tend to do with number ranges is to use `seq` which is part of GNU coreutils (installed on *nix per default) and pipe it to ffuf, like so:

`seq 1000 2000|ffuf -w -:NUMBER -u 'https://example.org/?id=NUMBER' ...`

**Comment by ironfisto** [comment]
@joohoi Awesome .
