### ISSUE TITLE
Add output as text

### ISSUE THREAD

**Issue by clem9669** [ffuf/ffuf#313]
Hey 🙂 

From the help:
`Available formats: json, ejson, html, md, csv, ecsv`

Simply add an option for output format as plain text.
Thanks

**Comment by joohoi** [comment]
What do you think the format should be like? What would be most useful?

**Comment by clem9669** [comment]
In my opinion, it should contain: **_ ffuf headers + full url discovered + code http + size + word + line_**.
Just like when you start it in the terminal.

That is a basic additional feature . Some say that you can use the tee command or whatever but it is better to rely the soft own implementation. It would be very useful for scripting the use of ffuf 😃

**Comment by clem9669** [comment]
Do you agree ? 😃 

What would you put in the text output ?

**Comment by clem9669** [comment]
Hey @joohoi,
Do you think it is possible to implement ? 😃 

Cheers

**Comment by joohoi** [comment]
Isn't that basically what you would get when using `-v`? What would be the use case?

**Comment by clem9669** [comment]
I guess implementing this option is not that useful when you can pipe the result with -v. 
I don't have any cases where you cannot pipe the output of stdout to a file so i will close this issue.

Thanks for your time

PS: If you make a PR about adding txt as output, make a reference to this issue :soil
