### ISSUE TITLE
Problem with using —input-cmd

### ISSUE THREAD

**Issue by Thorsten1** [ffuf/ffuf#318]
When I try to use the example for the --input-cmd parameter with payloads generated by radmasa, I'll always get the error ”* Keyword FUZZ defined, but not found in headers, method, URL or POST data.“
Is there an issue with the example code or am I doing something wrong? 
Thanks in advance. 

Thorsten

**Comment by bsysop** [comment]
Hi @Thorsten1, yes `FUZZ` is not in the example.

Right way:
```
ffuf --input-cmd 'radamsa --seed $FFUF_NUM example1.txt example2.txt' -H "Content-Type: application/json" -X POST -u https://ffuf.io.fi/FUZZ -mc all -fc 400
```

See i put the "FUZZ" at the end

**Comment by joohoi** [comment]
Thanks for @bsysop for fixing this in PR #319 closing the issue as solved.
