### ISSUE TITLE
Someone is using your tool to scan all our webservers, our most common browser is now FFUF

### ISSUE THREAD

**Issue by joakimtauren** [ffuf/ffuf#328]
It would be nice if you could at least have a default user-agent header of IE-6, hacking-robot, or something more creative, I mean..

**Comment by bsysop** [comment]
Hi @joakimtauren 

You mean for Analytics purpose or something?


```
Mozilla/5.0 (Android 4.4; **Fuzzer**; rv:41.0) Gecko/41.0 Firefox/41.0 **FFUF v.xx**
```

Your suggestion is something like this?

**Comment by PatrikFehrenbach** [comment]
I found a workaround for this, the affected file 
	
```
// set default User-Agent header if not present
	if _, ok := req.Headers["User-Agent"]; !ok {
		req.Headers["User-Agent"] = fmt.Sprintf("%s v%s", "Joakim Tauren was here", ffuf.VERSION)
	}
````

I'll submit a PR request soon

**Comment by bsysop** [comment]
😂😂😂 @PatrikFehrenbach been Patrick! 

I look for other departments like Marketing, think they looking at Google Analytics and trying to explain to their boss why they have more "hackers" than customers...

We should try to be transparent for companies, but it's pretty hard.

**Comment by curi0usJack** [comment]
This is now one of my favorite github issues. Poor dude just wants his metrics lololol....

**Comment by joakimtauren** [comment]
I recommend you @curi0usJack to check out who I am and who my colleague is, it might be related to the tool, just saying 👯

**Comment by bsysop** [comment]
Man, we need an feature to easy attach MEMES on GitHub for yesterday!
I would make git funnier!.

**Comment by curi0usJack** [comment]
boooo are you guys coworkers? I was seriously hoping this was legit. thanks anyways for the chuckle. :-)

**Comment by bsysop** [comment]
There was a nice one in nuclei, where someone opened a issue shouting "stop hacking my website" just because the user-agent or something, "Stop hacking my website your f#$!##$ idiots"!

Probably was just a company dangling subdomain pointing to his server IP!
