### ISSUE TITLE
I have this error anytime i try to fuzz from a raw request file

### ISSUE THREAD

**Issue by 0xBones** [ffuf/ffuf#334]
I have this error when i try to fuzz from a raw request file.

Command Used:- 

ffuf -u "ac921f721ee6aa1e80ea0b3c00df003a.web-security-academy.net/product/stock" -request raw.txt -w word.txt -x "127.0.0.1:8080"
__________________________________________________________________________
Contents of raw.txt :- 

POST /product/stock HTTP/1.1
Host: ac921f721ee6aa1e80ea0b3c00df003a.web-security-academy.net
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://ac921f721ee6aa1e80ea0b3c00df003a.web-security-academy.net/product?productId=2
Content-Type: application/x-www-form-urlencoded
Origin: https://ac921f721ee6aa1e80ea0b3c00df003a.web-security-academy.net
Content-Length: 31
Connection: close
Cookie: session=4BHsGl6IgirpGBVw4v7K1aBKi0f3GHpB

stockApi=http://192.168.0.FUZZ:8080/admin
_____________________________________________________________________

Errors :-

Encountered error(s): 2 errors occured.
        * Bad proxy url (-x) format: parse "127.0.0.1:8080": first path segment in URL cannot contain colon
        * Keyword FUZZ defined, but not found in headers, method, URL or POST data.
___________________________________________________________
Latest version of ffuf.

What could i be doing wrong to trigger this issue.

**Comment by joohoi** [comment]
You are not doing anything wrong, this seems to be a regression issue related to the configuration file update. The `POST` data and verb are not getting parsed right now, and it's causing ffuf not to recognize your FUZZ keyword in the POST data.

As a workaround, you can pass `-X POST -d 'stockApi=http://192.168.0.FUZZ:8080/admin'` on the commandline. It will be fixed soon though.

**Comment by 0xBones** [comment]
Thanks @joohoi for your responsive feedback.

Tried using [ -X POST -d 'stockApi=http://192.168.0.FUZZ:8080/admin' ] 

No errors this time but it just runs for one millisecond and then stops.

No output no nothing. 
___________________________________________________________________

Full Command used :- 

ffuf -u 'acf31f331fe3df7680605d2300f00084.web-security-academy.net/product/stock/' -X POST -d 'stockApi=192.168.0.FUZZ:8080/admin' -w word.txt

____________________________________________________________________

Output :- 


        /'___\  /'___\           /'___\       
       /\ \__/ /\ \__/  __  __  /\ \__/       
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\      
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/      
         \ \_\   \ \_\  \ \____/  \ \_\       
          \/_/    \/_/   \/___/    \/_/       

       v1.2.0-git
_____________________________________________________________________

 :: Method           : POST
 :: URL              : acf31f331fe3df7680605d2300f00084.web-security-academy.net/product/stock/
 :: Wordlist         : FUZZ: word.txt
 :: Data             : stockApi=192.168.0.FUZZ:8080/admin
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 40
 :: Matcher          : Response status: 200,204,301,302,307,401,403
___________________________________________________________________

:: Progress: [256/256] :: Job [1/1] :: 0 req/sec :: Duration: [0:00:00] :: Errors: 256 ::

____________________________________________________________________

Thanks for going out of your way to help the ffuf and bug bounty community. @joohoi

**Comment by joohoi** [comment]
You can use `-debug-log filename.log` to see the error messages, but looking at your command line, I think the issue is the URL - it's missing the protocol. When used with `-request`, the value of `Host` - header is used as the host, and HTTPS as default protocol. However you are using `-u` flag on your command line which overrides the host (and the default protocol) from the request file. 

You can either: 
 - Remove `-u ...` from your command line
 - Or add protocol to its value: `-u https://acf31f331fe3df7680605d2300f00084...`

**Comment by 0xBones** [comment]
By adding the protocol https:// resolved this issue.

Thank you so much @joohoi. 
__________________________________________________________________________
Final working command :-

ffuf -u 'https://acc01f5e1e83245480bf23fc00a50042.web-security-academy.net/product/stock/' -X POST -d 'stockApi=192.168.0.FUZZ:8080/admin' -w word.txt
