### ISSUE TITLE
[Feature Request] FFUF should support writing the output to multiple files of different format in one go. 

### ISSUE THREAD

**Issue by meaditisharma** [ffuf/ffuf#337]
As of now FFUF is supporting only one output file, I believe it should support multiple output file of different format. 
for example the following command is trying to write html and json format file, but ffuf isn't supporting the both format. Its only writing the result in html_result.html file of json format. 

ffuf -w domain.txt -of html -of json -u https://singaporeairlines.com/FUZZ -o html_result.html json_result.json

**Comment by joohoi** [comment]
ffuf already supports keyword `all` for `-of` parameter, making it to create the output file in all the available formats. I do see the benefit of defining only two or three different formats from the pool, but as it's already possible to get them with `all` kw, I don't think it's of a super high priority. What do you think?

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
