### ISSUE TITLE
Is this a bug? Actual results different from the one set in filters

### ISSUE THREAD

**Issue by iv1r4x** [ffuf/ffuf#338]
I think the 2 images are pretty self explanatory, but it seems that the actual results I am getting (seen in burp) are different from what I mentioned in the filter (setting and result status both shown in terminal).
![1](https://user-images.githubusercontent.com/48623823/96720610-9b033e00-13c8-11eb-9a6d-cedfc7417fac.png)

![2](https://user-images.githubusercontent.com/48623823/96720623-9fc7f200-13c8-11eb-812f-c0c0a9755afe.png).

**Comment by joohoi** [comment]
Interesting. You could write the request and response of the matched results to disk from ffuf with cli option `-od outputdir` and inspect the results there. 

When using `-replay-proxy` it redoes the request through Burp. In this case, I'm expecting the server to behave differently for these requests, maybe it errenously responds with `200` from time to time under a heavy load (and properly with 503 on the subsequent request).

**Comment by iv1r4x** [comment]
That does sound interesting.. I will check this out and get back thanks 👍

**Comment by iv1r4x** [comment]
Like you said, it does give different results, thanks a lot :)
