### ISSUE TITLE
[Feature request] Raw HTTP request from STDIN

### ISSUE THREAD

**Issue by shelld3v** [ffuf/ffuf#342]
In my dream:

```
$ ffuf --input-request -c -w path/to/wordlist
GET /FUZZ HTTP/1.1
Host: example.com
User-agent:  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1468.0 Safari/537.36
Accept-Language: en-us
Accept-Encoding: identity
Cache-Control: max-age=0


        /'___\  /'___\           /'___\
       /\ \__/ /\ \__/  __  __  /\ \__/
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/
         \ \_\   \ \_\  \ \____/  \ \_\
          \/_/    \/_/   \/___/    \/_/

....
```

**Comment by joohoi** [comment]
I don't personally see many use cases for this. Could you give me an example?

**Comment by shelld3v** [comment]
I mean, I'm too lazy to save the copied content into a file and then run ffuf with that file.

**Comment by clem9669** [comment]
I don't see use cases too. 
I mean you just lose history of what you have done and at what time. Copy paste to a file.
`time xclip -o > myfile` 🤷‍♂️

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I don't currently consider this feature to be implemented.
