### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by theinfosecguy** [ffuf/ffuf#345]
go get -u github.com/ffuf/ffuf
# github.com/ffuf/ffuf/pkg/ffuf
../../work/src/github.com/ffuf/ffuf/pkg/ffuf/optionsparser.go:516:19: undefined: os.UserHomeDir

**Comment by bsysop** [comment]
You should re-install your Golang Env!

**Comment by theinfosecguy** [comment]
I have followed this.
https://www.digitalocean.com/community/tutorials/how-to-install-go-on-ubuntu-18-04

Which one should I use?

**Comment by bsysop** [comment]
Any of your preference at TOP5 in Google.

Your machine variables should have good understanding of where is go installed and work paths.

Try other tutorial.

**Comment by theinfosecguy** [comment]
Great, Thanks

**Comment by bsysop** [comment]
👊🏻
