### ISSUE TITLE
Error in Installation

### ISSUE THREAD

**Issue by theinfosecguy** [ffuf/ffuf#346]
go get -u github.com/ffuf/ffuf
# github.com/ffuf/ffuf/pkg/ffuf
../../work/src/github.com/ffuf/ffuf/pkg/ffuf/optionsparser.go:516:19: undefined: os.UserHomeDir

**Comment by bsysop** [comment]
This is duplicate of #345

**Comment by bsysop** [comment]
Please self-close

**Comment by theinfosecguy** [comment]
Sure
