### ISSUE TITLE
Suggestion to add url-list argument

### ISSUE THREAD

**Issue by Sy3Omda** [ffuf/ffuf#35]
first of all you are doing an amazing tool here, second it would be a huge pros if you add argument for brute forcing a list of urls (domains) along side with `-u` for just single domain .

**Comment by joohoi** [comment]
Thanks for your kind words. This will be quite a task to overtake within the ffuf code itself and is easily achieved by shell scripting around the thing.

However, there's few bits of development details I'd like to share. I'm currently building a daemon & web UI around ffuf. This will allow deployment of ffuf on a server, and adding jobs up to queue while not having to sit around waiting for them to finish. It will also allow batch creation of new jobs (basically the feature you are asking for), as well as other nifty things like copying the existing job as a template, changing it up a bit and adding to the queue.

Other plans for this daemon are DNS and HTTP responders and such. There's a lot of cool stuff coming, when I find the time to actually make them happen :)

Would the described behavior work for you? I'm a bit hesitant to add too much features to the core tool itself, especially if they'll be complicating the code - which is currently quite straightforward.

**Comment by Sy3Omda** [comment]
wooow, if that features so...
you would beat an Ancients tools known in content discovery category. especially your tool is insanely fast.
I would like to make another suggestion for the output of ffuf, is it hard to make the output contains the full URL of along with the FUZZ ing word when I make brute force to certain domain rather than putting the domain as a title and the result in different lines.
that would be great. 
one last thing, for the time being how would you use for loop or while to brute force list of URL with ffuf

**Comment by mexhanic** [comment]
+1 for this feature.
The tool you create is really impressive, but I want it to still be CLI tool, still be "swiss knife".
Can you please add "-l" param to provide a list of URLs to brute-force?

**Comment by Sy3Omda** [comment]
> +1 for this feature.
> The tool you create is really impressive, but I want it to still be CLI tool, still be "swiss knife".
> Can you please add "-l" param to provide a list of URLs to brute-force?

@mexhanic you could use `while` loop till @joohoi add this feature
something like 
`while read -r url ; do ffuf -u https://$url/FUZZ -w list.txt -se -sf -mc all -fc 300,301,302,303,500,400,404 | tee ffuf/$url.txt; done < domains.txt`
and of course u have to make `ffuf` directory first

**Comment by codingo** [comment]
Long term the plans @joohoi proposes are definitely supreme. Shorter term I've been doing this with a project of mine ([Interlace](https://github.com/codingo/Interlace)).

You can essentially do what @Sy3Omda is doing then with:

```
interlace -tL <domain list> -c "ffuf -u _target_ -w list.txt -se -sf -mc all -fc 300,301,302,303,500,400,404 | tee ffuf/$url.txt
```

The benefit of doing it this way is that interlace will manage a thread pool (default 10 threads) for each host, and in my (admittedly very biased) opinion is quicker to do on the fly.

**Comment by Shaddy** [comment]
@codingo approach is great but requires two projects involved, which is similar to what `parallel` does.

What if we support a chain of payloads? I know I'm "stealing wfuzz ideas" but they are great!

Imagine this command:

`ffuf -w domains.txt -w common.txt -u https://FUZZ/FUZZ2N`

Just adding one extra replacement (FUZZ2N) and supporting two input payloads a list of domains can be tested along with the wordlist.

Also, investing time on this will open a good effort to create product and chain iterators, and could be used as a strategy in multiple different scenarios. 

So it is just not "support a list of domains" but investing in an expressive way to build payloads.

What do you think?

**Comment by joohoi** [comment]
It's a great idea! I'm definitely adding it to the TODO list.

**Comment by darkr4y** [comment]
Is it possible to support input the IP range or CIDR ?

**Comment by joohoi** [comment]
Closing this issue as ffuf now supports multiple wordlists / fuzz keywords. This enables you to handle this (in addition to vast array of other things):

`ffuf -w "domains.txt:DOMAIN" -w common.txt -u https://DOMAIN/FUZZ`

> Is it possible to support input the IP range or CIDR ?

This is probably another issue, but I think it's easiest to solve to have a single wordlist for each IP address in the CIDR range. There's plenty of tools to do that for you.

**Comment by Tikam02** [comment]
> Long term the plans @joohoi proposes are definitely supreme. Shorter term I've been doing this with a project of mine ([Interlace](https://github.com/codingo/Interlace)).
> 
> You can essentially do what @Sy3Omda is doing then with:
> 
> ```
> interlace -tL <domain list> -c "ffuf -u _target_ -w list.txt -se -sf -mc all -fc 300,301,302,303,500,400,404 | tee ffuf/$url.txt
> ```
> 
> The benefit of doing it this way is that interlace will manage a thread pool (default 10 threads) for each host, and in my (admittedly very biased) opinion is quicker to do on the fly.

## Not Working

**Comment by Sy3Omda** [comment]
Hi @Tikam02 ,
i think since ffuf release ` #[v0.11](https://github.com/ffuf/ffuf/commit/5456a37f7253145e8d3ada99e64a4df04a9c5ec7)` it's support Multiple wordlist which is no need to make loop using bash or any other tool.
```
ffuf -w domains.txt:DOMAIN -w commom_wordlist.txt -u DOMAIN/FUZZ
```
AND one more advice if i may.
be gentle with web servers when using threading !!!
after all we are meant to protect not flood customer assets with enormous requests.
