### ISSUE TITLE
[Feature Request] options to avoid priniting progress status and errors

### ISSUE THREAD

**Issue by alexerxx** [ffuf/ffuf#351]
Hello, first of all thanks a lot for FFUF, most of the time when running ffuf with ip itself [-u http://10.1.10.1] repeatedly prints the progress status and errors. However this can be avoided with -s silent or -mc or -fc but to get only the url without other useful info, so if there is an additional option to hide the progress status along with errors it would be really much more helpful to have proper formatted data for later use too and also did found this option is available with gobuster as '--no-error and no-progress'.  I've also attached images below
![22 cleaned](https://user-images.githubusercontent.com/74594219/99506330-dff3a380-2979-11eb-9e98-40839ebbde45.png)
![33 cleaned](https://user-images.githubusercontent.com/74594219/99506344-e3872a80-2979-11eb-9269-ea580054d811.png)

**Comment by joohoi** [comment]
This happens because of too narrow terminal window, just make it wider and you will be good to go without -s etc.. There's an open PR to make it more streamlined too, #351

**Comment by RamblerConnect** [comment]
they're right, the progress bar just nukes anything trying to read from stdout. not a big deal in 99% of cases but when its a big deal, its a big deal
