### ISSUE TITLE
Any get around for 429 status code?

### ISSUE THREAD

**Issue by sA74n** [ffuf/ffuf#352]
i was scanning for live hosts in a website, but that responded me with 429 status code after sometime, is there any solution to this like ffuf should stop for some seconds when 429 is encountered and start after sometime

**Comment by bsysop** [comment]
Hi @sA74n,

take a look in theses options:

```
  -sa              Stop on all error cases. Implies -sf and -se. (default: false)
  -se              Stop on spurious errors (default: false)
  -sf              Stop when > 95% of responses return 403 Forbidden (default: false)
```

You can use -sf to make it stop after a big % of fails.

**Comment by sA74n** [comment]
Thanks I'll try these

**Comment by sA74n** [comment]
Is there any way I can add a condition like, if there 10 consequent 429 response then stop and start after certain intervals in ffuf

**Comment by bsysop** [comment]
It's a very good idea, but don't have that option yet.

You can ask for this feature in a new issue, or code it and submit a pull request.

**Comment by joohoi** [comment]
I would like to keep `ffuf` status code agnostic as much as possible, as there always is and will be deviations from the intended use of HTTP status codes
. I also think that it'd be tricky to figure out good defaults for this. Some servers do report the rate limits and "ban" duration information via custom headers, but it is very much case-by-case basis.

For these reasons I suggest just manually tuning your rates according to the target.

**Comment by joohoi** [comment]
I think this issue is resolved, and will close it. Feel free to comment in case this is not the case  and we'll reopen.
