### ISSUE TITLE
Filtering 302 Redirects/Auto Recalibrate

### ISSUE THREAD

**Issue by uBadRequest** [ffuf/ffuf#353]
I've noticed that i'll start getting a lot of 302's that redirect to a 404 page or an error page and i'm using auto calibrate which doesn't help with this case. I don't want to ignore 302's but I was to ignore them when the location that i'm being redirected to are all the same.

If we can add a filter for the location of a 302, say it contains "error" or "/404" then ignore it. Or we could randomly attempt to go to the same path or another random path that auto calibrate did in the beginning and see if the number of words/line have changed, if so, update the filter.

What you think?

**Comment by joohoi** [comment]
You should be able to do this with `-fr` (filter regex)

**Comment by uBadRequest** [comment]
> You should be able to do this with `-fr` (regex based filtering)

Ahh I am using that, didn't thinking about using it for headers! I'll have to try.
