### ISSUE TITLE
Can ffuf filter the [progress] in the terminal window?

### ISSUE THREAD

**Issue by no0bsec** [ffuf/ffuf#354]
Why is the output of my ffuf different from the demo video? During the use of my ffuf, a large number of [progress] will be displayed, and it is not error. This affects my use a lot. Is there any other way besides the parameter -s?
Below is the screenshot：
![image](https://user-images.githubusercontent.com/45028098/100042326-306d7400-2e46-11eb-817f-90225fb404bd.png)

**Comment by bsysop** [comment]
Hi @no0bsec, are you sure your screen is not very small?

If you make that terminal window a bit large, you should not have that problem!

**Comment by joohoi** [comment]
I except this issue to be resolved, and will hence close the issue. Feel free to comment if this is not the case and we'll reopen.
