### ISSUE TITLE
wordlists not readable in ffufrc 

### ISSUE THREAD

**Issue by 0xspade** [ffuf/ffuf#357]
Hi @joohoi,

I set up a large file of wordlists in .ffufrc file but when I'm using the command:
```bash
$ ffuf -u https://example.com/FUZZ
```
it says that I need to provide a wordlist which I already did in .ffufrc file.

**Comment by joohoi** [comment]
Could you please include the content of your `~/.ffufrc` file for debugging purposes? Also just to make sure: the file is in the `$HOME/.ffufrc` right?

**Comment by 0xspade** [comment]
Hi @joohoi,

here is my `.ffufrc`:

```yaml
<snip...>
[input]
        dirsearchcompat = true
        extensions = "conf,config,bak,backup,swp,old"
        ignorewordlistcomments = true
        wordlists = [
                "/path/dicc.v3.txt:FUZZ",
                "/path/assetnote-wordlists/bak.txt:BAK"
       ]
<snip...>
```

**Comment by KwnyPwny** [comment]
I'm having the same issue on v1.3.1.

**Comment by paupaulaz** [comment]
Same here :(
