### ISSUE TITLE
[bug] '-or' flag ignores filters

### ISSUE THREAD

**Issue by uBadRequest** [ffuf/ffuf#358]
Output files are still written if your using filters, like auto calibrate, or status code filters. 

I was having to do this manually so now that there's a flag for it, I decided to try and edit my scripts so it was definitely a good idea.

**Comment by joohoi** [comment]
Could you give the full command line of what you are running and what you except the outcome to be.

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
