### ISSUE TITLE
hide results based on same status, size, words and lines

### ISSUE THREAD

**Issue by juniorhero** [ffuf/ffuf#360]
i have observed when testing different urls, some urls returns the same response for many or most of the  requests like

xxx.com/data
xxx.com/data2
xxx.com/someotherfile 

all has same response like 
[Status: 200, Size: 3406, Words: 953, Lines: 66]
[Status: 200, Size: 3406, Words: 953, Lines: 66]
[Status: 200, Size: 3406, Words: 953, Lines: 66]

how will i filter all such same responses dynamically without manually filtering out such responses.

**Comment by bsysop** [comment]
H @juniorhero ,

You can try `-ac` filter.

With -ac `ffuf` will do it for you

**Comment by joohoi** [comment]
Yup, the autocalibration is what you are looking for. I'm going to close this issue as resolved. In case you feel this is not the case, feel free to reopen.

**Comment by juniorhero** [comment]
I have used -ac already and still getting these results

**Comment by bsysop** [comment]
Ok, then add your manual entries with `-acc`

Something like:
```
ffuf -acc "/data2"
```

**Comment by juniorhero** [comment]
why did -ac fail?

**Comment by bsysop** [comment]
`auto-calibration` works in 99% of cases, but some server or endpoints have own rules, regex, mod_rewrite, etc, which make them response different for specific patterns, you will find a lot of this when you use Ffuf a bit more.

Some patterns could be:
- ^admin(.*)
- ^.(.*)

So, server-side rules is not in Ffuf control.

**Comment by bsysop** [comment]
I mean: Keep using `-ac`, it works, but in some rare cases you need add your own's.
