### ISSUE TITLE
FFUF does not recognize value supplied for -rate flag

### ISSUE THREAD

**Issue by mase289** [ffuf/ffuf#361]
While trying to limit requests made to a host, I supply the -rate flag as in the line below 

ffuf -w raft-large-directories.txt -u https://example.com/FUZZ -mc 200  -fs 42 -c -v -rate 1000. 

This results in an error `flag provided but not defined: -rate`

I am using the latest version of ffuf - v1.1.0

**Comment by joohoi** [comment]
This feature is in the development version of ffuf, so in order to leverage it, you'll currently have to build it from the source of `master` branch. v1.1.0 doesn't have it, but the next release will.

I'll close the issue, feel free to comment and we'll reopen if it's needed.
