### ISSUE TITLE
ffuf not running in windows

### ISSUE THREAD

**Issue by HunterLarcol** [ffuf/ffuf#362]
I have installed ffuf in windows but it runs and exit immediately
how to run ffuf in windows

**Comment by bsysop** [comment]
Hi @AndyBTuttofare,

Looks this is something wrong in your golang environment, stuff not related to FFUF.

In case you see error in FFUF and have something to show/debug, please open a new issue.

**Comment by joohoi** [comment]
One question that popped to my mind; how are you trying to run `ffuf`, can you post the exact command and output so we can debug it further?

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
