### ISSUE TITLE
Match HTTP response size

### ISSUE THREAD

**Issue by aaxxtt** [ffuf/ffuf#363]
is it possible to choose between multiple option [Match HTTP response size]

for example i want the tools to give me result where the size is between 10-20

thx

**Comment by bsysop** [comment]
Hi @aaxxtt,

Yes, you can use multiple combinations

Single: `-ms 200`

Multiple: `-ms 200,201`

Range: `-ms 200-204`

**Comment by aaxxtt** [comment]
thx for replay but i have another question

when i use -mc 200 -ms 500 the tools give me like for example this result

[Status: 200, Size: 123, Words: 6, Lines: 1]
[Status: 200, Size: 1635, Words: 141, Lines: 62]
[Status: 220, Size: 500, Words: 1212, Lines: 1]
[Status: 220, Size: 169, Words: 16, Lines: 12]
[Status: 401, Size: 500, Words: 16, Lines: 12]

but just i want result like this

[Status: 220, Size: 500, Words: 1212, Lines: 1]

so how to fix this ?

**Comment by bsysop** [comment]
You mean, valid targets only if BOTH conditions MATCH, right?

`if (size == 500 && code == 200): true`

FFUF can't do it right now, what you can do is add "filters" or you can parse ffuf output (ffuf json output + jq tool).

To combine filters and matchers you can use for example:
`ffuf -mc 200 -fs 0-499,501-999999`

**Comment by aaxxtt** [comment]
thx u very much
its work now

**Comment by bsysop** [comment]
You are welcome @aaxxtt

If you don't have more questions about this, please close the report.

Thank you.
