### ISSUE TITLE
How to Store the response to a file

### ISSUE THREAD

**Issue by hello13211** [ffuf/ffuf#364]
How to 

Store the response to a file

**Comment by hello13211** [comment]
Store the response to a file

**Comment by bsysop** [comment]
Hi @hello13211,

```
OUTPUT OPTIONS:
  -debug-log       Write all of the internal logging to the specified file.
  -o               Write output to file
  -od              Directory path to store matched results to.
  -of              Output file format. Available formats: json, ejson, html, md, csv, ecsv (or, 'all' for all formats) (default: json)
  -or              Don't create the output file if we don't have results
```

- ffuf your_rules -of json -o file.json
- ffuf your_rules -of html -o file.html
- ffuf your_rules -of all

Also you can save RAW data

- ffuf your_rules -od raw_folder

**Comment by hello13211** [comment]
Hello

Thank you for your response

But I know how to save the results into a file but I want to save the Responses too for example


If I fuuzed this link 

https://example.com/FUZZ

The content of this page will be saved on an html file on my desktop 

Did you got my point?;

Is it possible with FFUF tool to do that ? 

Thank you

**Comment by bsysop** [comment]
Oh, got it, you need the HTML.

What you can do is save all raw response, but it include headers too, which is not so beautiful.

You can try using `-od`, then you can parse it removing the headers. Try renaming a RAW response to .html and open in your browser.. is not perfect, but works.

**Comment by hello13211** [comment]
Oh Thank you for your help 

So my final commands will be 

./ffuf -w test.txt -u https://target.com/FUZZ -c -v -r -od -of html -o test.html 


Right ?

**Comment by bsysop** [comment]
```
./ffuf -w test.txt -u https://target.com/FUZZ -c -v -r -od RAW_OUTPUT_PATH -of html -o test.html
```

All files will be stored at RAW_OUTPUT_PATH folder

**Comment by hello13211** [comment]
Thank you for your response I appreciate your help I hope if I can return
you the favor

**Comment by hello13211** [comment]
Thank you for your response I appreciate your help I hope if I can return you the favor

**Comment by bsysop** [comment]
Don't worry @hello13211 
Just contribute with the community 🤟🏻

Happy hacking.

**Comment by hello13211** [comment]
Thank you ❤️ sure
