### ISSUE TITLE
[FEATURE REQUEST] Output doesn't contain enough info!

### ISSUE THREAD

**Issue by alexerxx** [ffuf/ffuf#365]
Is that possible to save output simply as on terminal results, I use |tee -a for more visual inspection. But the issue is that cat file doesn't contain the URL but just the paths this hard for later use (no ffuf banner like extensions) , -v wasn't convenient either. 
Thank you for giving us FFUF. 

![1](https://user-images.githubusercontent.com/74594219/102708075-25b4cc00-4298-11eb-8620-4bc1abc5a9b0.png)
![2](https://user-images.githubusercontent.com/74594219/102708113-64e31d00-4298-11eb-982b-77d053e271fe.png)

**Comment by bsysop** [comment]
Hi @alexerxx 

Have you tried save it in a file?

https://github.com/ffuf/ffuf/issues/364#issuecomment-752736960

**Comment by bsysop** [comment]
Hi @alexerxx, you can use -v to get the full URL.

Closing this by now, please re-open if you still have questions related to it.
