### ISSUE TITLE
output not saved if wordlist specified with wildcard

### ISSUE THREAD

**Issue by whitehat92** [ffuf/ffuf#369]
ffuf -u example.com -w /usr/share/yourlist/*.txt -o fuzzing_example.com
I ran this command a couple times now and all I have is the requests in the command line but the output file is not generated. If you specify a wordlist without any wildcard, it will generate an output file without a single problem, but if you put a wildcard in a specific folder with a bunch of txt files which you want to fuzz with, it won't.
Is there any way you could fix this?
Thank you

**Comment by joohoi** [comment]
Your shell actually expands the wildcard, so with the above command you are actually running:

```
ffuf -u example.com -w /usr/share/yourlist/first.txt /usr/share/yourlist/second.txt /usr/share/yourlist/third.txt /usr/share/yourlist/nth.txt -o fuzzing_example.com
```

... which is not a syntax supported by ffuf.
