### ISSUE TITLE
Error when execute ffuf

### ISSUE THREAD

**Issue by tXambe** [ffuf/ffuf#370]
Hello,

I installed ffuf in Kali, I follow the steps indicated in Github for installation of ffuf, when execute ffuf:

sudo  ffuf  -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -u https://www.example.com                                       

sudo: ffuf: command not found

I obtain this error.

Can anyone help me ?

A greeting and thanks

**Comment by bsysop** [comment]
Hi @tXambe 

Take a look at here: https://github.com/ffuf/ffuf/issues/220

**Comment by tXambe** [comment]
Hello,

I follow this setps and same error

**Comment by bsysop** [comment]
Hi,

If you run `which ffuf` you will see it dont exists.

You should:
A) Configure your Golang env + Install ffuf
B) Run it directly in path

https://github.com/ffuf/ffuf/issues/220#issuecomment-615256799

Review steps in https://www.digitalocean.com/community/tutorials/how-to-install-go-on-ubuntu-18-04

**Comment by joohoi** [comment]
Closing this issue as it's not ffuf related.
