### ISSUE TITLE
Mention that ffuf can be installed in Linux (and MacOS) using Homebrew package manager

### ISSUE THREAD

**Issue by sidahmed-malaoui** [ffuf/ffuf#374]
Someone already created a Formulae for `ffuf`, which means that `ffuf` can be installed using Homebrew on Linux (and MacOS) : 
```bash
brew install ffuf
```

I think you should mention this in `README.md` file, so Linux (and MacOS) users know they can install `ffuf` using homebrew.

## Bump ffuf version
Homebrew doesn't allow to install from the latest commit directly, it only allows to install from tags (versions). So I guess it would be awesome if you bump `ffuf` version, since the latest available version is `V1.1.0`, which is 6 months old.

PS : Thank you a lot for this wonderful tool :smiley:

**Comment by joohoi** [comment]
Thanks for the input. I'll have to talk with the maintainer of the homebrew formula, but could very well add the information the documentation. Thanks for bringing this up! Also sorry for the late reply, but the version has been bumped meanwhile ;)

**Comment by sidahmed-malaoui** [comment]
Thanks a lot dude, i appreciate it :D
