### ISSUE TITLE
[feature request] many matches in one response

### ISSUE THREAD

**Issue by xinali** [ffuf/ffuf#376]
Hi,

I can use a regex to match one response with ffuf, but I can not find the feature many regexs match one response.
such as
```
-mr "error" -mr "failed" ...
```
If `error` or `failed` in response, it can match the response and output to result.
Can you add the feature to ffuf?

Thanks.

**Comment by sw33tLie** [comment]
There's no need for such thing, keep in mind that mr stands for match regex!
You can do something like -mr "error|failed" :)

**Comment by bsysop** [comment]
Hi buddy

You can use all regex combinations you want

In your case:

-mr “(abc|def)”

Then this will match both strings
-- 



*Guilhermo Gregorio*
Founder, CrowdSec

(+55) 34 99124-1302 <http://null>

www.crowdsec.com.br

**Comment by bsysop** [comment]
> o need for such thin

@sw33tLie I replied by email, I have not saw your reply before buddy!
❤️

**Comment by joohoi** [comment]
I believe this issue was solved, and will close it. Using regexes inherently solves the issue.
