### ISSUE TITLE
How to improve results of ffuf [ -ac flag not working]

### ISSUE THREAD

**Issue by rohitcoder** [ffuf/ffuf#383]
Hi There,

Is there any feature to filter / remove results in case there are a lot of results that have the same [status, size, words, line]

I used this command

```ffuf -w /words.txt -u https://target.com/FUZZ -e .php,.zip,.rar -c -o /target-ffuf.txt -ac -sa -t=2```

and i received this result

![Screenshot 2021-02-02 at 4 50 36 PM](https://user-images.githubusercontent.com/17665703/106618482-81f85480-6595-11eb-968c-efc0796fe4a9.png)

In the above pic, you can see last 4 results, status, size, words everything is the same and in reality these above files doesn't exist, they are just rendering same page (404 page, without throwing 404 status code)

Any idea how to achieve what i am trying? I am planning to do this with comparing results using python, but let me know if there is any good alternaitve.

Thanks for this great project!

**Comment by rohitcoder** [comment]
After watching previous issues https://github.com/ffuf/ffuf/issues/360 & PRs it seems this issue has been already discussed by a lot of other peoples.

I don't know why -ac flag is not working here, i am testing this on my own web application and i not added something which makes this URL special (mod_rewrite or rules) 

I still don't have any idea how to achieve this using -acc flag, i've seen someone discussing use -acc flag can anyone please guide me or post an example here?

**Comment by bsysop** [comment]
Hi @rohitcoder, is clear now?

Thanks

**Comment by rohitcoder** [comment]
Hi @bsysop ,

I am closing this issue, as i found an alternative for this task.

According to #360 sometimes Ffuf not works with ``-ac`` in that case you can use ``-fr`` to filter any unwanted links.

In my case i was getting 200 response for all error pages, and Ffuf wasn't able to remove those links using ``-ac`` flag, so i used this one ``-fr 'not found|404|error'`` this will remove all those links which are redirecting to 404 page.

**Comment by bsysop** [comment]
Ok, if not multiple domain, you can use `-acc` too,

Example:

`-acc 500.html`

It will filter everything that looks with that 500 page you previously had found!

`-acc` is a manual filter for `-ac`
