### ISSUE TITLE
-ac flag not working when Scheme / Protocol is defined in file => FUZZDOMAIN/FUZZWORDS

### ISSUE THREAD

**Issue by rohitcoder** [ffuf/ffuf#384]
Hi,

i used this command and this was working properly.

```ffuf -u FUZZDOMAIN/FUZZDIR -w hosts.txt:FUZZDOMAIN -w words.txt:FUZZDIR -o output.txt```

**_Contents of hosts.txt_**

```
https://example.com
https://example2.com
https://example3.com
```

**Notice:** I used FUZZDOMAIN/FUZZDIR this not starts with http:// or https:// because these schemes are defined under hosts.txt

But, when i added -ac flag this is throwing an error

```ffuf -u FUZZDOMAIN/FUZZDIR -w hosts.txt:FUZZDOMAIN -w words.txt:FUZZDIR -o output.txt -ac```

Error in autocalibration, exiting: Get "admincTwKYaSAiSHTTbYt//admincTwKYaSAiSHTTbYt/": unsupported protocol scheme ""

**Comment by bsysop** [comment]
@rohitcoder please, don't create new issues with exactly same thing, you can comment in the previous one.

I will response here for the two issues, please close your-self after everything is clear for you.

Please change the order of wordlists.

`ffuf -u "URLS/FUZZ" -w words.txt:FUZZ -w hosts.txt:URLS -o output.txt -ac`

Should work for you.

**Comment by rohitcoder** [comment]
@bsysop 

I am trying to send these requests in parallel to multiple domains. 

According to codingo blog, we can use above wordlist order 

```ffuf -u https://FUZZDOMAIN/FUZZDIR -w ./domains.txt:FUZZDOMAIN,./wordlist.txt:FUZZDIR ```

https://codingo.io/tools/ffuf/bounty/2020/09/17/everything-you-need-to-know-about-ffuf.html


![IMG_20210203_205255](https://user-images.githubusercontent.com/17665703/106768423-ec76c680-6661-11eb-9d0b-c1223c2ea22d.jpg)

Is there any compatibility issue in this wordlist order or I am doing something wrong here?

**Comment by bsysop** [comment]
Ohhh, got it now.. sorry.

`-ac` dont works for multiple domains by now, only run it if you want do a single domain (or some special cases not like yours).

**Comment by bsysop** [comment]
Instead you can use a LOOP.

`for URL in $(<hosts.txt); do( ffuf -u "$URL/FUZZ" -w words.txt:FUZZ -ac ); done`

**Comment by rohitcoder** [comment]
Thanks @bsysop 

Seems a compatibility issue, using a loop can do the work. 

This is clear for me now :)

**Comment by bsysop** [comment]
You welcome! 👊🏻
