### ISSUE TITLE
[feature request] Stdin Support for URLs(Target)

### ISSUE THREAD

**Issue by BitThr3at** [ffuf/ffuf#385]
In current version of ffuf we only have stdin support for wordlist, it would be easy to pipeline ffuf if we can have a stdin input for URLs also. Something like below:

`echo "https://target.com/FUZZ" | ffuf -u - -w wordlist.txt`

**Comment by jimen0** [comment]
Hi @BitThr3at,

`ffuf` already supports that mode, you just need to read from `stdin`. Here's an example but you can build a wrapper around it if you want a cleaner method to call it.

```console
$ echo "https://api.github.com/FUZZ" | for item in `cat /dev/stdin` ; do ffuf -k -w wordlist/foo:FUZZ -fc 404 -mc 200 -t 1 -u $item ; done
```

**Comment by joohoi** [comment]
I think this is more of an process issue. The URL part can already be read from the stdin with the default functionality but it applies the restriction that you cannot specify the `FUZZ` target in the input itself.

Like:
`echo 'https://example.org/url/path' | ffuf -w -:HOST -w wordlist.txt -u HOST/FUZZ ...`
