### ISSUE TITLE
CreateFile Not Specified

### ISSUE THREAD

**Issue by Varjack** [ffuf/ffuf#389]
Hello all,

Having an issue with the -w flag. When ever i specify the path to the wordlist i receive an error stating "*CreateFile <file path to word list> the system cannon find the file specified" Please see screenshot for more details.

I am sure i am doing something obvious but i am not sure what the issue is at this point.

Thanks,
![image](https://user-images.githubusercontent.com/68429139/107303117-6cb18780-6ab9-11eb-8c95-a993bd729bda.png)

**Comment by bsysop** [comment]
Hi @Varjack,

I'm not sure how this works on Windows,

Ideas:
- Try with a file in the same path
- Docker? Not a good idea.

**Comment by joohoi** [comment]
Yeah, to add to that; does the file called `wordlist.txt` exist in that path?

**Comment by joohoi** [comment]
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.
