### ISSUE TITLE
[feature request] Add extension to saved output

### ISSUE THREAD

**Issue by ikuamike** [ffuf/ffuf#391]
After running ffuf and saving output as csv
```sh
ffuf -ic -c -u http://192.168.191.130/cgi-bin/FUZZ -w words2.txt -e .cgi -o cgi.out -of csv
```
the output doesn't contain the extension

![image](https://user-images.githubusercontent.com/5783614/107567495-cec3d700-6bf6-11eb-9273-a3d7fa5d0897.png)

ffuf version 1.2.1

**Comment by joohoi** [comment]
Interesting! Nice catch. This is indeed a bug, and the extension should be there. I think it doesn't need to have its own column though, but it should be appended to the payload, as that's the inner working of it anyway.

**Comment by ikuamike** [comment]
Yes that is what I mean, it should be appended. Not as a column. Looking forward to the bugfix.

**Comment by ikuamike** [comment]
Would it be possible to have the appended extension to the terminal output as well? It doesn't appear there too.

**Comment by ikuamike** [comment]
After more testing, this is a false positive. The local app I was bruteforcing was giving weird responses. I ran it a different app and the extension is recorded. Sorry for raising the bug without further tests. Thankyou for your work on ffuf.
