### ISSUE TITLE
Create output dir recursively [essential when outputs parent folder does not exist)

### ISSUE THREAD

**Issue by Damian89** [ffuf/ffuf#395]
Simple fix:

Instead of:
```
err := os.Mkdir(s.config.OutputDirectory, 0750)
```
use: 
```
err := os.MkdirAll(s.config.OutputDirectory, 0750)
```

Fix for:
```
-od /tmp/random/results
```

If "random" does not exist, the files wont get saved. Using MkdirAll will create "results" as well as "random".

Best,

Damian

**Comment by joohoi** [comment]
Thanks for opening the issue. It should be an easy fix.
