### ISSUE TITLE
Retry Connection Reset

### ISSUE THREAD

**Issue by fang0654** [ffuf/ffuf#4]
First off, I love this tool. It is awesome. My only feature request: instead of printing `"Error in runner: Get <url> ...read: connection reset by peer"` and `"Client.Timeout exceeded"` errors, retry the attack and mark an 'error' counter with the status line. This will keep from dropping tests due to an overloaded server, and keep the output somewhat cleaner.

**Comment by joohoi** [comment]
Thanks for your kind words, and for suggesting this feature. It's a really good idea, and I'll implement it soon(ish) when I get the time.

**Comment by SolomonSklash** [comment]
I wanted to second this. I noticed that when it happens, the request per second drops very low, and delays the scan quite a bit. I use ffuf in a chain of tools via [Chomp Scan](https://github.com/SolomonSklash/chomp-scan), and when I hit this error, the entire script essentially hangs waiting for the timeouts and slow request rate.

Is there a way to do something similar to the `-sf` flag (great addition by the way!) and exit the scan if a lot of errors happen?

**Comment by joohoi** [comment]
There are multiple things at play here, and I'm wondering about the approach to take. Currently, I'm thinking of adding a new flag `-se` (stop on errors) and `-sa` (stop on all, which would apply `-se` and `-sf` and probably others to come in the future).

For the retry, I'm wondering about safe defaults. I will be adding a new flag to do what @fang0654 suggested, but I'm wondering if there should be some logic alongside of it - like for example increasing the delay to avoid spurious connection errors, and whether to make these defaults or not.

I'm curious to hear about your opinions on this.

**Comment by SolomonSklash** [comment]
I really like the `-se` and `-sa` flags. For my use case it's perfect.

For the use case where you don't want to stop if errors are encountered due to connection errors, increasing the delay sounds like a good idea. Making the delay optional and configurable could be good too, if it's not too much trouble to implement.

That's my two cents. Thanks for your work on this tool!

**Comment by fang0654** [comment]
I'd say with the retries, only retry once. The main reason is that the error may be intentional on the client side. For example, I've seen a few WAFs that just drop the connection if your request matches some blacklist. I even had one recently that didn't bother to at least send a syn packet, so anything it considered malicious would just timeout. 

It seems like a tough trade-off of simplicity, efficiency and safety, although I guess having various flags for the different behaviours kind of takes care of that.

**Comment by SolomonSklash** [comment]
Thanks for implementing this! Some feedback based on my (limited) initial testing:
Using both `-sa` and `-sf -se` produce the same result: exiting after a certain number of spurious erors. So far so good.
The issue I'm seeing is that it takes about a minute and a half before the exit occurs. Not the end of the world, but when running against a large number of endpoints, it adds up.

**Comment by SolomonSklash** [comment]
To add more detail/context to my previous post:

What I'm seeing when fuzzing a host that errors out is this.
* ffuf drops to about 1-2 requests per second, counting up errors in increments of 20.
* The timer increases until about 60 seconds, give or take a second or two.
* At this point there are about 80-100 errors.
* ffuf hangs for about 20 seconds, then quits, showing 121 errors and about 120 seconds taken.

**Comment by joohoi** [comment]
What's the exact command you are running, and what's the error that the remote host is giving out? In my tests, running against a timeout server:
```
while true                                                        
do
nc -lvnp 4433
done
```
and running ffuf with CLI: `time ./ffuf -sa -w /path/to/wordlist -u http://localhost:4433/FUZZ`

makes ffuf exit in 30 seconds:
```
0,08s user 0,13s system 0% cpu 30,010 total
```

I'm open to suggestions how to detect and handle the errors. What I'm currently thinking is to change the default timeout (currently 10 seconds) and to make it configurable for users using CLI flag.

**Comment by SolomonSklash** [comment]
I'm running it in a loop in [Chomp Scan](https://github.com/SolomonSklash/chomp-scan), like this:
`ffuf -u https://some.domain/FUZZ -w /path/to/wordlist -sf -se -fc 301,302 -k -mc 200,201,202,204,307,308,400,401,403,405,500,501,502,503`
I have been running it against various bug bounty domains. I don't actually receive any error messages during the run. I am attaching a screenshot of what I'm seeing. Ignore the "ffuf took 370 seconds to run" part, that's output from Chomp Scan for the entire ffuf loop.

![Screenshot_20190405_100444-edit](https://user-images.githubusercontent.com/43149956/55637524-cc032a00-57b4-11e9-99ff-ed1eed5decec.png)

**Comment by SolomonSklash** [comment]
As far as a timeout, I think in my use case, the shorter the better. I'm sure others would like it to be longer in the interest of more accurate results. So it seems that a configurable timeout parameter would work well to cover most use cases.

Thanks again for this tool, by far my goto web fuzzing tool.
