### ISSUE TITLE
Add option to print the whole response(with response headers) for matched responses

### ISSUE THREAD

**Issue by choket** [ffuf/ffuf#408]
Maybe I'm blind, but currently I don't see any way to print the whole response for matched responses. Something like `--print-matched-responses`, which would, as the name suggests, print the whole response, including headers, of matches.

**Comment by choket** [comment]
On second thought, maybe printing responses to stdout is not such a great idea as they can't be easily extracted from the rest of the output. Maybe write them to a file called `responses/<matched_word>-response.txt`

**Comment by joohoi** [comment]
> Maybe add another flag called --responses-dir through which the user can supply a directory and then write the matched responses to <responses_dir>/<Fuzz_word>.txt

Hi! This is what the CLI option `-od` does. The request + response get saved as-is to files. The files are named by md5 hashes, and the match entry in both ffuf stdout output as well as the output file refer to this hash.

**Comment by choket** [comment]
Thanks for the quick reply!
