### ISSUE TITLE
[Feature request] Content-type based filtering option

### ISSUE THREAD

**Issue by w9w** [ffuf/ffuf#414]
Hi! Could you please add Content-type based filtering option? I have some checks in mind, but only this option can help me determine what I want to see in the response.

Thank you, and have a beautiful day, Max (@w2w).

**Comment by joohoi** [comment]
Cheers! You should be able to do it with regex filter already!

**Comment by w9w** [comment]
Thanks, Joona! Initially, I thought regex in ffuf is only for the body matching, but it seems like it's for headers, too. Closing then.
