### ISSUE TITLE
Problem with data included in file generated by ffuf in recursive process

### ISSUE THREAD

**Issue by 7h3D0d93r** [ffuf/ffuf#417]
I have noticed that when I use the "_-recursive_" and "_-o file_" options, the only matching patterns included in the file at the end of the ffuf execution are only those of the last executed job. It occurs with all file export formats.
All matching patterns are displayed correctly on screen during the execution of the ffuf process, but do not seem to be included in the final file.

Version: "_1.3.0 Kali Exclusive <3_".
ffuf example command: "_ffuf -u URL/FUZZ -w WORDLIST -mc=all -fc=403,404 -v -c -ac -recursion -recursion-depth 2 -o FILE -of csv_"

Thanks

**Comment by bsysop** [comment]
Hi @7h3D0d93r,

Sorry if I don't get your exactly point here, but you mean:
- You run FFUF more than one time, using the exactly same output config `-o FILE -of csv`
- After you finished the last job (the second for example) the FILE just contains the last work/logs

Its that?

This file is not expected to be a workspace with all logs but a simple log of the last running.

You can save to different files just adding a timestamp for example.
```
ffuf example command: "ffuf -u URL/FUZZ -w WORDLIST -mc=all -fc=403,404 -v -c -ac -recursion -recursion-depth 2 -o FILE_$(date +%s) -of csv"
```

Happy hunting.

**Comment by 7h3D0d93r** [comment]
Apologies for the delay in responding.
I try to explain better the problem that persists on my side.

When I run ffuf with the -recursion -recursion-depth flags, although it locates new directories and adds them as new jobs in the execution and those directories are correctly executed as new jobs, the scan results of the initial process and all the jobs that are not the last to be executed are not stored in the resulting output file that it generates at the end of the program execution.
It only stores the results of the last job, in this case, of the last directory.

I have reproduced this by running ffuf from Kali on several HTB machines and I don't think this is the expected behavior.
I updated Kali a few minutes ago to make sure I have the latest version of ffuf for this platform.



As an example, I run on the HTB Popcorn machine (10.10.10.6) the command:
ffuf -u http://10.10.10.6/FUZZ -c -v -ac -t 250 -recursion -recursion-depth 1 -H "User-Agent: Firefox" -w ~/wordlists/wl-raft-small.txt -ic -mc all -fc=404 -o ffuf.csv -of cs

In the resulting file "ffuf.csv" only the scan results for the directory "http://10.10.10.6/rename/" are shown, when it has also located files for "/" and for the directory "http://10.10.10.6/torrent/".

This is the content of "ffuf.csv":
 FUZZ,url,redirectlocation,position,status_code,content_length,content_words,content_lines,content_type,resultfile.
index.php,http://10.10.10.6/rename/index.php,,1,200,95,4,1,text/html,
.,http://10.10.10.6/rename/.,,371,200,95,4,1,text/html,
index,http://10.10.10.6/rename/index,,11669,200,95,4,1,text/html,
,http://10.10.10.6/rename/,,15679,200,95,4,1,text/html,


Thanks again

Translated with www.DeepL.com/Translator (free version)

**Comment by joohoi** [comment]
Thanks for opening the issue and catching the bug @7h3D0d93r ! It's a really important one, and It's now fixed.

I'll create a point release tomorrow to ship it out.

Much appreciated!
