### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by gprime31** [ffuf/ffuf#419]
Any idea why it does this? 1.3.0-dev

![Screenshot_20210401-234022_JuiceSSH](https://user-images.githubusercontent.com/44535257/113377969-cad54b00-9343-11eb-8ca7-632d4422e3ef.jpg)

**Comment by bsysop** [comment]
Hi @gprime31,

This is a breakline.. FFUF output is a bit more large than your terminal screen size, you need a wider one.

Happy hunting.

**Comment by gprime31** [comment]
Ah, makes sense, thanks.
