### ISSUE TITLE
Unable to FUZZ a list of URLs at the same time

### ISSUE THREAD

**Issue by developerkn** [ffuf/ffuf#420]
Hi,
Your tool is awesome. But it would be better if we could fuzz a list of URLs at the same time.

**Comment by bsysop** [comment]
Hi @developerkn,

While this feature is not in the core of FFUF, you can do a bash loop to fuzz multiple endpoints.

```bash
for URL in $(<urls.txt); do ( fuff args[] ); done
```

I know is not what you asked for, but... 🤷🏻‍♂️

**Comment by developerkn** [comment]
@bsysop
 Thanks for the info.
Can you also tell me how to get the full URL instead of the path in the result?

I will be glad if you write the full command. Example: 
ffuf -c -w -l listofUrl.txt --full-url -mc 200 -o result.txt

**Comment by bsysop** [comment]
To see the full URL you need to use `-v` argument.

The best thing you can do it export output to json and then use `JQ` command to access the full data you need.

If you start using json+jq just ping and I help you with that.

**Comment by developerkn** [comment]
@bsysop 
ok, thanks.
I wanted to know the full command to fuzz a list of URLs.
I'm new in bash. That's why I'm unable to understand your bash command which is:
`for URL in $(<urls.txt); do ( fuff args[] ); done`

What is the full command?

**Comment by bsysop** [comment]
Oh, I got you

```bash
for URL in $(<urls.txt); do ( fuff -u "${URL}/FUZZ" -w wordlist -ac ); done
```

`urls.txt` have all your urls
`wordlist` have all the files list you want to find
`-ac` is the auto-calibrator.

And then you have plenty other options you can choose, I recommend you adapt it at your needs.

**Comment by developerkn** [comment]
@bsysop thank you so much😊

**Comment by joohoi** [comment]
I assume this was resolved by the help of @bsysop <3 

I'll close the issue for now. If you feel that it was left unresolved or you would like to add something, feel free to comment and we'll reopen the issue if necessary.

**Comment by IbrahimGithub** [comment]
**for URL in $(<urls.txt); do ( ffuf -u "${URL}/FUZZ" -w wordlist -ac ); done**
not face the wordlist properly. @bsysop @br0k3n-1337

**Comment by Krmorc** [comment]
what if we want to save it to a file? I'm getting weird results when I try to loop it and save it? how can I do it?

**Comment by EslamSad3** [comment]
cat urls.txt | while read line;do ffuf -c -w wordlist.txt  -mc 200 -u "$line/FUZZ";done

**Comment by fadyosman** [comment]
Actually, you can do that even without any bash commands, you can do

ffuf -w urls.txt:URL -w wordlist:FUZZ -u URL/FUZZ

You can omit the / if your URL list already has a /

**Comment by skalvin** [comment]
is there a way to make ffuf run in pipe mode

if we have a list of urls with parameters (urls)

https://www.website.com/?id=FUZZ
https://www.website.com/?page=FUZZ
https://www.website.com/?view=FUZZ

we can use a cmd to make it run

cat urls.txt | ffuf -c -w payloads.txt -mc -mw "word"

**Comment by bugoverfl0w** [comment]
The same issue here. It is great if can do with multiple URLS
