### ISSUE TITLE
[feature request] - output full url along the result

### ISSUE THREAD

**Issue by dogasantos** [ffuf/ffuf#421]
Hey man,
Just have a simple output idea to make this tool easier to mix with other tools.
It would be possible to add an option to show the full URL on every discovery (file/directory) ?
eg:
ffuf -w a.txt -u http:/b/FUZZ -s 
http:/b/dir1
http:/b/dir2
http:/b/filea
http:/b/fileb

with that, we can use tee to make an easy-to-use plain text list of urls that can be fetched or mixed with other tools.
As this unfortunately don't have a plain text output format, this would be VERY handy.

Thanks!

**Comment by joohoi** [comment]
You actually do have this with verbose output, eg: `ffuf -v -w a.txt -u http:/b/FUZZ`

with simple grep & awk magic you can turn the output into full urls, eg:

```
ffuf -v -w a.txt -u http:/b/FUZZ |grep '| URL |' |awk -F '| URL | ' '{print $3}'
```

**Comment by dogasantos** [comment]
fantastic job @ShyftXero thanks for that!

**Comment by DaddyBigFish** [comment]
figured it out very small command
![image](https://github.com/user-attachments/assets/ae38a898-90a6-4e0c-ad6e-aea13a567e41)

`2>/dev/null | grep -oP '(htt.*)'`

**Comment by bsysop** [comment]
That's awesome @DaddyBigFish 
I'm closing this, please feel free to re-open if needed.
