### ISSUE TITLE
wordlist issue!!

### ISSUE THREAD

**Issue by 0xAkashsec** [ffuf/ffuf#422]
Hi,
When I check the wordlist line it's showing 45683.
![wordlist line](https://user-images.githubusercontent.com/46501627/114042204-0a051e00-98a7-11eb-8eee-b236ffd64d09.png)
But when I go to FUZZIng any target site it's showing (411147). How?
![FUZZING](https://user-images.githubusercontent.com/46501627/114042527-53ee0400-98a7-11eb-94d6-42900e1ce2e5.png)

**Comment by bsysop** [comment]
Hi @0xAkashsec,

Thank you for the pictures.

This wordlist have special characters or breaklines or any special unicode character?

Could you give more details about the wordlist it self?

Thanks

**Comment by joohoi** [comment]
Everything looks as expected. I see you are testing out 9 different versions of each word in the wordlist (see Extensions), and 9 * 45683 equals 411 147

**Comment by 0xAkashsec** [comment]
No, There are only directory words. No break lines.
![Screenshot_13](https://user-images.githubusercontent.com/46501627/114047581-99accb80-98ab-11eb-9427-323cac60a63a.png)

**Comment by 0xAkashsec** [comment]
> Everything looks as expected. I see you are testing out 9 different versions of each word in the wordlist (see Extensions), and 9 * 45683 equals 411 147

Understood. 411147 for 9 extensions. hahahahah. I didn't understand before. Thanks
