### ISSUE TITLE
-request flag adding newline

### ISSUE THREAD

**Issue by grey-fish** [ffuf/ffuf#423]
I am brute forcing password against Nineveh in HTB. Since yesterday, i've been trying to figure out why my password brute force using ffuf is failing. I've come to conclusion that using `-request` flag adds a newline to my request (confirmed via Burp) which is causing my request to fail.

**Fail scenario**

![image](https://user-images.githubusercontent.com/70162785/114044773-b3511180-98b1-11eb-94bd-13017ab9ec44.png)

**Confirmation via Burp**

![image](https://user-images.githubusercontent.com/70162785/114045446-3a05ee80-98b2-11eb-9e1b-6f69adca96c0.png)

**Success Scenario :  using other command line parameters** 

![image](https://user-images.githubusercontent.com/70162785/114045884-936e1d80-98b2-11eb-972a-5b879278d03b.png)

**Confirmation via Burp**

![image](https://user-images.githubusercontent.com/70162785/114046216-dcbe6d00-98b2-11eb-9c0a-341b5471276f.png)

Note: `test_ffuf.txt` does not contain newline

![image](https://user-images.githubusercontent.com/70162785/114047193-b0572080-98b3-11eb-9463-116a4ca94524.png)

**Comment by joohoi** [comment]
While the editor does not show it, the file most likely actually includes the newline. You can verify this with `hexdump -C test_ffuf.txt` 

In vim you actually need an option:
`:set nofixeol` 
to omit automatically adding a newline to the end of the file.

That said, I think this is a bit inconvenient and I think the file parsing in ffuf should probably remove this last newline automatically. I'm going to label this issue as an enhancement because of this.

**Comment by grey-fish** [comment]
Thanks, I am glad this is acknowledged. As per your last comment, i ran `hexdump `on `test_ffuf.txt` and it seems Burp save the file with `\r\n` ending.  (When we _right click_ and select _Copy to file_ option)

![image](https://user-images.githubusercontent.com/70162785/114066521-046b0080-98c6-11eb-991f-d44cb474281a.png)

I tried manually pasting the request (so that line ends with only `\n`) and can confirm that issue is still seen

Lastly, i wasn't able to remove newline from vim using `:set nofixeol`  and then saving the file.  Maybe i have to put it in `.vimrc`.

**Comment by joohoi** [comment]
> Lastly, i wasn't able to remove newline from vim using :set nofixeol and then saving the file. Maybe i have to put it in .vimrc.

I poked around a bit with that and yeah, not very convenient. A way to handle no-newlines-at-the-end-of-the-file with vim is described in the following stackoverflow article: https://stackoverflow.com/questions/1050640/vim-disable-automatic-newline-at-end-of-file/16114535#16114535

I'll make sure it gets normalized by ffuf in the future.
