### ISSUE TITLE
Recursion still not working 1.3.0

### ISSUE THREAD

**Issue by gprime31** [ffuf/ffuf#429]
Recursion still not working 

ffuf -w dict.txt -u https://example.com/FUZZ -recursion -recursion-depth 3 
no jobs added to que after finding /api/ and other dirs

**Comment by gprime31** [comment]
Edit: it seems to be finding random dirs to the que.
ex:
/api <-- not added
/admin <--- not added
/blog <--added
/app <-- added
/user <--- not added
not sure what's going on here, dirsearch picks them all up and adds them all to que.

**Comment by joohoi** [comment]
It's impossible to say what's going on while not being able to reproduce the issue. Can you provide full request & response to an endpoint that should be added as a recursion job?

**Comment by gprime31** [comment]
unfortunately, no ,it's a private program.
download dirsearch run it and fuff on the same target and compair the results.
I would like to use fuff, it's really good.

**Comment by joohoi** [comment]
Can you anonymize the request & response then. I cannot help you if I don't know the response headers, more specifically the response code as well as potential `Location` header. Feel free to change the host name to an anonymous one (example.com for example).

**Comment by gprime31** [comment]
![2021-04-20_07-10](https://user-images.githubusercontent.com/44535257/115390656-7f78c480-a1ac-11eb-9d2f-da1c9da2b3b3.png)
fuff, first dir found for recursion 10k words in...

**Comment by gprime31** [comment]
![2021-04-20_07-44](https://user-images.githubusercontent.com/44535257/115390729-93242b00-a1ac-11eb-974e-71d11ea4c02a.png)
dirsearch first recursion 20 words in...

**Comment by joohoi** [comment]
I would need the information I requested above to analyze it any further. However, in the screenshot from ffuf you provided, it just shows ffuf _starting_ the new recursion job, not finding & adding it to the queue.

**Comment by joohoi** [comment]
With the default settings, ffuf will only add a recursion job, if a request to `target.tld/resource` has a HTTP status code of 30X and has a `Location` header pointing to `target.tld/resource/`

**Comment by HolyBugx** [comment]
Hey joohoi, 

Hope you are doing alright, if the recursion only works for paths with the HTTP status code of 30X then possibly lots of stuff on other endpoints with 20X status code would be missed, for instance, imagine you used `ffuf -w example.txt -t https://target.tld/FUZZ` and found: `/api`, now ffuf should automatically add `/api/FUZZ` to the queue, and use the same wordlist on that path too, in this case, it would be great.
Hopefully, it's clarified now :) 

Regards
HolyBugx

**Comment by joohoi** [comment]
> Hope you are doing alright, if the recursion only works for paths with the HTTP status code of 30X then possibly lots of stuff on other endpoints with 20X status code would be missed, for instance, imagine you used ffuf -w example.txt -t https://target.tld/FUZZ and found: /api, now ffuf should automatically add /api/FUZZ to the queue, and use the same wordlist on that path too, in this case, it would be great.

This is already implemented. In the v1.3.0 there's a new cli flag: `--recursion-strategy greedy` which does exactly that - it adds all the matches as recursion jobs, especially meant for API endpoint discovery. 

I did not recommend using that previously in this thread as the OP is clearly doing generic content discovery, and this would have just added hundreds of recursion jobs.

**Comment by HolyBugx** [comment]
> > Hope you are doing alright, if the recursion only works for paths with the HTTP status code of 30X then possibly lots of stuff on other endpoints with 20X status code would be missed, for instance, imagine you used ffuf -w example.txt -t https://target.tld/FUZZ and found: /api, now ffuf should automatically add /api/FUZZ to the queue, and use the same wordlist on that path too, in this case, it would be great.
> 
> This is already implemented. In the v1.3.0 there's a new cli flag: `--recursion-strategy greedy` which does exactly that - it adds all the matches as recursion jobs, especially meant for API endpoint discovery.
> 
> I did not recommend using that previously in this thread as the OP is clearly doing generic content discovery, and this would have just added hundreds of recursion jobs.

This is great, thanks! gonna try it out soon :)

**Comment by gprime31** [comment]
> > Hope you are doing alright, if the recursion only works for paths with the HTTP status code of 30X then possibly lots of stuff on other endpoints with 20X status code would be missed, for instance, imagine you used ffuf -w example.txt -t https://target.tld/FUZZ and found: /api, now ffuf should automatically add /api/FUZZ to the queue, and use the same wordlist on that path too, in this case, it would be great.
> 
> This is already implemented. In the v1.3.0 there's a new cli flag: `--recursion-strategy greedy` which does exactly that - it adds all the matches as recursion jobs, especially meant for API endpoint discovery.
> 
> I did not recommend using that previously in this thread as the OP is clearly doing generic content discovery, and this would have just added hundreds of recursion jobs.

This is is what i was looking for, Thanks.

**Comment by okondo-afo** [comment]
Hi , recursion does not work on my end regardless of what flag i use, even tho i set recurson to greedy still no jobs are added to que nothing, i am having to do this manually wish is stressful



 ffuf -w raft-large-files.txt -u https://instablog9ja.com/FUZZ -t 2 -r --recursion-strategy greedy

        /'___\  /'___\           /'___\       
       /\ \__/ /\ \__/  __  __  /\ \__/       
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\      
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/      
         \ \_\   \ \_\  \ \____/  \ \_\       
          \/_/    \/_/   \/___/    \/_/       

       v1.3.1 Kali Exclusive <3
________________________________________________

 :: Method           : GET
 :: URL              : https://website/FUZZ
 :: Wordlist         : FUZZ: raft-large-files.txt
 :: Follow redirects : true
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 2
 :: Matcher          : Response status: 200,204,301,302,307,401,403,405
________________________________________________

index.php               [Status: 200, Size: 156612, Words: 8259, Lines: 1598]
xmlrpc.php              [Status: 405, Size: 42, Words: 6, Lines: 1]
wp-login.php            [Status: 200, Size: 9382, Words: 460, Lines: 157]
wp-register.php         [Status: 200, Size: 9602, Words: 470, Lines: 159]
favicon.ico             [Status: 200, Size: 1671, Words: 12, Lines: 9]
readme.html             [Status: 200, Size: 7346, Words: 740, Lines: 98]
.htaccess               [Status: 403, Size: 1271, Words: 437, Lines: 41]
license.txt             [Status: 200, Size: 19915, Words: 3331, Lines: 385]
:: Progress: [214/37050] :: Job [1/1] :: 0 req/sec :: Duration: [0:04:05] :: Errors: 0 ::
[INFO] ------ PAUSING ------
