### ISSUE TITLE
Suggestion to output full urls, not only words found

### ISSUE THREAD

**Issue by mexhanic** [ffuf/ffuf#43]
It will be very useful to have the ability to output not only words found, like
`api
about
static`
but full urls like
`https://github.com/ffuf/
https://github.com/api/
https://github.com/about/
`
Because in saved csv-reports there is no scan query or so present, so it will be awesome to see full urls in every of hundreds of report-files saved, to see from what target it comes from.

**Comment by joohoi** [comment]
This has been in the works, and there was an PR that was closed by the author that did exactly this. I'm thinking of including that as an (yet another) command line flag. 

It's not a feasible default, as there's many other use cases besides URL fuzzing with ffuf.

**Comment by ngkogkos** [comment]
That would be an awesome addition!

**Comment by hazanasec** [comment]
+1

**Comment by joohoi** [comment]
This has been added in #100 , works with `-v` flag.

**Comment by rotemreiss** [comment]
@joohoi As far as I can tell, there is no way to output full URLs with the silent (`-s`) flag, right? This could be very handy. WDYT?

**Comment by bsysop** [comment]
> @joohoi As far as I can tell, there is no way to output full URLs with the silent (`-s`) flag, right? This could be very handy. WDYT?

Hi @rotemreiss, If you choose SILENT option, it means you need save output in files and check with your own tools.

If you need know more about it, just let me know.
