### ISSUE TITLE
Recursion not working

### ISSUE THREAD

**Issue by Phoenix1112** [ffuf/ffuf#430]
hello. thanks for great project. i did install ffuf last version.. but i cant use this tool with recursive mode.

command:

```
ffuf -u https://example.com/FUZZ -w wordlist.txt -r -recursion -recursion-depth 10
```

With the above command, it finds all directories but does not start a new scan on the directories it finds. that is, the program terminates without the recursive mode running.

![image](https://user-images.githubusercontent.com/42475284/115561212-049fce80-a2be-11eb-8fcb-90c7914fcaab.png)

![image](https://user-images.githubusercontent.com/42475284/115561277-171a0800-a2be-11eb-9724-1b9fcfddef7a.png)

what's wrong?

**Comment by gprime31** [comment]
I had the same problem, use --recursion-strategy greedy and close

**Comment by joohoi** [comment]
I assume this issue was solved by the above comment from @gprime31 . Closing it now. If you feel something is unresolved, feel free to comment and we'll reopen the issue.
