### ISSUE TITLE
HTTP/2 Implementation

### ISSUE THREAD

**Issue by c0g4ih4l4n** [ffuf/ffuf#432]
I'm currently using this tool vs HTTP/2 website but it's not working, is this have any option to working with HTTP/2 protocol ?

**Comment by joohoi** [comment]
ffuf should use http/2 with default settings wherever possible. How does the issue manifest itself?

**Comment by longtranf** [comment]
![image](https://user-images.githubusercontent.com/20518149/116197367-e3782b80-a75e-11eb-84a9-d706f040e876.png)
It's has a lot of error here

**Comment by joohoi** [comment]
The errors are typically from the transport. To get an idea of the errors, you can use `-debug-log errors.log`

**Comment by longtranf** [comment]
Here the error, sorry for late response 
![ffuf](https://user-images.githubusercontent.com/20518149/116857122-7d8c1800-ac26-11eb-9dfd-1fd45c0873cb.png)

**Comment by joohoi** [comment]
Yup, you are right (even though the error messages are somewhat ambiguous for this issue). ffuf is missing http/2 support. I'll add it in the near future!

**Comment by mxrch** [comment]
Hello @joohoi, thanks for this awesome tool.
Any news regarding the HTTP/2 support ?

**Comment by bsysop** [comment]
Hi @c0g4ih4l4n and @mxrch,
Ffuf is supporting HTTP2 with the argument `-http2`

I will consider the problem was fixed.
Feel free to re-open if you still have issues.

Happy hacking.
