### ISSUE TITLE
Read from piped stdin

### ISSUE THREAD

**Issue by noraj** [ffuf/ffuf#442]
Is that possible to read the wordlist from stdin, eg. [piping cook into gobuster](https://github.com/giteshnxtlvl/cook#direct-fuzzing-with-gobuster)?

I'm not sure of how `--input-cmd` works and if it does that.

It would be cool to be able to set a dash as argument of wordlist `-w -` or just a dash `-` as alternative to `-w`.

**Comment by joohoi** [comment]
This is already implemented.

-w - works :)

**Comment by noraj** [comment]
My bad, I hadn't a shell to test this at that time 😆
