### ISSUE TITLE
Limit results with with http response size range

### ISSUE THREAD

**Issue by securitum** [ffuf/ffuf#45]
Is there a simple way to filter out responses with N <= size <= M ?

**Comment by joohoi** [comment]
There currently isn't. However it could be handled in a similar way than the delay ranges defined with `-d` are used. I'll label this issue as feature request.

**Comment by joohoi** [comment]
With the #47 merged, you should now be able to say `-fs 1024-1337` to filter out everything between 1024 and 1337 bytes @securitum !
