### ISSUE TITLE
how can I filter response size in reverse mode

### ISSUE THREAD

**Issue by Rahimianes** [ffuf/ffuf#453]
Hello
How can I filter only that requests not equal to some size?
for example, I only want to filter that requests not equal with size 3690 
size=!3690 
thanks

**Comment by bsysop** [comment]
Hi @Rahimianes 

For it you can combine multiple filters/matches:

`-ms` supports ranges, for example: `-ms 0-3689,3691-999999999`

Happy hacking.

**Comment by bsysop** [comment]
Hi @Rahimianes, I'm closing this by now, feel free to re-open if you problem was not fixed.

Happy hacking.
