### ISSUE TITLE
TOR Usage

### ISSUE THREAD

**Issue by r3dpars3c** [ffuf/ffuf#455]
Hi
Is there any way to use tor in ffuf ?

**Comment by bsysop** [comment]
Hi @Aaryan9898 

FFUF supports socks4/5.

```
-x socks5://127.0.0.1:8080
```

It could help you.

**Comment by bsysop** [comment]
hi @r3dpars3c,
I will consider your problem was fixed.

Feel free to re-open if you still have issues.

Happy hacking.
