### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by savushkin-yauheni** [ffuf/ffuf#456]
Hi team.

Today i found a bug in my code. after long review i found a strange ffuf output.

```
{
  "input": {
    "FUZZDIR": "active.log",
    "FUZZDOMAIN": "https://workspace.finance.seagroup.com"
  },
  "position": 1004901,
  "status": 200,
  "length": 142022,
  "words": 8930,
  "lines": 123,
  "content-type": "text/html; charset=utf-8",
  "redirectlocation": "",
  "duration": 128699261,
  "resultfile": "6d1d0aa1dc7c8cf527a72cb51d1c9ff5",
  "url": "https://2021.tinkoff.ru/actions/seomatic/meta",
  "host": "2021.tinkoff.ru"
}
```

Check FUZZDOMAIN and url. How is it possible at all ? Maybe it's a concurrency bug ?

Thanks.

**Comment by bsysop** [comment]
Hi @savushkin-yauheni, 
Have you additional information to add? What was the ffuf arguments you used?

A lot of time passed, I'm closing this by now, but feel free to re-open if you still consider the issue valid.

**Comment by savushkin-yauheni** [comment]
Hi @bsysop 
I am not sure that any arguments should lead to such result.  But anyway it was the simpliest config, nothing special at all. It's definitely  looks like concurrency\multiprocessing bug. But of course I can't provide you more info about it =(

unfortunately it was a main reason why I left ffuf, it was reproduced multiple times and fuzzings results looked strange because of that.
Regards!
