### ISSUE TITLE
FFUF freezes after fuzzing for 1ooK urls

### ISSUE THREAD

**Issue by r3dpars3c** [ffuf/ffuf#464]
I checked my network to see if there is any problem there but it was fine.
The ffuf will not work after fuzzing more than 100k  urls.
Please fix this soon.

**Comment by jimen0** [comment]
This seems to be working as intended. Created the following server:

```go
package main

import (
	"log"
	"net/http"
)

func home() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}
}

func main() {
	http.HandleFunc("/", home())
	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

Created a 105.000 lines long wordlist:

```console
$ seq 1 100005 > /tmp/large.txt
```

Ran ffuf:

```console
$ ./ffuf -w /tmp/large.txt -k -mc 200 -u http://127.0.0.1:8080/FUZZ
...
:: Progress: [100005/100005] :: Job [1/1] :: 3448 req/sec :: Duration: [0:00:29] :: Errors: 0 ::
```

For your interest @joohoi

**Comment by bsysop** [comment]
Awesome work @jimen0,
I'm closing this by now @r3dpars3c, please re-open if you still have issues.

If you found the reason it was happening, feel free to share.

Happy hacking.
