### ISSUE TITLE
Continue to fuzz ignoring the errors. any switch.......????????

### ISSUE THREAD

**Issue by r3dpars3c** [ffuf/ffuf#472]

**Comment by bsysop** [comment]
Hi @Aaryan9898 , what args are you using?

**Comment by Aaryan9898** [comment]
Here is the flag am using.
ffuf -w 1.txt -u FUZZ -mr '200' -r -t 15 -fc 404,342 -rate 50

**Comment by bsysop** [comment]
Got it,

1.txt have full urls?

```
https://domainA/path
https://domainB/path
```

right?

you can use `-debug-log file` to see what is happening, check what errors FFUF is puking out.

**Comment by Aaryan9898** [comment]
Yeah you are right.

**Comment by ndeepak** [comment]
You can use -fs {most occurring size value of the header}

**Comment by bsysop** [comment]
@Aaryan9898 try using any of these two args, which one fits better for your current fuzz.

```
  -sa                 Stop on all error cases. Implies -sf and -se. (default: false)
  -se                 Stop on spurious errors (default: false)
```

**Comment by ksecurity45** [comment]
This switch does not work. 
-sa                 Stop on all error cases. Implies -sf and -se. (default: false)
  -se                 Stop on spurious errors (default: false)

**Comment by bsysop** [comment]
Hi @ksecurity45, to say it doesn't work, please prove it with some context, ffuf versioon, debug logs, screenshots, and a target to test.
