### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mr-n30** [ffuf/ffuf#473]
Sorry if I'm posting this in the wrong section.

Adding a flag that greps the response for the FUZZ payload. This is similar to Burp's "Search responses for payload strings". Another feature is adding a flag that allows ffuf to read URL's from a file or stdin. Each URL must contain the FUZZ keyword of course else ffuf either skips the URL or exits (But that's just annoying.)

**Comment by bsysop** [comment]
Hi buddy,

`-mr` does that.

`-mr "REGEX"`

read from the stdin, you can do it too

`cat file | ffuf -w -:FUZZ`

Regards.

**Comment by mr-n30** [comment]
Thank you! :)

**Comment by bsysop** [comment]
You welcome --



*Guilhermo Gregorio*
Founder, CrowdSec

(+55) 34 99124-1302 <http://null>

www.crowdsec.com.br
