### ISSUE TITLE
Add support for client SSL certificates

### ISSUE THREAD

**Issue by choket** [ffuf/ffuf#477]
Some websites require clients to authenticate themselves using SSL certificates.
Please add a command line param which takes a user's ssl certificate and uses it when connecting to the target for fuzzing. Without the client cert, such websites only give you an error page regardless of the path you requested, making fuzzing impossible

**Comment by jimen0** [comment]
Doable by adding a couple of flags and updating `TLSClientConfig` attribute of the HTTP Transport in use.

**Comment by rsauron** [comment]
This is feature is needed.

**Comment by Serizao** [comment]
I have make PR to do that #713

**Comment by joohoi** [comment]
PR for this functionality has been merged, thanks @Serizao
