### ISSUE TITLE
filter and match options

### ISSUE THREAD

**Issue by drforbin** [ffuf/ffuf#478]
Fuff does not seem to report the proper size word count and lines as compared to real burp or http responce!
Is it cooking the responces data somehow?

**Comment by bugbaba** [comment]
The difference maybe due to how its being calculated in ffuf vs burp
https://github.com/ffuf/ffuf/blob/master/pkg/runner/simple.go#L169

**Comment by bsysop** [comment]
Exactly @bugbaba 
@drforbin Some fuzzers will pick content-length and others will calculate in the fly

You have different servers implementations, with load balancers, with CDNs, etc
Because of that, sometimes Content-Length is not real.

**Comment by bsysop** [comment]
I will consider your problem as fixed.
Feel free to re-open if you still have issues.

Happy hacking.
