### ISSUE TITLE
[Request] Extensions without %EXT%

### ISSUE THREAD

**Issue by SecT0uch** [ffuf/ffuf#49]
Thanks for your work, FFuF is now my favorite tool for Web discovery/fuzzing.

Would it be possible to allow `-e` without `-D` and `%EXT%` in the wordlist ?

I have the wordlist [Web-Content/common.txt](https://github.com/danielmiessler/SecLists/blob/master/Discovery/Web-Content/common.txt) who doesn't contains extensions or `%EXT%`. 
For exemple `fuuf -w common.txt -e .php,.html -u https://target/FUZZ` would test `login.php` and `login.html`.
And maybe implement `-E` who would try with and without the extension, so `login.php`, `login.html` AND `login`.

**Comment by Shaddy** [comment]
Hi!

It seems that running as you pointed out does what you expect.

```
echo test | ffuf -e '.php','.html' -u https://www.example.com/FUZZ -mc all -w -

        /'___\  /'___\           /'___\
       /\ \__/ /\ \__/  __  __  /\ \__/
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/
         \ \_\   \ \_\  \ \____/  \ \_\
          \/_/    \/_/   \/___/    \/_/

       v0.11git
________________________________________________

 :: Method       : GET
 :: URL          : https://www.example.com/FUZZ
 :: Matcher      : Response status: all
________________________________________________

test.html               [Status: 404, Size: 1270, Words: 338]
test.php                [Status: 404, Size: 1270, Words: 338]
test                    [Status: 404, Size: 1270, Words: 338]
:: Progress: [3/3] :: 0 req/sec :: Duration: [0:00:00] :: Errors: 0 ::
```

In case it wouldn't, you could have done using `-e '.php','.html',''` which will do another extra `test` request.

If what you want it so also test it as dir, use `-e '.php','.html','/'`

```
test                    [Status: 404, Size: 1270, Words: 338]
test.html               [Status: 404, Size: 1270, Words: 338]
test/                   [Status: 404, Size: 1270, Words: 338]
test.php                [Status: 404, Size: 1270, Words: 338]
```

Hope it helps!

**Comment by SecT0uch** [comment]
I didn't manage to make it work. I'll try again later.

Thanks,
