### ISSUE TITLE
fr with post request

### ISSUE THREAD

**Issue by oxygenne** [ffuf/ffuf#491]
I try to filter results with certain words in them but without success:
ffuf -w users.txt -u "https://url/login.php" -X POST -d 'username=FUZZ' -fr "1 times"

Basically i dont wont to show the results with word "1 times" in them

**Comment by joohoi** [comment]
You seem to be POSTing form data without proper Content-Type header.

**Comment by joohoi** [comment]
Closing this issue as I assume it is happening because of improper headers, and hasn't seen any traffic in quite a long time.
