### ISSUE TITLE
how to get web's title

### ISSUE THREAD

**Issue by chibd2000** [ffuf/ffuf#492]
whether or not add HTML title display option at next version? Thanks ;)

**Comment by bsysop** [comment]
There is not a way right now using FFUF @chibd2000,

You can save the requests in raw files, and then use any other way to extract it.

**Example:**
```bash
ffuf -u FUZZ -w urls -od raw_folder
grep -rEo "(http|https)://[a-zA-Z0-9./?=_%:-]*" ./raw_folder/ | sort -u
```

Happy hacking.

**Comment by chibd2000** [comment]
thanks

**Comment by bsysop** [comment]
You welcome @chibd2000, please close the issue.
Thanks.
