### ISSUE TITLE
Suspected high concurrency caused the operation to be cancelled

### ISSUE THREAD

**Issue by ab-Alex** [ffuf/ffuf#493]
The operation was canceled.
![image](https://user-images.githubusercontent.com/43507436/138552421-48d56645-846c-4238-8dc6-8c92699e8675.png)
Suspected high concurrency caused the operation to be cancelled

**Comment by joohoi** [comment]
The error message is not from `ffuf` but from OS maybe? Closing this issue as it seems stale.
