### ISSUE TITLE
shell 

### ISSUE THREAD

**Issue by Who-AmI** [ffuf/ffuf#498]
nohup fuzz_file.sh & will be stopped, how can i do?

**Comment by bsysop** [comment]
Hi @Who-AmI 
What the content of `fuzz_file.sh`?

**Comment by Who-AmI** [comment]
I have  soved it . Thanks very mucl.

**Comment by bsysop** [comment]
No problem, please close the issue.
Good luck.

**Comment by Who-AmI** [comment]
Thanks a lot.
