### ISSUE TITLE
Make -fr and -mr (regex filtering) match header content as well

### ISSUE THREAD

**Issue by joohoi** [ffuf/ffuf#5]
The regex filtering currently matches only against the response body, make it match response headers as well.

**Comment by codingo** [comment]
I would also love to see this happen. I haven't looked too deeply into this project as yet (beyond using it), but feel free  to assign this to me if you'd like me to pick it up.

**Comment by joohoi** [comment]
Oh, that would be great!

Few pointers to make it easy for you:
The change is needed at https://github.com/ffuf/ffuf/blob/master/pkg/filter/regex.go#L23-L25
And I'd imagine the best way to do this would be to flatten the Headers map, append the body data to it, after which to perform the regex matching.

The response struct for reference: https://github.com/ffuf/ffuf/blob/master/pkg/ffuf/response.go#L8-L16

**Comment by joohoi** [comment]
I had a bit of spare time in my hands so I made a PR for this. Going to roll a new release next.
