### ISSUE TITLE
ffuf get stuck with domains list having both http and https.

### ISSUE THREAD

**Issue by salooali** [ffuf/ffuf#501]
Hey i'm trying to fuzz on web directoires, I've a list of my subdomains the file containt boht http and https domains. 
when i try to this:
ffuf -w wordlist.txt -u https://www.example.com/FUZZ  
as it is running on http not on https. It will not give me any result. Yeah i can do this.
ffuf -w wordlist.txt -u http://www.example.com/FUZZ
now it will give results. but as i've boht http and https domains in a list it should be dynamic and gives me result on boht (http and https)
is there any way to solve this? 
Thanks

**Comment by bbtony** [comment]
I agree with you! This is good feature and I think I will be useful for other users.

**Comment by 9oelM** [comment]
https://github.com/ffuf/ffuf/issues/84

**Comment by 9oelM** [comment]
For me personally, what I decided to do is to run `httpx` on the targets first, and the output from`httpx` will automatically prefix appropriate, supported protocol by the domain. And I use that as an input to ffuf.

**Comment by joohoi** [comment]
Closing this issue as @9oelM provided a workaround, and the ffuf-specific answer was given in the linked issue already.

**Comment by ocervell** [comment]
@joohoi in my case `httpx` gives me an `https://` URL and seems to be able to access it, while for ffuf `https://` doesn't work and I need to input `http://` for it to work. The error from `ffuf` is "http server gave HTTP response to HTTPS client" but it doesn't seem to bother `httpx`. ...

**Comment by esp0xdeadbeef** [comment]
This seems to be working:
```
$ cat /tmp/protocols
http
https
$ echo -e '/\nindex.html\netc.' | ffuf -w /tmp/protocols:PROTOCOLS -u 'PROTOCOLS://example.com/FUZZ' -w -
<snipped>
[Status: 200, Size: 1256, Words: 298, Lines: 47, Duration: 86ms]
    * FUZZ: index.html
    * PROTOCOLS: http

[Status: 200, Size: 1256, Words: 298, Lines: 47, Duration: 90ms]
    * FUZZ: /
    * PROTOCOLS: http

[Status: 500, Size: 433, Words: 29, Lines: 13, Duration: 223ms]
    * FUZZ: etc.
    * PROTOCOLS: http

[Status: 200, Size: 1256, Words: 298, Lines: 47, Duration: 84ms]
    * FUZZ: /
    * PROTOCOLS: https

[Status: 200, Size: 1256, Words: 298, Lines: 47, Duration: 88ms]
    * FUZZ: index.html
    * PROTOCOLS: https

:: Progress: [6/6] :: Job [1/1] :: 1 req/sec :: Duration: [0:00:05] :: Errors: 0 ::
```
