### ISSUE TITLE
Suggestions of Code : 

### ISSUE THREAD

**Issue by ArkAngeL43** [ffuf/ffuf#503]
I have not been in go to long however i have been programming for a while now, and im sure you can optimize ALOT of this code like here

```go
	fmt.Printf("EXAMPLE USAGE:\n")
	fmt.Printf("  Fuzz file paths from wordlist.txt, match all responses but filter out those with content-size 42.\n")
	fmt.Printf("  Colored, verbose output.\n")
	fmt.Printf("    ffuf -w wordlist.txt -u https://example.org/FUZZ -mc all -fs 42 -c -v\n\n")
	fmt.Printf("  Fuzz Host-header, match HTTP 200 responses.\n")
	fmt.Printf("    ffuf -w hosts.txt -u https://example.org/ -H \"Host: FUZZ\" -mc 200\n\n")
	fmt.Printf("  Fuzz POST JSON data. Match all responses not containing text \"error\".\n")
	fmt.Printf("    ffuf -w entries.txt -u https://example.org/ -X POST -H \"Content-Type: application/json\" \\\n")
	fmt.Printf("      -d '{\"name\": \"FUZZ\", \"anotherkey\": \"anothervalue\"}' -fr \"error\"\n\n")
	fmt.Printf("  Fuzz multiple locations. Match only responses reflecting the value of \"VAL\" keyword. Colored.\n")
	fmt.Printf("    ffuf -w params.txt:PARAM -w values.txt:VAL -u https://example.org/?PARAM=VAL -mr \"VAL\" -c\n\n")
	fmt.Printf("  More information and examples: https://github.com/ffuf/ffuf\n\n")
```

im sure like 100% of languages out there you can optimize it so much, by calling a simple string to where you do something like 

```go
ascii := `
 Fuzz file paths from wordlist.txt, match all responses but filter out those with content-size 42.
Colored, verbose output.\n
  ffuf -w wordlist.txt -u https://example.org/FUZZ -mc all -fs 42 -c -v
Fuzz Host-header, match HTTP 200 responses.
`

and so fourth, what would be better or migth be would jsut make a simple txt file and string out the content 

```go

func file(filename string) {
content, err := ioutil.ReadFile(filename)
if err != nil {
log.Fatal(err)
} else {
    fmt.Println(string(content)) 
}

}

```

Another suggestion would be, maybe see or test if the user is online first before attempting to make get requests something like 

```go

func test() {
get, err http.Get("http://google.com")
if err != nil {
log.Fatal(err)
} else {
    fmt.println("[ +=] Connection test passed")
}
}

```

these are just some simple things and ideas i think could change your code for the better, i am not a god nor do i know your code or how some of yall designed it or wanted it to be, but maybe these will help in the further future of other versions if you plan on it. also if you think i could help in any other way contact me here or some other way just let me know and i willbe willing to contribute to this amazing project! good day :D

**Comment by joohoi** [comment]
As common in open source - contributions are welcome. For the things you looked into, there are reasons why they are written in a way they are currently though:

**The documentation part with multiple fmt.Printf's**

While the multi-line strings definitely do exist in Go, the formatting makes it a bit hard to read and to manage to proper indentations for. As this part of the code is in no means performance critical, I opted to go with visually more readable option.


**Online test**

In many cases, ffuf can be used in internal networks, with potentially no internet connectivity, the online-check would then get in the way of the user.
