### ISSUE TITLE
Filter not working properly

### ISSUE THREAD

**Issue by jgk0** [ffuf/ffuf#506]
Discovered this while doing a portswigger lab called "Username enumeration via subtly different responses".
I was trying to filter the response body using flag -fr "/^Invalid username or password.$/"

Full command: 
ffuf -w tmp_list_username  -X POST -d "username=FUZZ&password=asdasd" -u "https://ac291ffc1ec617b0c0e60cf300a600c2.web-security-academy.net/login" -c -fr "/^Invalid username or password.$/".

 The expected output wouldn't come, even though the regex is correct, it can't filter the "." at the end.
 What i had to do, was  to output all responses to a folder and use grep + find to search for a file that doesn't match this pattern "Invalid username or password." .

**Comment by bsysop** [comment]
Hi @jgk0, do you have a sample of the website/api output?

**Comment by joohoi** [comment]
The regex looks a bit strange, I mean it's a regex allright, but I assume the "/" are extra there. I suggest you to go to https://regex101.com/ and to select "Go" from the left menu and testing your regex out in order to ensure its correct.

**Comment by joohoi** [comment]
Oh, and looks like you are also POSTing form data without the correct Content-Type header.
