### ISSUE TITLE
[Feature Request] pipe to ffuf

### ISSUE THREAD

**Issue by gprime31** [ffuf/ffuf#508]
Cat file.txt | ffuf -w wordlist.txt
To replace 
ffuf -w wordlist.txt -u FUZZ

**Comment by bsysop** [comment]
Hi buddy,

You can use bash for that.

```
cat file.txt | ffuf -w -:FUZZ -u FUZZ
```

**Comment by gprime31** [comment]
> Hi buddy,
> 
> You can use bash for that.
> 
> ```
> cat file.txt | ffuf -w -:FUZZ -u FUZZ
> ```

Thanks!!!!

**Comment by bsysop** [comment]
You welcome, please close the issue.
Thanks.
