### ISSUE TITLE
Multiple -fr or filter regex not working.

### ISSUE THREAD

**Issue by Aaryan9898** [ffuf/ffuf#516]
Hi .
The -fr doesn't work while using multiple time.

I have those urls in url.txt file.

https://assetstore.unity.com/linkmaker/embed/package/18125/widget-light
https://assetstore.unity.com/linkmaker/embed/list/115965/widget-wide-light

and if i run ffuf like this.
ffuf -u FUZZ -fr "LinkMaker/LinkMakerPackageEmbedController" -fr "LinkMaker/LinkMakerEmbedController" -H "User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; vivo 1606) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.120 Mobile Safari/537.36" -r -w url.txt

Intended behaviour.
shouldn't print any url.

Actual behaviour i am facing.
ffuf prints one url.

Can you please sort out this soon.
Thank you.

**Comment by jazzystring1** [comment]
You must escape the "/" because -fr command is dealing with regular expression. It should be like this:

-fr "LinkMaker\/LinkMakerPackageEmbedController"

**Comment by bsysop** [comment]
Hi @jazzystring1,

```
  -fr                 Filter regexp
```

it's a **REGEX** filter, which means you can use **regex patterns**.

Try this:
```
-fr "LinkMaker/(LinkMakerPackageEmbedController|LinkMakerEmbedController)"
```

You can create any regex rule using websites like https://regexr.com/

Happy hacking!

**Comment by marcelo321** [comment]
hey @bsysop,

for multiple regexs, it should be like this right? e.g `-fr "word\|word1\|word3"`. That's how it's done with `grep` for example, you need to escape | to have mutiple regexs.

**Comment by bsysop** [comment]
Hi @marcelo321,

I use ffuf `-mr` and `-fr` with **extended regex** and not **basic regex**

**Basic regex:**
```
grep '\(A\|B\|C\)' file
```

**Extended regex:**
```
grep -E '(A|B|C)' file
```

So I never escape the vertical bar, but if it works for you, must works too, have you tested?

For me **extended regex** is much easier and clean.

**Comment by joohoi** [comment]
I'll close this issue as I feel it has been resolved. Feel free to comment again if this is not the case and we can reopen the issue.
