### ISSUE TITLE
[Improvement] Collect data for each request to avoid data loss.

### ISSUE THREAD

**Issue by Shaddy** [ffuf/ffuf#52]
The output seems to be written at the end of the discovery, leading to a loss of data if the program is stopped manually. 

Sometimes could be interesting to grep partial data and use it to readjust a new fuzzing session.

For now, an approach to don't loose findings is to split up in two steps using `ffuf -s | tee output` and then running `< output | ffuf -w -`.

Thanks :)!

**Comment by joohoi** [comment]
This would be feasible for CSV (and eCSV) output with minimal changes. While using JSON output for sessions that result into a large amount of hits, it could get progressively slower, as everything needs to be written at once in order to not to leave the JSON structure to broken state.

**Comment by Shaddy** [comment]
For me as if you want to keep CSV as the default output. I just use `gron output |  rg (input|status)` all the time so for me is perfect :)

Thanks for your time and effort <3!

**Comment by joohoi** [comment]
This was implemented in #101

**Comment by mrthankyou** [comment]
As of `Fuzz Faster U Fool - v1.1.0-git`, I'm unable to see any output written when I `^C` while ffuf is running. Am I missing something?
