### ISSUE TITLE
Error when trying Authentication Bypass room in THM

### ISSUE THREAD

**Issue by deep8819** [ffuf/ffuf#524]
Hi there,
I was learning ffuf tools and its various options when using THM room, I am seeing this error and I am not able to understand why this is coming up:
![image](https://user-images.githubusercontent.com/100400228/155660038-1bedec8a-9e9a-4b6f-b047-b25c53b5d9cd.png)

error:
-u url not defined

Can someone please help me with this?

**Comment by bsysop** [comment]
Hi @deep8819,

The error is because of BASH, change the wordlists to something like this:
`-w wordlist1:W1 -w wordlist2:W2` and check if it works

To confirm my theory, just change the final `-u http://10.10....` to the beginning (`ffuf -u http://10.10....`)

**Comment by joohoi** [comment]
It looks like you have whitespaces between the wordlist filename and the keyword:
```
#wrong
-w valid_usersnames.txt: W1

#correct   
-w valid_usernames.txt:W1
```
