### ISSUE TITLE
Is this possible to have the output in both json and html format?

### ISSUE THREAD

**Issue by salooali** [ffuf/ffuf#529]
Hey
Thank you for this great tool. 
I'm trying to get the output in both formats JSON for parsing the output in a more meaningful way. I also need an HTML file report it also good for clients.

I'm trying the following command but it just gives me the output in HTML.

`ffuf -w wordlists2.txt -u https://www.example.com/FUZZ -e php,~,_bak,db -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" -ac -p '0.5-0.10' -t 40 -fc 404,505,501,502,401 -o jsonFile.json -o htmlFile.html -of html
`

Thanks

**Comment by joohoi** [comment]
Help text for `-of` points out the ability to get the output in all the available formats. Unfortunately there's no way to explicitly tell ffuf to output just few of them. It's either one or all at this time.

```
  -of                 Output file format. Available formats: json, ejson, html, md, csv, ecsv (or, 'all' for all formats) (default: json)
  ```
