### ISSUE TITLE
Repeated requests submitted recursion

### ISSUE THREAD

**Issue by weujieytt** [ffuf/ffuf#536]
-recursion-depth **4**  在代理中可以看见会重复发送4次请求

![image](https://user-images.githubusercontent.com/70327097/160574803-21b6006d-3f03-4d42-b450-a99bd81e7479.png)

**Comment by weujieytt** [comment]
上面的说法是错误的，我发现递归扫描重复几次应该是根据目录结构来决定的，例如： 我的目录：test1...test5,那么递归重复请求的次数为6*5+5*5
![image](https://user-images.githubusercontent.com/70327097/160582911-68f94915-4e14-4b7b-a4cb-d14a1d82ddb6.png)

**Comment by bsysop** [comment]
Hi @weujieytt, how are you doing?
Thanks to bring this, could you please let me know which docker image I could use to confirm this?

**Comment by weujieytt** [comment]
> Hi @weujieytt, how are you doing? Thanks to bring this, could you please let me know which docker image I could use to confirm this?

这并不是一个docker镜像，你可以使用任何网站，或者是自行搭建一个web服务。只需要将 目录 控制在可观察的范围内，挂上代理观察重复规律

**Comment by joohoi** [comment]
Hi, thanks for opening the issue. This seems to be a bug introduced in the last release.

**Comment by joohoi** [comment]
There's a new release 1.4.1 out now, that fixes this issue.
