### ISSUE TITLE
Unix config normalization

### ISSUE THREAD

**Issue by noraj** [ffuf/ffuf#542]
It's really nice to have [Configuration files](https://github.com/ffuf/ffuf#configuration-files) with [ffufrc](https://github.com/ffuf/ffuf/blob/master/ffufrc.example).
However having ~2000 "dotfiles" in `$HOME` is a bit less nice.

That why I suggest implementing a XDG compliant config deployment.

- **Specs**: [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
- **Env vars**: `XDG_CONFIG_HOME` (default to `$HOME/.config` for users) and `XDG_CONFIG_DIRS` (default to `/etc/xdg` for system)
- **Go libs**: [go-appdir](https://github.com/ProtonMail/go-appdir) (archived) - [configdir](https://github.com/shibukawa/configdir) (abandoned) - [kyoh86/xdg](https://github.com/kyoh86/xdg) (archived) - [adrg/xdg](https://github.com/adrg/xdg) (up to date)

The idea would be to have `~/.config/ffuf/config.ini` instead of  the legacy `~/.ffufrc`.

**Comment by daniel-ts** [comment]
My pull request addresses this issue. See #582.

Basically, ffuf would look for `.ffufrc` first in the current working directory, then in `$XDG_CONFIG_HOME/.ffufrc` on Linux and then `$HOME/.ffufrc`.

This pull also provides a mechanism to merge configuration from different sources sanely. The default hierarchy would be .ffufrc < request file < explicit config file < commandline args.

**Comment by noraj** [comment]
I guess this issue has been covered by 2.0 release. #582 still introduces more changes and simplifications.
