### ISSUE TITLE
There is no result when I use FFUF for fuzzing every website

### ISSUE THREAD

**Issue by aldobesma** [ffuf/ffuf#548]
### Version

-    ffuf v1.4.1-dev
- windows 10
- go version go1.18.1 windows/amd64

### Problem
I typed this command: 

> ffuf -w common.txt -u http://github.com/FUZZ

Result:
Nothing

Picture: https://drive.google.com/file/d/1lvY8qaxAy7tangk4MvPMpZXFOXwPDO5e/view?usp=sharing

**This happens to every website that I tried to fuzz with**

### Directory

- FFuf in C:\Users\user>
- Wordlist in C:\Users\user>

I don't actully know what went wrong to this. I already tried to search some youtube tutorial how to install it on win 10 64 bit. But, still that I got no result after following their video.

**Comment by bsysop** [comment]
Hi @aldobesma, 

please run like below:

```
ffuf -w common.txt -u http://github.com/FUZZ -debug-log debug.log
```

Then check debug.log
Is very likely a network issue or maybe kernel configuration.

**Comment by aldobesma** [comment]
Still the same thing, I got no result

**Comment by bsysop** [comment]
Check debug.log please.

**Comment by aldobesma** [comment]
I don't know where that "Debug.log" is? I am using win 10, already tried to find the tutorial on google still could not find the debug.log on win 10

**Comment by bsysop** [comment]
It is in the same directory you are in the cmd

```
ffuf -w common.txt -u http://github.com/FUZZ -debug-log C:\debug.log
```

It will be saved in `C:\debug.log`

**Comment by aldobesma** [comment]
I got the file now

Can you please open it here: https://drive.google.com/file/d/14auDuMX6krM4mvKx3XBK4diPRGrmFHI7/view?usp=sharing

There is a maximum words so i can't copy paste it here

**Comment by bsysop** [comment]
Hi @aldobesma, checking the file,  is possible to see something like:

```
2022/04/26 09:18:47 parse "http://github.com/\x00.\x00c\x00a\x00c\x00h\x00e\x00\r\x00": net/url: invalid control character in URL
2022/04/26 09:18:47 parse "http://github.com/\x00.\x00g\x00i\x00t\x00/\x00H\x00E\x00A\x00D\x00\r\x00": net/url: invalid control character in URL
2022/04/26 09:18:47 parse "http://github.com/\x00.\x00w\x00e\x00l\x00l\x00-\x00k\x00n\x00o\x00w\x00n\x00/\x00a\x00s\x00h\x00r\x00a\x00e\x00\r\x00": net/url: invalid control character in URL
```

So you are fuzzing with "illegal utf8" characters, is that what you really want?

If yes, ffuf will not help you on this, is better if you use common wordlists with paths, files, etc.

**Comment by aldobesma** [comment]
Im trying to understand this first. I just want to fuzz some dirctories, and become a legal bug hunter. I will search for "illegal utf8" first. 

Better common wordlist with path? So i shuold make a folder like 
`ffuf -w /path/to/wordlist -u https://target/FUZZ`

not only `-w  common.txt`?

**Comment by bsysop** [comment]
I don't know what you have in `common.txt`, but is not something you must use for fuzzing, 

Since this is not a FFUF issue, I recommend you to watch this
- https://www.youtube.com/watch?v=iLFkxAmwXF0 

And read everything you can here: 
- https://codingo.io/tools/ffuf/bounty/2020/09/17/everything-you-need-to-know-about-ffuf.html

If you need a wordlist, here you have something to start:
- https://github.com/danielmiessler/SecLists/blob/master/Discovery/Web-Content/raft-large-files-lowercase.txt

You was just fuzzing with the wrong wordlist.
Happy hacking!

**Comment by aldobesma** [comment]
I see, I just download some of wordlist in the link that you gave me. And there is some result come out now.

But actually I still confuse, cause yesterday i download in the `https://github.com/danielmiessler/SecLists`

I download in the `raw mode` it gaves no result. But yeah thanks anyway, I will try to check it later why it does not give the result even i copied from the same Seclist.

**Comment by bsysop** [comment]
Got it @aldobesma, clone the repo and you will have many wordlists.

Please close the issue when you can, thanks.
Happy hacking.

**Comment by aldobesma** [comment]
Ah I got `the main problem` 

So I changed the wordlist type from `encoding: UTF-16 LE` to `encoding: UTF-8`

Now I can see the result. Thanks @bsysop for your help. Hope you have a great day, and I am closing the issue now.

Happy Hacking!
