### ISSUE TITLE
Regex filtering not working as intended.

### ISSUE THREAD

**Issue by DBonacich** [ffuf/ffuf#549]
FFUF 1.5.0 Kali

I've noticed on several occasions that the -fr argument does not seem to properly filter regex from the response. Below is an example with the Mr. Robot box:

* The box has a wordpress login page that outputs "Invalid Username" on POST response.
![1](https://user-images.githubusercontent.com/81584492/165360849-4c76174d-efd5-4673-a815-31ee5859d469.png)
![2](https://user-images.githubusercontent.com/81584492/165360909-d3e908a0-6d89-4b1a-9123-d57908e5fc31.png)

* On using the -fr argument to filter the regex, ffuf still outputs anything that includes this regex
![3](https://user-images.githubusercontent.com/81584492/165361117-fad1d072-ade4-4b8f-bdc7-2124fee70fc5.png)

**Comment by bsysop** [comment]
Hi @DBonacich,

Ffuf will not set the `Content-Type` for you, the lack of Content-Type could give you some problems in POST requests, the best option is to use raw requests (`-request file request-proto https`).

In case you don't want to use raw requests, you can try setting the Content type header like below, but you also need to check what other headers the server expects to receive.

```
-H "Content-Type: application/x-www-form-urlencoded"
```

Maybe after setting the header it still don't works, so I suggest you to proxy ffuf to your Burp and read the error in the HTML response (I'm sure you need a pre-setted cookie to Bruteforce wordpress, but is better if you could check it)

This is not a ffuf error, but you need to setup it a bit more.
Happy hacking.

**Comment by joohoi** [comment]
A really common mistake when handling POST data for HTML forms is to not to
include the proprer Content-Type header, which I think is the issue here
too.

**Comment by bsysop** [comment]
Hi @DBonacich, closing this by now, the documentation is being improved to cover this case.
https://github.com/ffuf/ffuf/pull/775

Feel free to re-open if it has not resolved your case.
