### ISSUE TITLE
the -fs filtering option does not work for me.

### ISSUE THREAD

**Issue by octavio96** [ffuf/ffuf#550]
Im trying to execute this instruction "ffuf -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt:FUZZ -u http://academy.htb:30424/ -H 'Host: FUZZ.academy.htb' -fs 900 -c" but i do not why it print me all
![esta](https://user-images.githubusercontent.com/36074274/165644199-e19943ca-5ebe-46cf-9098-d7972e3a7952.jpg)

**Comment by joohoi** [comment]
On your command line, you have instructed ffuf to filter out all responses with a response size of exactly 900bytes, but the responses you see in the output have a different one.
