### ISSUE TITLE
Is there an option to append found results to the url ?

### ISSUE THREAD

**Issue by iso1983** [ffuf/ffuf#590]
Hi,
Assume that I run:
**ffuf -u https://target.com**
I want ffuf output on **cli**:
**https://target.com/somefoundPath**
instead of just **somefoundPath**

Is this possible?

**Comment by lavafroth** [comment]
Pretty sure you can do that using the `-v` flag.

**Comment by bsysop** [comment]
I will consider your issue as resolved.
Feel free to re-open if you still have questions.

Happy hacking.
