### ISSUE TITLE
How to bypass Wordpress Password Protected Pages with FFUF, Possible?

### ISSUE THREAD

**Issue by petemaverickx** [ffuf/ffuf#594]
Hi,

First of all I apologize if this is not the right forum to post this question. I have been asking it in forums (reddit, tryhackme, hackthebox, youtube) and nobody could answer me.

Is it possible to bypass Wordpress Password Protected Pages with FFUF?

Here is the situation:

1. Wordpress offers you the option to protect a page or post with a password (built-it feature)
2. For example this is the page you are protecting: mywebsite.com/page/
3. In the page there is a form with the field to submit the password.
4. When you click on Submit the page makes a **Redirect 302** to “mywebsite.com/wp-login.php?action=postpassword”
6. It sends the "../page/" as Referrer and the Password via Post Data.

This is what I'm doing:
**ffuf -w Documents/passwords.txt -u https://mywebsite.com/wp-login.php?action=postpassword -X POST -d “post_password=FUZZ&Submit=Entrar” -H “Referrer: https://mywebsite.com/page/” -r**

When using "-r" FFUF gives me 200 status code for all the words in the doclists (even the right one).
and returns 302 status code when no using "-r"

Thanks so much for reading and I apologize is not the right forum to post this, I'm new to this world.

Thanks

**Comment by bsysop** [comment]
Hi @petemaverickx,

Apparently, you are not sending the proper headers, my recommendation is to send it via Burp, analyze the sent Headers and then adapt it on FUFF.

For example in this case, you need to send the proper `content-type`, with the value `application/x-www-form-urlencoded`

Try it and you will see something different :)

**Comment by bsysop** [comment]
I will consider your issue as resolved.
Feel free to re-open if you still have questions.

Happy hacking.
