### ISSUE TITLE
No auto-detection of HTTP protocol when specifying -request file

### ISSUE THREAD

**Issue by Crypto-Cat** [ffuf/ffuf#596]
When saving a HTTP request and running ffuf with the `-request [filename]` option, you have to specify `-request-proto http`. 

Maybe a better approach would be to check the request e.g. *if* user doesn't specify the `-request-proto` on the command line, parse the first line of the request file, checking for "HTTP" and default to `-request-proto http`?

**Comment by bsysop** [comment]
Hi @Crypto-Cat, what about https?

**Comment by Crypto-Cat** [comment]
Yep, true. I can't think of a better approach, not sure there is one. I guess possibly default to the protocol in the origin/referer header but it's a stretch. I'll close this ticket 😅

**Comment by bsysop** [comment]
The only possible approach is to check HTTP and HTTPS, if one of the two doesn't works, then it fuzz the one that works, the problem is both work :)

Happy hackign!.
