### ISSUE TITLE
Recursion adding the same paths (with different caps on IIS) - Basically an issue with case sensitivity

### ISSUE THREAD

**Issue by ZerkerEOD** [ffuf/ffuf#604]
I have been scanning a lot recently and started using the recession option. The sad thing, though, is when I check jobs on an IIS host, I will see stuff like 'assets' 'Assets' and 'ASSETS', which all resolve to the same. So it creates three jobs for one technical directory. Any way to make recursion smarter to block the same or have it check case sensitivity before adding the job?

**Comment by bsysop** [comment]
Hey @ZerkerEOD, when scanning IIS, I recommend you use a lowercase wordlist, only.

```
cat wordlist | tr '[:upper:]' '[:lower:]' | sort -u > new_wordlist
```

Happy hacking!.

**Comment by ZerkerEOD** [comment]
> Hey @ZerkerEOD, when scanning IIS, I recommend you use a lowercase wordlist, only.
> 
> ```
> cat wordlist | tr '[:upper:]' '[:lower:]' | sort -u > new_wordlist
> ```
> 
> Happy hacking!.

As simple as that is, I can't believe I didn't think of it lol. Thanks for the tip!
