### ISSUE TITLE
ffuf showing no matches even though other tools show matches

### ISSUE THREAD

**Issue by ziul123** [ffuf/ffuf#606]
Running ffuf shows no matches, even though running gobuster with the same wordlist does show matches:

![image](https://user-images.githubusercontent.com/37045052/201260369-0a4eb1df-3d31-4188-99c9-cbfab4a94af4.png)
![image](https://user-images.githubusercontent.com/37045052/201260443-4a9e43c3-5b79-4677-898c-0ab4a11de86f.png)

I am using the prebuilt binary of the latest release of ffuf (v1.5.0).

**Comment by Kaz721** [comment]
-u http://10.10.11.184/FUZZ
