### ISSUE TITLE
Help needed! Output not getting saved

### ISSUE THREAD

**Issue by lazywithcrazyness** [ffuf/ffuf#607]
I used this ffuf -w httpx.txt:URL -w onelistforallmicro.txt:WORDS -u URL/WORDS -fc 429 -of -o ffuff.html

But output is not getting saved what to do

**Comment by Acidwaverzs** [comment]
same issue

**Comment by hvprvtr** [comment]
Same issue. Wait some works in screen, but nothign saved :( Output file not creating. 50/50.

**Comment by bsysop** [comment]
Hi @lazywithcrazyness,

There is a typo in the way you are using `-of`, is necessary to specify the type of output that you want.

```
-of                 Output file format. Available formats: json, ejson, html, md, csv, ecsv (or, 'all' for all formats) (default: json)
```

So the right argument would be `-of html`

**Example:**

```bash
ffuf -w httpx.txt:URL -w onelistforallmicro.txt:WORDS -u URL/WORDS -fc 429 -of html -o ffuff.html
```

Happy hacking.

**Comment by hvprvtr** [comment]
Ok, but 2 questions:
1) Why ffuf dont alert about it? Why its allow me specify -o without -of? 
2) Why 50|50 output file is creating? I run 2 scans with -o only, and one outfile is creating.

**Comment by hvprvtr** [comment]
Ok, but 3 questions:
1) Why ffuf dont alert about it? Why its allow me specify -o without -of? 
2) Why 50|50 output file is creating? I run 2 scans with -o only, and one outfile is creating. 
3) Why -of did not have default value?
