### ISSUE TITLE
Question for mass checking a list of sites for /.git/HEAD

### ISSUE THREAD

**Issue by Darkcast** [ffuf/ffuf#610]
Hi
I have a list of site that i would like to check for ```/.git/HEAD```
basically what I want to do is for fuffs to check if the body response contains something like 
```
ref: refs/heads/main
ref: refs/heads/master
```
The acme_subfinder_results containts all the sites I want to test and the word list only contains /.git/HEAD
```ffuf -w acme_subfinder_result.txt:DOMAIN -w versioning_metafiles.txt -u DOMAIN/FUZZ -o acme_versioning -of html -p 0.1-2.0 -mc 200 -t 10```

I was wonder which ```flag``` can i use to matched the body response I am looking for ?

Thank you kindly

**Comment by bsysop** [comment]
Hi @Darkcast, you can use `-mr` to match Regex as you need.

**Comment by Darkcast** [comment]
> Hi @Darkcast, you can use `-mr` to match Regex as you need.

Thank you, could you help me out making a correct regex (i suck ) 
:)

**Comment by bsysop** [comment]
Something like `ffuf -u "URL/.git/config" -w urls_list:URL -mr "\[core\]" -c -r` must works, then you can play with any other conditions you need, like threads, output, combining the matches/filters, etc.

**Comment by Darkcast** [comment]
ok.thank you :)
