### ISSUE TITLE
Using regexp to filter pages starting with dot stop working

### ISSUE THREAD

**Issue by r3nt0n** [ffuf/ffuf#619]
I notice that when I try to filter with the usual regexp `/\..*` to not show pages starting with a dot, `ffuf` still shows it:

```
ffuf -u http://example.com/FUZZ -w /usr/share/seclists/Discovery/Web-Content/raft-large-words-lowercase.txt -fr '/\..*'

        /'___\  /'___\           /'___\       
       /\ \__/ /\ \__/  __  __  /\ \__/       
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\      
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/      
         \ \_\   \ \_\  \ \____/  \ \_\       
          \/_/    \/_/   \/___/    \/_/       

       v1.5.0 Kali Exclusive <3
________________________________________________

 :: Method           : GET
 :: URL              : http://example.com/FUZZ
 :: Wordlist         : FUZZ: /usr/share/seclists/Discovery/Web-Content/raft-large-words-lowercase.txt
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 40
 :: Matcher          : Response status: 200,204,301,302,307,401,403,405,500
 :: Filter           : Regexp: /\..*
________________________________________________

server-status           [Status: 403, Size: 280, Words: 20, Lines: 10, Duration: 32ms]
                        [Status: 200, Size: 137, Words: 40, Lines: 6, Duration: 53ms]
.htaccess               [Status: 403, Size: 280, Words: 20, Lines: 10, Duration: 28ms]
.htpasswd               [Status: 403, Size: 280, Words: 20, Lines: 10, Duration: 29ms]
index.html              [Status: 200, Size: 137, Words: 40, Lines: 6, Duration: 30ms]
.hta                    [Status: 403, Size: 280, Words: 20, Lines: 10, Duration: 27ms]
.htm                    [Status: 403, Size: 280, Words: 20, Lines: 10, Duration: 27ms]
(...)
```

I tried escaping the slash too (`\/\..*`) but show the same behavior, is this feature stop working as expected?

Thanks in advance! :)

**Comment by bsysop** [comment]
Hi @r3nt0n, just to confirm, are you using regex to filter the PATH? Regex is used by FFUF to filter the `response content`.

**Comment by r3nt0n** [comment]
Hi @bsysop , Im following the method proposed by noraj in the [ffuf THM room](https://tryhackme.com/room/ffuf) (right at the end of Task 4) and [here](https://www.acceis.fr/ffuf-advanced-tricks/) (Avoiding false negatives section).

**Comment by bsysop** [comment]
I have not read that article @r3nt0n, but you got my point? using regex you are filtering the response output

**Comment by r3nt0n** [comment]
What would be the right way to filter out this results?

**Comment by bsysop** [comment]
In that case, you are trying to hide `.something`, but that is explicitly in your wordlist, so if you don't wanna see that, the most clever thing to do is to remove it from your wordlist, you are sending requests with it, wasting time, local resources and servers resources for something you don't want. Makes sense?

Other than that, you have to filter using `-ac` and `-acc` as related in the `README.md`

**Comment by r3nt0n** [comment]
Makes sense, thanks @bsysop :+1:  sometimes we couldn't see the forest for the trees

**Comment by bsysop** [comment]
That's deep!
Happy hacking @r3nt0n.
