### ISSUE TITLE
reCAPTCHA / ffuf

### ISSUE THREAD

**Issue by 1lchenko** [ffuf/ffuf#621]
If i set ffuf to guess passwords/logins on the  web page. reCAPTCHA will it interfere with this? help pls

**Comment by 1lchenko** [comment]
sorry for my English, if it's not clear - I'll clarify

**Comment by bsysop** [comment]
Hi, @1lchenko your English is fine :)

Ffuf doesn't has that feature at this moment, reCAPTCHA works similar to CSRF tokens (even safer), there is a discussion going on about it -> https://github.com/ffuf/ffuf/issues/525

**Comment by bsysop** [comment]
Closing this by now since there is another issue for a similar case.
Happy hacking
