### ISSUE TITLE
CSRF TOKEN Bypass 

### ISSUE THREAD

**Issue by silverbullet-herr** [ffuf/ffuf#622]
is there is any way to extract the csrf token from the web forms and pass it to ffuf as a second parameter  using (Pitchfork+recursive grep) attack like  in burpsuite ??

**Comment by bsysop** [comment]
Hi @silverbullet-herr, there is a discussion about this here -> https://github.com/ffuf/ffuf/issues/525

**Comment by bsysop** [comment]
Closing by now, since there is already a discussion about it.
Happy hacking.
