### ISSUE TITLE
console output bug

### ISSUE THREAD

**Issue by prohk** [ffuf/ffuf#623]
command: ffuf -u https://xxxx/FUZZ -w dicc.txt
version: macos: 13.1
how can i Mask these outputs?
<img width="558" alt="image" src="https://user-images.githubusercontent.com/37725167/210473950-d500f783-2d48-4ea6-92d6-ccdd6842bf91.png">

**Comment by bsysop** [comment]
Your terminal is very small, please increase the size of your terminal or decrease the font size.

**Comment by prohk** [comment]
it works! thanks
