### ISSUE TITLE
Killed...please help me

### ISSUE THREAD

**Issue by welltest** [ffuf/ffuf#626]
ffuf -w /root/wordlists/wordlist.txt -u "https://FUZZ.abc.com" -mc 200,302,403 -of csv -timeout 60

:: Progress: [713934/9544235] :: Job [1/1] :: 1669 req/sec :: Duration: [1:38:12] :: Errors: 713816 ::zsh: killed     ffuf -w /root/wordlists/wordlist.txt -u "https://FUZZ.abc.com" -mc

**Comment by joohoi** [comment]
My guess would be that this is a kernel OOM killer; your wordlist itself with almost 10 million entries is a huge memory hog, and when you add the results to memory (guessing they are all 200's) you are simply running out of memory, and your kernel is doing the best thing it can think of - killing the process.
