### ISSUE TITLE
Issue with silent mode and json

### ISSUE THREAD

**Issue by ocervell** [ffuf/ffuf#628]
When using silent mode (`-s`) and JSON lines (`-json`) together, the output is no more a JSON but a normal text. Ideally we want silent mode to just hide the progress bar in this mode, and just output JSON lines.

ffuf version: v1.5.0-dev

**Comment by joohoi** [comment]
That's reasonable, and will be added. As of now, you can workaround this by running the "non-silent" mode and redirecting STDERR to `/dev/null`.
