### ISSUE TITLE
Version 2.0.0 not installed when using @latest reference

### ISSUE THREAD

**Issue by righettod** [ffuf/ffuf#636]
Hi,

It is normal that the version **1.5.0** is still installed when using the [install command from the documentation](https://github.com/ffuf/ffuf#installation) ?

```shell
go install github.com/ffuf/ffuf@latest
```

I tried this morning and the version **1.5.0** was installed instead of the **2.0.0**:

![image](https://user-images.githubusercontent.com/1573775/216811544-b7163f21-177d-4eb0-b0d4-744cc4a89e18.png)

![image](https://user-images.githubusercontent.com/1573775/216811648-e95c683e-4dcf-44cb-b58b-854fbb2ebb5e.png)

Thank you very much in advance for your feedback 😃

**Comment by joohoi** [comment]
Looking into it, I have no idea why go install doesn't see the new version tag.

**Comment by righettod** [comment]
Thanks a lot for the feedback.

**Comment by xnl-h4ck3r** [comment]
@righettod I had the same issue, but I realiised it was building the new binary correctly, but just not moving it to `~/go/bin`.
So until a proper fix, after running `git clone https://github.com/ffuf/ffuf ; cd ffuf ; go get ; go build` you can just do `mv ffuf ~/go/bin/`

**Comment by righettod** [comment]
@xnl-h4ck3r Thank you very much for the hint and infos 💯

**Comment by joohoi** [comment]
This is now fixed in the README, the go install command to get the latest ffuf v2 version is:
`go install github.com/ffuf/ffuf/v2@latest`

**Comment by righettod** [comment]
Thank you
