### ISSUE TITLE
The output of s.PrintResult of ffuf on windows does not completely cover the output of j.Output.Progress

### ISSUE THREAD

**Issue by yikuaibro** [ffuf/ffuf#642]
normal:
![image](https://user-images.githubusercontent.com/44493045/218137817-376f1134-9dee-463e-81fa-5f1ab724697b.png)
But on windows the following output appears
**Input**: ```ffuf -u https://codingo.io/FUZZ -w ./ffuf_eg.txt -mc all```
**output**:
![image](https://user-images.githubusercontent.com/44493045/218137254-05c5b68f-1272-4288-8e73-d27b1a72ef31.png)

This happens because ```\r\r``` the override of the short string overrides the long string.

**Comment by yikuaibro** [comment]
#644

**Comment by yikuaibro** [comment]
@noraj  Excuse me, does this appear on all windows or is it just me?

**Comment by noraj** [comment]
Why am I pingeg here?

**Comment by yikuaibro** [comment]
> Why am I pingeg here?
Sorry, I @ wrong person, I think you are ffuf’s reviewer.

**Comment by yikuaibro** [comment]
> @noraj Excuse me, does this appear on all windows or is it just me?

@joohoi

**Comment by yikuaibro** [comment]
@joohoi Hi, are you busy? Please reply me when you are free, because this output will affect my current project, I want to know what is causing it.
go version: 1.18+
OS: win 10, win11
CMD, powershell and gitbash all have this output.
Hope you notice this, thanks！

**Comment by joohoi** [comment]
Hi @yikuaibro , I unfortunately don't have a windows box to test / develop on at the moment. I'm a bit puzzled why this happens, as the progress bar (the long output in your example) is written in STDERR, while the results are printed out to STDOUT. I think this might be a bug in the terminal program you may be using. Not sure though.

**Comment by yikuaibro** [comment]
@joohoi  I've tried outputting both of them to STDERR, but it still doesn't work.
```
func (s *Stdoutput) resultMultiline(res ffuf.Result){
        ...
        fmt.Printf("%s\n%s\n", res_hdr, reslines)
}
```
I noticed here that Printf outputs to STDOUT, but even though I tried changing to `Fprintf(os.stderr,...)` it still didn't work.

**Comment by joohoi** [comment]
What I meant was that as they currently are printed to different buffers,
they shouldn’t ever ”interfere” with each other.

And because of that my initial thought is that the terminal which you use
is not correctly handling these buffers.

**Comment by yikuaibro** [comment]
@joohoi 
Yes, STDOUT is buffered, I noticed that in UNIX using ```TERMINAL_CLEAR_LINE = "\r\x1b[2K"``` is to clear the contents of the current line, but in windows using ```TERMINAL_CLEAR_LINE = "\r\r"```, just simply overriding. 
So i tried doing this change in windows ```"\r\r" -> "\r\r\x1b[2K" ```.
It works. 
I use CMD, so I hope you can test it in windows,
