### ISSUE TITLE
How to get back the 1 line verbosity like v1.5

### ISSUE THREAD

**Issue by C4lputer** [ffuf/ffuf#645]
Now it takes 3 lines for 1 result which to me is quite frustrating

![image](https://user-images.githubusercontent.com/93414512/218296059-d04d2ac2-3ca8-41e5-845a-638f1e521b8e.png)

**Comment by joohoi** [comment]
Hi, thanks for opening the issue. This is a bug in case you have no
scrapers enabled. With no scrapers it should default to single-line output,
but the check for it seems to be broken.

However in the case you are using scrapers, the multi-line output is the
only possible output format.

**Comment by C4lputer** [comment]
`ffuf -w /opt/SecLists/Discovery/Web-Content/raft-medium-directories-lowercase.txt -u "http://google.com/FUZZ"`

I just fuzz like I always do, but when I update to version 2 this happened. So I supposed this is a bug and there will be a fix soon?
Thank you for the quick response.

**Comment by riramar** [comment]
Same problem here. AFAIK it's not possible to create filters like:

(HTTP code 400) OR (HTTP code 404) OR (HTTP code 301 AND Words 456)

So I was filtering out using egrep since the results were present in one line.
Now I'm getting 3 lines per result even with no scrapers.

**Comment by dhtzs** [comment]
I'm experiencing the same issue. Seems like ffuf 2.0 now takes 3 lines for a result without using scrapers, which is frustrating indeed.

**Comment by vionde** [comment]
Hope it will be fixed soon, but until that `go install github.com/ffuf/ffuf@v1.5.0`

Anyway, thanks for your work!

**Comment by 0xGreen** [comment]
Hi there,

Fuzzing like i used to do (no `-scrapers`)

```bash
ffuf -u http://example.com -w wordlist.txt -H 'Host: FUZZ.example.com' -mc all -fw 1288
```
but the output is really weird, like 3 lines for 1 hit.

Just like @C4lputer, too much for me as well.

![image](https://user-images.githubusercontent.com/6963584/220812022-d071e999-8551-4c56-a7d1-ea8390b75632.png)

**Comment by p0dalirius** [comment]
Hi,

I've fixed the bug, proposed a pull request and wrote details on what was happening in https://github.com/ffuf/ffuf/pull/656

It now works awesomely on my end.

Best regards,

**Comment by cardassian-tailor** [comment]
Just wanted to say I also am having this issue and look forward to this being fixed. Thank you.

**Comment by 0xCGonzalo** [comment]
Hi,

I've the same issue with a previous update at this date.

![image](https://user-images.githubusercontent.com/43796175/227578059-3321e3e5-6ef7-422a-bb5c-1d26babbeb34.png)

**Comment by p0dalirius** [comment]
> Hi,
> 
> I've the same issue (previously updated the tool) at this date.
> 
> ![image](https://user-images.githubusercontent.com/43796175/227578059-3321e3e5-6ef7-422a-bb5c-1d26babbeb34.png)

If you need, the issue is fixed in the not-yet-merged https://github.com/ffuf/ffuf/pull/656

Best regards,

**Comment by 0xCGonzalo** [comment]
It's work.

Thank you sir Rémi, @p0dalirius.

**Comment by 0xdf223** [comment]
Yeah. This makes ffuf unusable for me. Would love to see it back in a compact line. Back to wfuzz until then.

**Comment by HeckerBirb** [comment]
The PR made by [p0dalirius](https://github.com/p0dalirius) referenced here: https://github.com/ffuf/ffuf/issues/645#issuecomment-1453979462 can be build locally by checking out their branch and following the steps for building from source. 
Doing so will fix the problem described in here.

**Comment by AkechiShiro** [comment]
Given the nature of the issue and the PR fix that has been submitted, is this project a bit on hold/unmaintained right now ?

**Comment by p0dalirius** [comment]
Hey,

Any progress on this @tomikoski @joohoi ?

Best regards,

**Comment by joohoi** [comment]
This fix has now been merged. Thanks @p0dalirius !

> Given the nature of the issue and the PR fix that has been submitted, is this project a bit on hold/unmaintained right now ?
Nope, but I've been very busy recently. Now back to it.

**Comment by AkechiShiro** [comment]
Thanks a lot @joohoi ! 

Maybe there should be a way for some serious/recurrent/trusted contributors to the project (after for instance 5/10/15 good PRs) that they could ask to be set as co-maintainers (or recommended by other users) in order to avoid this kind of situation, maybe @p0dalirius could want to have those rights since he fixed this bug pretty fast and his maintaining quite a lot of tools on GitHub already, but I can't just speak for him like this, he might be very busy and not a right fit for that.

But it would be something to consider as an improvement for contributors/contributions, I'd guess !

**Comment by HeckerBirb** [comment]
I'd personally rather have to compile a pull request from sources rather than see random folks be allowed to simply merge changes to the main repo without vetting by the owner. This tool is primarily used by people who hack in one way or another. If all I takes is 15 good PRs before they can sneak in their own agenda.... 😂

**Comment by AkechiShiro** [comment]
Yeah you're not incorrect @HeckerBirb, then the hacker would need to have a provable record of being someone "ethical" in the community, but this is was just an idea, it can be expanded, or there should be at least 2 others contributors who have 100 PRs merged in vouching for him. But I understand it's risky.
