### ISSUE TITLE
2.0.0 release changed content

### ISSUE THREAD

**Issue by SMillerDev** [ffuf/ffuf#649]
When Homebrew downloaded the 2.0.0 release on the 4th the shasum was "`bc27b19ed78b31862b1922a3adb66839cdf58c9b799a715c206709a73e2583d0`" now the release page says that it was released on the 6th and the shasum is "`80b42fe3dda8b24e10bade7b18651d402d1acf5031baedd0b344985721f3d8cd`". Was the release retagged or is the repo compromised? Because the [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do.

**Comment by joohoi** [comment]
It was retagged. And yes, I might be insane ;)
That is both correct and unfortunate, the reason for retagging was me missing some details on how Go install handles pathspec for v2 onward (moving from v0.x to v1.x doesn't have this issue). Sorry for the inconvenience.

https://twitter.com/joohoi/status/1622529658330787840

**Comment by joohoi** [comment]
I'm closing this issue as I don't believe it requires more tracking. Sorry again, and I'll make this doesn't repeat in the future.

**Comment by SMillerDev** [comment]
Thanks for the quick answer, I think this is now resolved indeed
