### ISSUE TITLE
random user-agent

### ISSUE THREAD

**Issue by kN6jq** [ffuf/ffuf#653]
Please add a random user-agent to it.    

The security device has set the default user-agent to a tool signature.

**Comment by p0dalirius** [comment]
Hi,

You can set a custom user agent with `-H "User-Agent: YOUR_USER_AGENT_HERE"`

Example:
```
ffuf -w entries.txt -u http://192.168.1.27/FUZZ -H "User-Agent: YOUR_USER_AGENT_HERE"
```

Results:

![image](https://user-images.githubusercontent.com/79218792/226100054-dac86998-0ce7-41c9-a8a5-3ea7a75dab83.png)

Best regards,
