### ISSUE TITLE
"zsh: killed" when using very big wordlists

### ISSUE THREAD

**Issue by carouselcarousel** [ffuf/ffuf#658]
I get the error message "zsh: killed" when I try to laod in multiple gigabyte wordlists.
Is there any way to get around this problem?
Or is there any option I can use to load these list files?

__(Before FFUF I used patator and this was never a problem on the same wordlist (So no problem with the list). Turned to ffuf becaue all the pycurl problems with patator)._

**Comment by bsysop** [comment]
Hi @carouselcarousel, **ffuf** was killed by a resource limit of your server, VPS, or computer.
You can:
- Increase the resources of your station
- Split the wordlist into smaller chunks (check `split` command)

Since this is not `ffuf` issue, there is nothing to change or fix.

Happy hacking.
