### ISSUE TITLE
fuff won't run

### ISSUE THREAD

**Issue by eitansha** [ffuf/ffuf#659]
hi, 

I'm running this command:

`ffuf -u Domain/FUZZ -w leaky-paths.txt -o test_ffuf.txt `

but I always get the same output:

`:: Progress: [1694/1694] :: Job [1/1] :: 0 req/sec :: Duration: [0:00:00] :: Errors: 1694 ::`

I got the same results with some other domains. 
Also, i can access those domains manually with my browser so I guess it is not issue with my internet connection.

**Comment by bsysop** [comment]
Hey @eitansha,
You can debug it using the flag `-debug-log logfile` and then check the file `logfile` to see what failed!

**Comment by eitansha** [comment]
> Hey @eitansha, You can debug it using the flag `-debug-log logfile` and then check the file `logfile` to see what failed!

Thanks , I will try it.

**Comment by bsysop** [comment]
You welcome, close this issue when you get a resolution, please.

**Comment by joohoi** [comment]
Thanks again @bsysop , closing the issue as I assume it was resolved.
