### ISSUE TITLE
[Feature Request] Offset for response lengths

### ISSUE THREAD

**Issue by arbazkiraak** [ffuf/ffuf#66]
```
curl -s "https://www.facebook.com/" | wc -c
142767
```
```
curl -s "https://www.facebook.com/" | wc -c
142720
```

* Sometimes response lengths can by dynamic, is there any way to set an offset value along with `-fc` filter to filter the response lengths with an offset value.

* This will be problematic for both parameter fuzzing & Vhost fuzzing.

**Comment by joohoi** [comment]
Do you think `-fc` ranges could answer this need? This is already supported, so you could do `-fc 142700-142800` (in the example above). This is already supported in the current `master` version, and will be included in the next release.

**Comment by arbazkiraak** [comment]
* Apologies I missed checking out the `ranges` in Usage guide.
