### ISSUE TITLE
Inaccurate results

### ISSUE THREAD

**Issue by y0sua** [ffuf/ffuf#663]
Hello team,
could you please explain why the FFUF result is not accurate? or maybe this is a bug, if not please correct me.

My scenario:
I created a simple wordlist called "w.txt" for my testing purpose:
```
test 
index
robots.txt
findtheticket
aaaa
404
testing
```

note: the "findtheticket" is an existing page

run: ```ffuf -c -w w.txt -u https://www.target.com/FUZZ```
result: ```:: Progress: [7/7] :: Job [1/1] :: 1 req/sec :: Duration: [0:00:34] :: Errors: 7 ::```
FFUF in this case can not find the existing page, as we can see it said error (7), could you please explain what's happening here?

run: ```python3 dirsearch.py -u https://www.target.com -w w.txt```
result:
[13:15:09] 200 -  261KB - /findtheticket
[13:15:09] 200 -  909B  - /robots.txt

**Comment by bsysop** [comment]
Hey @y0sua,

Please run it with the debug argument `-debug-log debug.log` and then you know what is happening in the background.

Let me know if the debug information is not clear enough or if you need some help on it.

**Comment by y0sua** [comment]
Hi @bsysop ,
output:
```
2023/04/02 08:56:11 Error while opening default config file: open /root/.ffufrc: no such file or directory
```

**Comment by bsysop** [comment]
And it had errors? Are you sure?

Please put screenshots of everything, thank you.

**Comment by y0sua** [comment]
yes, here it is

<img width="860" alt="ffuf" src="https://user-images.githubusercontent.com/52686759/229774374-c644834a-90f4-4db8-8ce0-3c0c08eb28c0.png">

**Comment by bsysop** [comment]
Right, In that case, ffuf is working normally, differently from your first ticket it don't have errors.

Please check with curl what is the code response from `/findtheticket`

```bash
curl -i https://domain.com/findtheticket
```

**Comment by y0sua** [comment]
here it is:
200
<img width="659" alt="curl" src="https://user-images.githubusercontent.com/52686759/230077825-461ff8c3-6135-4526-a761-9ad0e03721d2.png">

**Comment by bsysop** [comment]
Hi @y0sua, interesting
Could you send me the URL, please?

Thank you

**Comment by y0sua** [comment]
Hi @bsysop ,
thanks for replying to me
could you drop here your email / telegram?

Thank you

**Comment by bsysop** [comment]
https://twitter.com/bsysop :)

**Comment by y0sua** [comment]
@bsysop sent!

**Comment by bsysop** [comment]
Hi @y0sua, you are fuzzing a URL that is hosted in `fastly.net`, then when you fuzz with the default FFUF User-Agent, their WAF is flagging you and returning a 403 code.

My recommendation:
- Add a custom User-Agent

```
-H "User-Agent: $your_user_agent"
```

- Catch more responses than HTTP 200

```
-mc 200,403,etc
```

**PoCs:**

```

        /'___\  /'___\           /'___\
       /\ \__/ /\ \__/  __  __  /\ \__/
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/
         \ \_\   \ \_\  \ \____/  \ \_\
          \/_/    \/_/   \/___/    \/_/
________________________________________________

 :: Method           : GET
 :: URL              : https://www.███████/FUZZ
 :: Wordlist         : FUZZ: wl
 :: Header           : User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 40
 :: Matcher          : Response status: 200,204,301,302,307,401,403,405,500
________________________________________________

[Status: 200, Size: 259919, Words: 24709, Lines: 1795, Duration: 149ms]
| URL | https://www.███████/findtheticket
    * FUZZ: findtheticket
```

```
        /'___\  /'___\           /'___\
       /\ \__/ /\ \__/  __  __  /\ \__/
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/
         \ \_\   \ \_\  \ \____/  \ \_\
          \/_/    \/_/   \/___/    \/_/
________________________________________________

 :: Method           : GET
 :: URL              : https://www.█████████/FUZZ
 :: Wordlist         : FUZZ: wl
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 40
 :: Matcher          : Response status: 200,204,301,302,307,401,403,405,500
________________________________________________

[Status: 403, Size: 425, Words: 55, Lines: 18, Duration: 145ms]
| URL | https://www.███████/findtheticket
    * FUZZ: findtheticket
```

I hope it helps.

**Comment by y0sua** [comment]
Thanks, it works
```
ffuf -w w.txt -u https://www.site.com/FUZZ -H "User-Agent: testing123" -mc 200
```
