### ISSUE TITLE
ffuf fails to generate output in html format

### ISSUE THREAD

**Issue by thecompositenoob** [ffuf/ffuf#684]
Command :: 

ffuf -c -ic -w /home/x/testd0/xwordlists/xlists/cmbd0.txt -u http://$tip:80/FUZZ -o c0.html -of html

Error :: 

[ERR] template: output.html:74:94: executing "output.html" at <$result.HTMLColor>: can't evaluate field HTMLColor in type output.htmlResult

**Comment by cyb3rsalih** [comment]
Got same error today, anyone knows why

**Comment by thecompositenoob** [comment]
Thank you
