### ISSUE TITLE
-mr cant fetch multile regex 

### ISSUE THREAD

**Issue by p3n73st3r** [ffuf/ffuf#692]
Want to match multiple words from response with -mr But unable to
Even tried 

-mr "xx|zz"
-mr "xx||zz"

Any solution ?

**Comment by Bryan-Herrera-DEV** [comment]
Could you tell us how was your initial test attempt, what error did it cause and how would you like it to be solved?

**Comment by phvietan** [comment]
@p3n73st3r Are you sure you tested well ? Because I write response match success with -mr "(Erro)|(abc)|(xyz)" .

**Comment by bsysop** [comment]
Hi all, @p3n73st3r check if the other arguments are conflicting with the match-regex one.

Normal regex works fine:

```
-mr "abc|def"
-mr "(abc|def)"
```
