### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by notmarshmllow** [ffuf/ffuf#699]
Please add a feature that will take a list of URLs as input. Everyone in the community needs this.

**Comment by bsysop** [comment]
Hi @notmarshmllow, meanwhile the feature is not created, you can run it like this:

```bash
cat urls_file.txt | ffuf -w -:FUZZ -u FUZZ [...]
```

**Comment by notmarshmllow** [comment]
I can supply file via stdin? I didn't knew that! Thanks @bsysop. I will try it right away

**Comment by bsysop** [comment]
Yes sir, enjoy :)

**Comment by notmarshmllow** [comment]
Hi @bsysop How do you supply wordlist? Will you please kindly provide full command?

**Comment by bsysop** [comment]
The same way

```bash
cat urls_file.txt | ffuf -w -:FUZZ -u FUZZ [...]
```

`-w` is how you set the wordlist, it can be a file.

```bash
ffuf -w /path/to/wordlist -u https://target/FUZZ
```

Full arguments can be found in the README.MD at https://github.com/ffuf/ffuf
