### ISSUE TITLE
The recursion "greedy" mode of operation is so stupid.

### ISSUE THREAD

**Issue by JaveleyQAQ** [ffuf/ffuf#703]
The recursive end file is something I don't understand 
![image](https://github.com/ffuf/ffuf/assets/132129852/243623b7-0f30-4d68-a128-43d645a2d163)

**Comment by bsysop** [comment]
Hi @JaveleyQAQ,

Let's go step by step, we need first to understand what FFUF is, and it is a fuzzing tool that can be used not only for the discovery of files and directories but also has multiple other functionalities.

The argument is there in case you want to use it, but if don't fits your needs or expectations, use any of the other recursion strategies.

In case you want just a traditional file/directory discovery tool, you can find tons of those on GitHub.
