### ISSUE TITLE
progress line can't hold in terminal

### ISSUE THREAD

**Issue by EtherealRise** [ffuf/ffuf#704]
I'm using the simplest command `ffuf -u xxx -w xx -H "Host: FUZZ.xxx"`

The problem is that the progress line in output, aka

> :: Progress: [41/4989] :: Job [1/1] :: 0 req/sec :: Duration: [0:00:01] :: 

can't hold, it keeps scrolling out and mess things up
`:: Progress: [63/4989] :: Job [1/1] :: 18 req/sec :: Duration: [0:00:02] :::: Progress: [64/4989] :: Job [1/1] :: 18 req/sec :: Duration: [0:00:02] :::: Progress: [64/4989] :: Job [1/1] :: 18 req/sec :: Duration: [0:00:02] :::: Progress: [64/4989] :: Job [1/1] :: 18 req/sec :: Duration: [0:00:03] :::: Progress: [64/4989] :: Job [1/1] :: 18 req/sec :: Duration: [0:00:03] :::: Progress: [64/4989] :: Job [1/1] :: 18 req/sec :: Duration: [0:00:03] :::: Progress: [68/4989] :: Job [1/1] :: 14 req/sec :: Duration: [0:00:03] :::: Progress: [78/4989] :: Job [1/1] :: 18 req/sec :: Duration: [0:00:03] :::: Progress: [78/4989] :: Job [1/1] :: 18 req/sec :: Duration: [0:00:03] :::: Progress: [81/4989] :: Job [1/1] :: 17 req/sec :: Duration: [0:00:03] :::: Progress: [81/4989] :: Job [1/1] :: 17 req/sec :: Duration: [0:00:03] :::: Progress: [81/4989] :: Job [1/1] :: 17 req/sec :: Duration: [0:00:04] :::: Progress: [81/4989] :: Job [1/1] :: 17 req/sec :: Duration: [0:00:04] :::: Progress: [81/4989] :: Job [1/1] :: 17 req/sec :: Duration: [0:00:04] :::: Progress: [93/4989] :: Job [1/1] :: 17 req/sec :: Duration: [0:00:04] :::: Progress: [103/4989] :: Job [1/1] :: 20 req/sec :: Duration: [0:00:04] ::: Progress: [103/4989] :: Job [1/1] :: 20 req/sec :: Duration: [0:00:04] ::: Progress: [106/4989] :: Job [1/1] :: 19 req/sec :: Duration: [0:00:04] ::: Progress: [107/4989] :: Job [1/1] :: 31 req/sec :: Duration: [0:00:04] :
`

I'm in kali virtual machine 2023.2a, tested on xterm-color256 and Alacritty for same results.

**Comment by mehrankazemi1122** [comment]
thats my problem too
