### ISSUE TITLE
When using -mt >time please include all requests that timeout to detect sqli time-based

### ISSUE THREAD

**Issue by phvietan** [ffuf/ffuf#707]
When using ffuf -mt >time , there are many times that timed out requests are actually the detected sql injection (for time-based). 
Alternatively, could you please add an option to verbosely show all timed out requests, thank you ?

**Comment by joohoi** [comment]
Ok so as the response is never received, we cannot use the "normal" match route. For now the fix is to print out timeouts if time based matching is active.
