### ISSUE TITLE
Possibility to output the response data as `curl -i` do

### ISSUE THREAD

**Issue by n3rada** [ffuf/ffuf#716]
Hi maintainers,

I would really appreciate it if will be possible to display the contents of the response as `curl -i` do. The main use case is when an identification cookie is sent as a response to identify the user and you want to brute force user identification with for example: 

```shell
seq 20004400 20004500 | ffuf -w -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "contact_id=FUZZ" -u https://portal-client/restricted/preview/ -mc 302
```

In the case, I want to retrieve the `cookie` named `user_unique_id`.

**Comment by joohoi** [comment]
In my opinion it’s not very feasible to do by printing out to stdout (as
some responses can be HUGE). And  -od outputdirname/ already exists. -od
will write the full raw request and response to a file for each matched
request.

**Comment by n3rada** [comment]
If they can be saved to a file, can't they be displayed on standard output by looping through them instead of saving them? Leaving the possibility for a user to make a pipe.

**Comment by joohoi** [comment]
Sure, it's not a technical issue (and even with output-file writing, you could work with your piped script around that), but I believe it should be handled in another way. 

For this specific use case (Getting the `Set-Cookie`  values from responses, there are much more convenient ways to do it in ffuf. One that immediately comes to mind that would require way less scripting around is to use the [scraper functionality](https://github.com/ffuf/ffuf/wiki/Scraper). Or is there something that i'm missing?

**Comment by joohoi** [comment]
There are examples provided in the wiki linked above ( https://github.com/ffuf/ffuf/wiki/Scraper ). It should be easy enough to adapt to your need.

**Comment by n3rada** [comment]
Thanks @joohoi, closable issue tho'
