### ISSUE TITLE
Align stdout output 

### ISSUE THREAD

**Issue by SakiiR** [ffuf/ffuf#72]
It is kinda hard to read when there is long lines :)

**Comment by SakiiR** [comment]
Here it is misaligned

![Screenshot 2019-10-03 at 15 42 11](https://user-images.githubusercontent.com/9950578/66131850-6a513a80-e5f4-11e9-95c2-6b9ee630a215.png)

**Comment by joohoi** [comment]
This gets even worse when presenting info for multiple keywords / values ( #79 ). I'm really not too happy about the current output.

**Comment by joohoi** [comment]
This is fixed in `-v` (verbose) output as well as multi-wordlist output.
