### ISSUE TITLE
hello，I want to ask you something

### ISSUE THREAD

**Issue by eeeeeeeeee-code** [ffuf/ffuf#725]
Hello, is there a random User-Agent header featrue?  I tried to look, but I couldn't find it.

**Comment by bsysop** [comment]
Hey @eeeeeeeeee-code, unfortunately not,

You can use a bash function to run a random User-Agent every time, but it will affect all the requests of that execution and will not use a new User-Agent for each request.

**Comment by eeeeeeeeee-code** [comment]
Yes, I know.  However, a large number of requests, his ua head has not changed, will be detected by some devices.  I'm so helpless,[T-T]
