### ISSUE TITLE
CSV was not generated in expected format

### ISSUE THREAD

**Issue by Cellesti** [ffuf/ffuf#730]
Hi, while running ffuf's test suite, i encountered the following error:
```
--- FAIL: TestToCSV (0.00s)
    file_csv_test.go:42: CSV was not generated in expected format
FAIL
FAIL	github.com/ffuf/ffuf/v2/pkg/output	0.002s
FAIL
```

I think this is due to the CSV test not being updated for the new ffufhash functionality.

**Comment by joohoi** [comment]
Thanks for creating the issue!
