### ISSUE TITLE
Outfile not creating or not filling.

### ISSUE THREAD

**Issue by hvprvtr** [ffuf/ffuf#743]
Hello. Using simple commands like 
`ffuf -t 5 -w "iis.txt:IIS" -w small.txt -u https://IIS/FUZZ -e ".apsx" -x socks5://1.1.1.1:55555-o iis.out`
`ffuf -u "https://domain.com/FUZZ" -t 5 -w big.txt  -x socks5://1.1.1.1:55555 -fw 6 -e ".aspx,.txt" -o domain.out`
And outfiles not creating with ~50% chance.

v2.1.0, kali.

**Comment by bsysop** [comment]
Hi @hvprvtr

The first command you sent is using `-x socks5://1.1.1.1:55555-o iis.out` instead of `-x socks5://1.1.1.1:55555 -o iis.out`

Can you double-check, please?

Thanks.
