### ISSUE TITLE
Allow filter size greater/less than value & write output to file dynamic

### ISSUE THREAD

**Issue by bugoverfl0w** [ffuf/ffuf#747]
Dear team,

Thank you for your great tools.

I have a question here.

- Should you make ffuf filter response size with > or <? example -fs ">1000"
- Should you allow write output dynamic each result? For example I have 5 million requests. It should write to output (csv) file each matches found. Currently it wait for ffuf finished then write to file. With big files, data can not write (broken when running sometimes)

Thank you for your time and consideration!

**Comment by bsysop** [comment]
Hi @bugoverfl0w, that's already possible:

- `-fs 1000-1000000` will filter responses bigger than 1000

The same applies to any other matcher/filter.

Happy hacking.

**Comment by bugoverfl0w** [comment]
Thanks for your reply @bsysop 

How about this one?

> Should you allow write output dynamic each result? For example I have 5 million requests. It should write to output (csv) file each matches found. Currently it wait for ffuf finished then write to file. With big files, data can not write (broken when running sometimes)

Currently I must wait for ffuf finished then it will write to output file. But some big files about > 10M rows, the ffuf will stop random without writing any output

**Comment by bsysop** [comment]
It's a great idea, it's in the queue -> https://github.com/ffuf/ffuf/issues/513
Unfortunately, no time estimation for implementation.

**Comment by bugoverfl0w** [comment]
Thank you, master

I hope you can implement it soon :D

**Comment by bsysop** [comment]
I hope so :)
