### ISSUE TITLE
Feature Request: Use wordlist to provide multiple file names for output

### ISSUE THREAD

**Issue by 0xcrypto** [ffuf/ffuf#753]
I like to keep my output in seperate files and if ffuf could categorize the output based on the keyword to files, it would be awesome. Something like this:

```
ffuf -w targets.txt -u "http://FUZZ/some_path" -of csv -o FUZZ_main.csv
```

Expected result would be seperate files for each word in the wordlist.

**Comment by bsysop** [comment]
Hey @0xcrypto,
Could you please tell why do you want the output in separate files?

If you really want to do that, I recommend you to use bash/python to parse the ffuf json/csv output file and then split it into multiple files

Thinking in a real scenario, it could be a mess, since you could have hundreds of files (if not thousands), making it harder to parse.

**Comment by 0xcrypto** [comment]
> Hey @0xcrypto,
> Could you please tell why do you want the output in separate files?
> 
> If you really want to do that, I recommend you to use bash/python to parse the ffuf json/csv output file and then split it into multiple files
> 
> Thinking in a real scenario, it could be a mess, since you could have hundreds of files (if not thousands), making it harder to parse.

if you look at the example command I have given, I am using targets.txt as wordlist. I wanna keep each match for that target in a separate file. Like example-com.csv and foobar-com.csv both separate containing the matched string https://example.com/some_path and https://foobar.com/some_path respectively.

**Comment by bsysop** [comment]
hi @0xcrypto, now I got your point.
But in your command arguments, you are fuzzing for a single path, which means each file will contain a maximum one line

Are you saying you would fuzz using two wordlists?

**Comment by 0xcrypto** [comment]
Yes single and multiple both. In the case of single matches, This feature can help separate targets based on the matched/filtered code/size.

```
ffuf -w targets.txt -u "http://FUZZ/some_path" -mc 200 -of csv -o FUZZ_main.csv
```

As for multiple, it can help in categorizing matched cases based on a wordlist like target.

````
ffuf -w detect-tech.txt:PATH -w targets.txt:TARGET -u "http://TARGET/PATH" -of csv -o TARGET_main.csv
```

**Comment by bsysop** [comment]
Hi @0xcrypto,
Using JSON format, you can have all that information, just need to parse using `jq`

Happy hacking.

**Comment by 0xcrypto** [comment]
> Hi @0xcrypto,
> Using JSON format, you can have all that information, just need to parse using `jq`
> 
> Happy hacking.

ah yes, I can parse CSV as well but if this was an inbuilt feature, it would have been much easier.

**Comment by bsysop** [comment]
Gotcha, for specific cases like that, I recommend you create a fork or a parsing external tool, I guess it can't be that hard :)
Good luck @0xcrypto
