### ISSUE TITLE
Latest version is not installed

### ISSUE THREAD

**Issue by r00ki33** [ffuf/ffuf#760]
I am using Kali Linux and I installed Ffuf using git clone, now the 1.3.1 version is installed but the latest version is 2.1.0. Am I doing something wrong? Can I be guided? I'd be thankful!

**Comment by lrluque** [comment]
@r00ki33 

try to manually install it from here: [https://github.com/ffuf/ffuf/releases/tag/v2.1.0](https://github.com/ffuf/ffuf/releases/tag/v2.1.0)

**Comment by bsysop** [comment]
Hi @r00ki33, Kali comes with ffuf but in a stable version!
As mentioned by @lrluque, feel free to download a new version from releases or using `go install`
