### ISSUE TITLE
not showing output

### ISSUE THREAD

**Issue by vishaldalimbe** [ffuf/ffuf#763]
Encountered error(s): 1 errors occurred.
        * bufio.Scanner: token too long

**Comment by bsysop** [comment]
Hi @vishaldalimbe, that problem likely happens when you are fuzzing:
A) The wordlist contains words extremely long
B) The wordlist file is huge

Have you more details on how the wordlist is?

**Comment by vishaldalimbe** [comment]
Extremely thank you for replying.

**Comment by vishaldalimbe** [comment]
hello  @bsysop I am using SecLists (web content) for fuzzing. It was showing this error. i have solved this wordlsits error.
I have created a wordlist manually. then  tool is running properly
i would like  to  thank you.
