### ISSUE TITLE
about -rate

### ISSUE THREAD

**Issue by SMILESHx** [ffuf/ffuf#764]
<img width="821" alt="Screenshot 2024-03-01 083640" src="https://github.com/ffuf/ffuf/assets/145313396/dfcb22b9-89cb-4cec-8936-425c9eaa8c50">

**Comment by bsysop** [comment]
Hi @SMILESHx, you are using FFUF v1.1.0, the last version is v2.1.0, please download an updated version!
Happy Hacking!.
