### ISSUE TITLE
Feature request: use files as payloads.

### ISSUE THREAD

**Issue by gnunez88** [ffuf/ffuf#766]
Hello,

I would like `ffuf` to be able to use file contents instead of specifying the payloads always in the command line. It will be really useful for some JSON requests and especially for XML requests.

For instance:

```
ffuf -c -u http://example.com -d @payload.xml -H "Content-Type: application/xml" -w usernames.txt:USER -w passwords.txt:PASS
```

where `payload.xml` content is:

```
<?xml version="1.0" encoding="utf-8"?>
<application>
    <action>login</action>
    <data>
        <username>USER</username>
        <password>PASS</password>
    </data>
</application>
```

The notation I have described, with the at sign, is the same one `curl` uses to add file contents. Since `ffuf` has many options similar to `curl`, I think this should be more appropriate.

Thank you!

**Comment by bsysop** [comment]
Hi @gnunez88,
I wonder if in your test case, could you use the raw request itself.

`ffuf -request your_request_file -request-proto https -w wordlist [...]`

What would be the benefits of using @payload instead of a raw request?

**Comment by gnunez88** [comment]
I probably could have used the `-request` option. For me, the benefits of `@payload`:

1. Muscle memory for those who use `curl` along with `ffuf` to test how the request should be.
2. Sometimes, we might have some common payloads as PoCs for some vulnerabilities or behaviours. But I guess we can use `nuclei` for this anyway.

Those are two weak arguments. I wll have into account `-request`, and feel free to close this "issue". Thank you!

**Comment by bsysop** [comment]
Hi @gnunez88,

Understand, I thought you were sending some kind of binary payload or something, that would make sense for the usage @payload

It's awesome that `-request` works for you.

Happy hacking.
