### ISSUE TITLE
Suggest [ Follow The directories and Bruteforce On them In the same Command ]

### ISSUE THREAD

**Issue by MMrhassel** [ffuf/ffuf#77]
### Like This : 
```
ffuf -w list.txt -u https://Site.com/FUZZ -fc 403 
......
[2Kadmin              [Status: 301, Size: 413, Words: 46]
[2Kuploads              [Status: 301, Size: 414, Words: 46]
```
.....
###  When this complete The Ffuf Automatically Will Brute force On /admin/ And /uploads/

**Comment by joohoi** [comment]
This is a good suggestion, however as ffuf allows you to inject the wordlist data to other parts of the request than the URL, this feature is unlikely to get included. I feel that it's better to leave it off than to implement it half way through. This obviously wouldn't work in expected way in situations where you fuzz anything but the very "end" of the URL.

Examples of where this would not work:
```
ffuf -u https://example.com/FUZZ/rest/of/the/path ...
```
```
ffuf -h https://example.com/api/v1/endpoint -H "Whatever: FUZZ" ...
```

**Comment by MMrhassel** [comment]
You Right

Thank You so much for the great tool
