### ISSUE TITLE
Option -sa doesn't work properly (i think, not sure if i really understand it, anyways, would be great if this could be changed / added)

### ISSUE THREAD

**Issue by 0xNoport** [ffuf/ffuf#776]
I was performing a FUZZ scan as usual, when ffuf started scanning another directory, all words from the wordlist including the extensions had a 302 status code, so false positives. The -sa option doesn't filter that out. Here is the output:
![image](https://github.com/ffuf/ffuf/assets/125758265/b1ee2bb3-855b-4dfe-a031-04d6212bc8ab)

This output on the bottom is the whole file.
I would really appreciate if you could look into it.

**Comment by Matelz** [comment]
@0xNoport Try the `-fc 302` option, it will ignore all the **302** responses.

**Comment by bsysop** [comment]
Hi @0xNoport, all the 302 redirects you got start with `!`, which is an edge case, ffuf autocalibration will try to filter the default ones.

If you want to improve autocalibration, you can use `-ac -acc "!unknown"` to also gather and filter those, but remember it can make you lose some hits.

Happy hacking and feel free to re-open the issue if you want to add something else.

**Comment by bsysop** [comment]
Double-checking your screenshot, if you add `-acc !unknown`, you will miss the "/index.php" finding and maybe a few more.
