### ISSUE TITLE
ffuf out put issue

### ISSUE THREAD

**Issue by BlueHatOrganization** [ffuf/ffuf#777]
![Fuff](https://github.com/ffuf/ffuf/assets/146252574/39f654ff-f980-4648-b721-e1cc99d06519)

**Comment by bsysop** [comment]
Hi @BlueHatOrganization, can you add some explanation, please?

**Comment by BlueHatOrganization** [comment]
ffuf -c -u https.//abc.com/FUZZ -w wordlists -mc 200, 404 -o abc.txt -v after type this command out put save to abc.txt. when i open it the file is open  before given image format. please help.

**Comment by bsysop** [comment]
The default output it's JSON.

```
  -o                  Write output to file
  -od                 Directory path to store matched results to.
  -of                 Output file format. Available formats: json, ejson, html, md, csv, ecsv (or, 'all' for all formats) (default: json)
  -or                 Don't create the output file if we don't have results (default: false)
```

**Ex:** `-o file.csv -of csv`

**Comment by psych4cker** [comment]
the same problem is happening with me

**Comment by psych4cker** [comment]
I want the output in txt format but I am unable

**Comment by bsysop** [comment]
Hi @psych4cker, how is the format you want?

CSV? Or just plain text? you can just send the output to a file `ffuf [...] | tee your_file.txt`

**Comment by psych4cker** [comment]
![Screenshot from 2024-07-03 00-54-06](https://github.com/ffuf/ffuf/assets/162889818/4fe8dbac-2f03-454c-9e53-35a9a022c517)
By any chance can I get only the output(only FUZZ things) without the status, size and all

**Comment by psych4cker** [comment]
and I know I can do that with awk command but just curious if the only one liner can do that while using ffuf, it will save some time
