### ISSUE TITLE
window instantly opens and closes in a second (win 11 arm64 build newest release)

### ISSUE THREAD

**Issue by OneAndOnlyBarrettt** [ffuf/ffuf#780]
window instantly opens and closes in a second (win 11 arm64 build newest release)

**Comment by bsysop** [comment]
Hi @OneAndOnlyBarrettt, ffuf is not GUI but Command Line,
Have you tried to run it in your cmd or PowerShell?

**Comment by bsysop** [comment]
Closing this by now, please re-open if you have more information.
