### ISSUE TITLE
Feature request: Ingest NMAP XML file as targets

### ISSUE THREAD

**Issue by d-woosley** [ffuf/ffuf#782]
Thank you so much for this great tool! I use it at least once a week on pentests.

As part of my internal pentest workflow, I will perform directory enumeration against the whole internal network. However, to do this right now I have to run a  tool to figure out which ports support HTTP(S) and then parse that tool output and send it as input to ffuf. It would be very helpful to have an option that would ingest a straight Nmap XML file, attempt HTTP and HTTPS connections to each port to see what port/host combo's support HTTP(S), and then kickoff a directory enumeration scan with ffuf.

Something like the following:
```bash
ffuf -w portscan.xml:NMAP -w wordlist.txt:PATH -u NAMP/PATH
```

**Comment by bsysop** [comment]
Hi @d-woosley, this is very specific, you could use a bash/python wrapper!

**Comment by d-woosley** [comment]
Absolutely! That philosophy makes sense. I'll run this with a wrapper or other tools to generate the target list. Thanks again for the great tool!
