### ISSUE TITLE
Can we Fuzz 2 Request Header at the same time?

### ISSUE THREAD

**Issue by Rizatzmi** [ffuf/ffuf#784]
I want to Fuzz Request Header at the same time. For example Fuzz ``User Agent`` and ``X-Forwarder-For``, Which is that Wordlist for that two header is different, and I want the process is like this ``User Agent 1`` AND ``X-Forwarder-For 1`` to the last ``X-Forwarder-For`` after that go to ``User Agent 2`` AND ``X-Forwarded-For-1`` to the last, This process is repeated until the last ``User Agent``. How I can do that?

**Comment by bsysop** [comment]
Hi @Rizatzmi,

If I understood your question, you want to fuzz two headers at the same time using clusterbomb mode.

```bash
ffuf -w user-agents.txt:UA -w x-forwarded-for.txt:XFF -u http://example.com -H "User-Agent: UA" -H "X-Forwarded-For: XFF" -mode clusterbomb
```

That make sense to you?

**Comment by Rizatzmi** [comment]
Thx for the replies @bsysop ,

That means that ``:UA`` and ``XFF`` are parameters for wordlist usage, are they named parameters or positional parameters?

**Comment by bsysop** [comment]
You can define any "TAG" for your wordlist and then use it whatever you want.

```bash
ffuf -w user-agents.txt:WL2 -w x-forwarded-for.txt:WL1 -u http://example.com -H "User-Agent: WL2" -H "X-Forwarded-For: WL1" -mode clusterbomb
```

Feel free to re-open the ticket if you have additional questions.

Happy hacking.
