### ISSUE TITLE
How to read website from the txt file

### ISSUE THREAD

**Issue by mikykatwal** [ffuf/ffuf#785]
I have a list of website in the text file all-alive.txt and I want to read from it how can I achieve this ?

ffuf -u https://tinder.com/FUZZ -w fuzz.txt
this works fine. 

while reading the website it shows error 
ffuf -u all-alive.txt/FUZZ -w fuzz.txt

**Comment by rbih-boulanouar** [comment]
You can use it like this
```
ffuf -w all-alive.txt:URL -w fuzz.txt:FUZZ -u URL/FUZZ
```

**Comment by bsysop** [comment]
Closing this by now, feel free to re-open @mikykatwal
