### ISSUE TITLE
How to skip a job

### ISSUE THREAD

**Issue by rbih-boulanouar** [ffuf/ffuf#786]
When I use the flag `-recursion` is there any way to skip some of jobs in the queue?
for example if I run
```
ffuf -w worlist.txt -u http://example.com/FUZZ -recursion
```
and got something like this
```
[INFO] Adding a new job to the queue: http://example.com/fonts/FUZZ

[INFO] Adding a new job to the queue: http://example.com/images/FUZZ

[INFO] Adding a new job to the queue: http://example.com/js/FUZZ

[INFO] Adding a new job to the queue: http://example.com/secrets/FUZZ
```
is there is a way to remove or skip the first 3 jobs and keep just `http://example.com/secrets/FUZZ`?

**Comment by joohoi** [comment]
Yeah, hit enter to go in to interactive mode, and as your first command use "help". It should guide you through the process of removing unwanted recursion jobs.

**Comment by rbih-boulanouar** [comment]
thanks that worked
