### ISSUE TITLE
-fs -fw -fl Not Working

### ISSUE THREAD

**Issue by birbalkr** [ffuf/ffuf#791]
![Screenshot from 2024-06-03 15-59-06](https://github.com/ffuf/ffuf/assets/153169574/5bcc87d8-092c-421d-b651-259e5242a32e)

**Comment by bsysop** [comment]
Hi @birbalkr, please show what arguments you used, what you expected, and what the unexpected results were.

Thank you.

**Comment by birbalkr** [comment]
I'm try filter Response size = 0 and Line = 1 but show all size 985, Line=55 
command is :- **ffuf -w /path/to/vhost/wordlist:FUZZ -u https://target -H "Host: FUZZ/academy.htb" -fs 0 -fl 1 -v**

**Comment by bsysop** [comment]
`-f` means ignore
`-m` means match

-mc = match code (status code)
-fc = filter status code

Happy hacking.
