### ISSUE TITLE
Combined filters

### ISSUE THREAD

**Issue by hvprvtr** [ffuf/ffuf#794]
Hello! Its will be great to have a possibility for combined filters usage. Now i can set filter code and filter size separatelay, like "-fc 301 -fs 100", but what if i need size filter only with  one response code? Like "filter only 301 codes with 100 bytes response size, and filter 500 codes with 200 bytes responses size. Accept other 301 and 500 codes."

**Comment by rbih-boulanouar** [comment]
I think you can use `-fmode` flag to combine filters, by default its set to `or` you can change it to `and` so it applies `and ` operator on the filters. you can also use it on match using the flag `-mmode`

**Comment by bsysop** [comment]
Closing this by now, feel free to re-open.
