### ISSUE TITLE
Handling litteral headers lists

### ISSUE THREAD

**Issue by zar3bski** [ffuf/ffuf#804]
Some very useful Header wordlists out there contain **both key and values**. Such is the case for [these common non standards](https://github.com/danielmiessler/SecLists/blob/master/Miscellaneous/Web/http-request-headers/http-request-headers-common-non-standard-examples.txt) from **SecLists**

However, if I 

```
ffuf -u http://capiclean.htb/server-status -H "FUZZ" -w /usr/share/wordlists/seclists/Miscellaneous/web/http-request-headers/http-request-headers-common-standard-examples.txt
```

I end up with the following error 

```
Encountered error(s): 1 errors occurred.
        * Header defined by -H needs to have a value. ":" should be used as a separator
```
raised by https://github.com/ffuf/ffuf/blob/master/pkg/ffuf/optionsparser.go#L402

There should also be a way to pass litteral param value headers. Instead of 

```go
if len(hs) == 2 {
    // ....
} else {
    errs.Add(fmt.Errorf("Header defined by -H needs to have a value. \":\" should be used as a separator"))
}
```
this use of litteral could be logged. Something like 

```go
if len(hs) == 2 {
    // ....
} else {
    fmt.Sprint("Litteral Header parameter detected, please make sure that the lines of your wordlist follow a KEY: VALUE formatting")
    conf.LitteralHeaders[v] = .....
}
```
`LitteralHeaders` would need to be defined https://github.com/ffuf/ffuf/blob/master/pkg/ffuf/config.go#L7 and this would involved some changes here and there but I would be glad to give it a try to improve this tool I love. 

Best

**Comment by bsysop** [comment]
Hi @zar3bski, ffuf is very flexible allowing to fuzz basically anything in HTTP, but sometimes some edge cases could come, like this one.

You could use ffuf with multiple wordlists and `-mode pitchfork`, do that work for you?

**Workaround:**
```bash
curl -iks https://raw.githubusercontent.com/danielmiessler/SecLists/refs/heads/master/Miscellaneous/Web/http-request-headers/http-request-headers-common-standard-examples.txt -o headers.txt
cut -d':' -f1 headers.txt > wl1
cut -d':' -f1,2,3,4,5 headers.txt > wl2

ffuf -u http://capiclean.htb/server-status -H "WL1: WL2" -w wl1:WL1 -w wl2:WL2 -mode pitchfork
```

**How mode Pitchfork works:**
```
This attack iterates through a different payload set for each defined position. Payloads are placed into each position simultaneously. For example, the first three requests would be:

Request one:
Position 1 = First payload from Set 1.
Position 2 = First payload from Set 2.

Request two:
Position 1 = Second payload from Set 1.
Position 2 = Second payload from Set 2.

Request three:
Position 1 = Third payload from Set 1.
Position 2 = Third payload from Set 2.
```

**Comment by zar3bski** [comment]
Nice hack. I just tested it on a box.
