### ISSUE TITLE
Error with FUZZ, W1, W2 replacing

### ISSUE THREAD

**Issue by daniel2005d** [ffuf/ffuf#807]
When the request contains the words FUZZ, W1, or W2 within any header value, it replaces that text, corrupting the request

**Comment by joohoi** [comment]
Can you elaborate? You can redefine all the keywords on the command line
and make them something that doesn’t mess your specific request up.

**Comment by daniel2005d** [comment]
For example you have:

GET /api/doesnotexists
Host: evil.com
_**W1:W2**_
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMj**_W1_**M0NTY3ODkwIiwibmFtZSI6**_W2_**IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

With FUZZ you run:

ffuf -w words.txt:W1,word2.txt:W2 -request file.txt

But the W1 and W2 in Authorization header are replacing by FUZZING words.

**Comment by daniel2005d** [comment]
OK, thanks for your help.
