### ISSUE TITLE
More than one string in regex

### ISSUE THREAD

**Issue by waall** [ffuf/ffuf#811]
WHAT I WANT:
I would like to filter more than one word if it appears in the RESPONSE, that is, in the example below I only want request 3. That is, if ALPHA OR BRAVO appears, I want it to be filtered.

EXAMPLE:
Request 1 returns the response: "alpha"
Request 2 returns the response: "bravo"
Request 3 returns the response: "charlie"

HOW I'M DOING IT:
```
ffuf -u 'example.com/hotel?whiskey=FUZZ' -w wordlist --fr 'alpha' --fr 'bravo'
ffuf -u 'example.com/hotel?whiskey=FUZZ' -w wordlist --fr 'alpha,bravo'
ffuf -u 'example.com/hotel?whiskey=FUZZ' -w wordlist --fr 'alpha','bravo'
ffuf -u 'example.com/hotel?whiskey=FUZZ' -w wordlist --fr 'alpha' --fr 'bravo' --fmode or
ffuf -u 'example.com/hotel?whiskey=FUZZ' -w wordlist --fr 'alfa,bravo' --fmode or
ffuf -u 'example.com/hotel?whiskey=FUZZ' -w wordlist --fr 'alfa','bravo' --fmode or
```

NOTE: None of the above methods prevented all requests (1, 2 and 3) from being retrieved. However, if there is ALFA OR BRAVO, I would like it to be excluded from the response.

NOTE 2: Yes, if I try with just "--fr" I can filter it.

VERSION: ffuf version: 2.1.0-dev 

HEADERS AND REQUISITION:

```
 :: Method           : GET
 :: URL              : example.com/hotel?whiskey=FUZZ
 :: Wordlist         : FUZZ: wordlist
 :: Follow redirects : true
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 32
 :: Delay            : 2.00 seconds
 :: Matcher          : Response status: all
 :: Filter           : Regexp: alfa,bravo <-- depends the command
```

Thank you for your time!

**Comment by bsysop** [comment]
Hi @waall, you can use normal regex, for example:
`-fr "filter1|filter2"`
`-mr "find1|find2"`

Is that what you need?

If it is not, please re-open the ticket and I will take a closer look.

Happy hacking.

**Comment by waall** [comment]
Ok, it was simply using the regex as it was designed... Sorry
Thanks a lot, ticket closed!

**Comment by bsysop** [comment]
Ffuf magic 🏴‍☠️
