### ISSUE TITLE
Fuff is spaming logs but doesn't delete it

### ISSUE THREAD

**Issue by Samsonov0** [ffuf/ffuf#812]
When I use ffuf, it works, but it doesn't clear the console properly.
I was expecting to get a list of existing api's, but I can't check the list because this spam is all over the place and overrides the results

<img width="619" alt="image" src="https://github.com/user-attachments/assets/a6867c43-03ac-458f-9e65-dab032acd9ec">

What I expected
<img width="702" alt="image" src="https://github.com/user-attachments/assets/abbc5ce0-a552-461d-b89b-e821bbf0ffbb">

**Comment by dextermorgan2007** [comment]
Your console window is too small in first example. Make it bigger and it will work
