### ISSUE TITLE
Great tool. Just replaced dirsearch with this. Can you add the functionality to save the reports of each scan so that we can look at it later? 

### ISSUE THREAD

**Issue by dark-warlord14** [ffuf/ffuf#82]

**Comment by joohoi** [comment]
Thanks for your kind words. There actually already exists few modes to save output to a file (in addition to basically just redirecting the stdout to a file using `ffuf -u .... > output.log`. 

The actual cli options to write the report to different file formats are `-o filename.log` and `-of fileformat`. The current version supports writing the output file in JSON, CSV or eCSV (with input values encoded, in case they contain the delimiter character and such). There's also a PR #63 waiting to get merged to the code tree that adds HTML and Markdown output format support for the reports.

**Comment by SakiiR** [comment]
Btw, that would be great to be able to output in differents formats :)
