### ISSUE TITLE
ffuf QUESTION

### ISSUE THREAD

**Issue by Brutelover** [ffuf/ffuf#821]
Whenever I put wrong url or domain in ffuf It continue to execute while go buster says cant reach host how do i do that in ffuf

**Comment by ola456** [comment]
`-se                 Stop on spurious errors (default: false)` might solve your issue

> % seq 1 999 | ffuf -s -w - -u https://somethingerror5813.tld/FUZZ -se
> Receiving spurious errors, exiting.

**Comment by bsysop** [comment]
Thank you @ola456 
@Brutelover please feel free to re-open if your question was not answered.
