### ISSUE TITLE
[request] stop probes on receiving a lot of 429 status code

### ISSUE THREAD

**Issue by bugbaba** [ffuf/ffuf#83]
Hi  joohoi,

ffuf doesn't stop on receiving 429 status code for probes.
I my opinion the `-sa` flag should also look for `429` status codes and if there are x number of time its repeated then stop the probes.

This is how I am using the ffuf

```
./ffuf -sa -mc all -fc 400,405,406,418,444,500,501,502,503,504,508,520 -ac -c -l -k -r -w untitled.txt -u https://signup.example.com/FUZZ
```
![image](https://user-images.githubusercontent.com/29960776/68129257-42306080-ff3f-11e9-8728-9299e7f61679.png)

**Comment by joohoi** [comment]
Hi @bugbaba 
Thanks for opening the issue!

You are absolutely right, and checking 429 should definitely get added, perhaps not as an individual CLI parameter, but as a check when `-sa` is used.
