### ISSUE TITLE
Maybe decrease to 1 the number of thread by default ? :')

### ISSUE THREAD

**Issue by SakiiR** [ffuf/ffuf#87]
Idk, it can be dangerous you know 🚀

**Comment by joohoi** [comment]
We discussed this OOB and decided against doing it. 

My rationale: when testing a sensitive target, it's most likely already known beforehand, and the user should scale down the thread count `-t` and/or implement breaks between requests `-p`. For majority of the use cases (basis for defaults), people prefer speed.
