### ISSUE TITLE
DataTable for HTML output

### ISSUE THREAD

**Issue by theblackturtle** [ffuf/ffuf#91]
Hi, I think It would be nice if you add DataTable (https://datatables.net/) for html output. We can use it to short Status code or find something.

**Comment by joohoi** [comment]
Thanks for opening the issue. This looks super convenient. Support added in #98

**Comment by SakiiR** [comment]
I am sorry to come while this issue is actually closed. But could we think about disabling the paging ?

It feel horrible to click the next button to see all the results :(

**Comment by theblackturtle** [comment]
@SakiiR I created an issue which has a suggestion for the amount of entries each page (https://github.com/ffuf/ffuf/issues/110)

**Comment by SakiiR** [comment]
oops ! 😨 

Thank you 👍
