### ISSUE TITLE
[Feature request] Recursive fuzzing

### ISSUE THREAD

**Issue by SecT0uch** [ffuf/ffuf#96]
It would be awesome to have a recursive option, with `--recursive` for example, with an option to specify the depth.
Every time we have a 200 response on a folder, ffuf would automatically scan the subfolders after the initial scan.

**Comment by joohoi** [comment]
I have been thinking of this, or rather the way to:
- Signal the user that we just extended the search space, instead of just bumping the total try count up
- Handle it internally in a sane way within `ffuf` codebase.

**Comment by joohoi** [comment]
Additional note: this feature only fits one of the multiple use cases for ffuf, and I would like to keep it all consistent. (as the tool can be used to fuzz HTTP headers, payload etc.)

**Comment by joohoi** [comment]
This was released with `ffuf v.1.0`!
